//! TypeScript LE binary codec emitter.
//!
//! Produces a TypeScript module for Wesley's deterministic little-endian
//! variable codec:
//!
//! - Enums encode their zero-based variant index (declaration order) as `u32` LE.
//! - Input objects encode their fields in declaration order with no separators.
//! - `Boolean` → 1 byte (`0x00` / `0x01`).
//! - `Int` → 4 bytes LE signed.
//! - `Float` → 4 bytes LE (canonicalized inside the Writer).
//! - `String` / `ID` → `u32` LE length + UTF-8 bytes.
//! - Nullable `T` → presence tag (`0x00` null / `0x01` present) + value if present.
//! - Non-null list `[T!]!` → `u32` LE element count + inline elements.
//!
//! Every emitted operation produces an `encode<Op>Vars(v) -> Uint8Array` /
//! `decode<Op>Vars(b) -> <Op>Vars` pair. Hosts or extension modules can use
//! those helpers as their transport boundary without Wesley owning the runtime
//! behavior behind the operation.

use std::fmt::Write;

use wesley_core::{
    stable_op_id, OperationArgument, OperationType, SchemaOperation, TypeDefinition, TypeKind,
    TypeReference, WesleyIR,
};

/// Default import path the emitted module uses to reach the TypeScript
/// `Writer` / `Reader` / `CodecError` primitives. Suitable for files written
/// to `<root>/src/generated/<app>/<schema>.codec.generated.ts` when the
/// primitives live at `<root>/src/codec.ts`.
pub const DEFAULT_CODEC_IMPORT: &str = "../../codec.js";

const HEADER: &str = "\
/* @generated by wesley-emit-typescript le-binary. Do not edit. */
// SPDX-License-Identifier: Apache-2.0
//
// Wire layout is Wesley little-endian variable codec v0. Field order is SDL
// declaration order. Enums encode their zero-based variant index as u32 LE.
";

/// Emit a TypeScript LE binary codec module for the given Wesley IR.
///
/// `codec_import_path` is the module specifier the emitted file uses to
/// import `Writer`, `Reader`, and `CodecError`. Pass [`DEFAULT_CODEC_IMPORT`]
/// when the generated file is two directories below the codec primitives.
pub fn emit_le_binary_typescript(
    ir: &WesleyIR,
    operations: &[SchemaOperation],
    codec_import_path: &str,
) -> String {
    let mut out = String::from(HEADER);
    out.push('\n');
    let _ = writeln!(
        out,
        "import {{ Writer, Reader, CodecError }} from {};",
        quote_string(codec_import_path)
    );

    for type_def in &ir.types {
        match type_def.kind {
            TypeKind::Enum => emit_enum(&mut out, type_def),
            TypeKind::InputObject => emit_input_object(&mut out, type_def),
            _ => {}
        }
    }

    for operation in operations {
        emit_operation_vars(&mut out, operation);
    }

    out
}

fn emit_enum(out: &mut String, type_def: &TypeDefinition) {
    let name = pascal_case(&type_def.name);

    let _ = writeln!(out, "\n// ─── enum {} ───", type_def.name);
    if type_def.enum_values.is_empty() {
        let _ = writeln!(out, "export type {name} = never;");
    } else {
        let mut iter = type_def.enum_values.iter();
        let first = iter.next().expect("non-empty enum");
        let _ = writeln!(out, "export type {name} =");
        let _ = write!(out, "    | '{first}'");
        for value in iter {
            out.push('\n');
            let _ = write!(out, "    | '{value}'");
        }
        out.push_str(";\n");
    }

    let _ = writeln!(
        out,
        "export function _enc{name}(w: Writer, v: {name}): void {{"
    );
    let _ = writeln!(out, "    switch (v) {{");
    for (index, value) in type_def.enum_values.iter().enumerate() {
        let _ = writeln!(
            out,
            "        case '{value}': w.writeU32Le({index}); return;"
        );
    }
    if type_def.enum_values.is_empty() {
        let _ = writeln!(out, "        // no variants");
    } else {
        let _ = writeln!(
            out,
            "        default: throw new CodecError('invalid {name} variant: ' + String(v));"
        );
    }
    let _ = writeln!(out, "    }}");
    let _ = writeln!(out, "}}");

    let _ = writeln!(out, "export function _dec{name}(r: Reader): {name} {{");
    let _ = writeln!(out, "    const d = r.readU32Le();");
    let _ = writeln!(out, "    switch (d) {{");
    for (index, value) in type_def.enum_values.iter().enumerate() {
        let _ = writeln!(out, "        case {index}: return '{value}';");
    }
    let _ = writeln!(
        out,
        "        default: throw new CodecError('invalid {name} discriminant: ' + String(d));"
    );
    let _ = writeln!(out, "    }}");
    let _ = writeln!(out, "}}");

    let _ = writeln!(
        out,
        "export function encode{name}(v: {name}): Uint8Array {{"
    );
    let _ = writeln!(out, "    const w = new Writer();");
    let _ = writeln!(out, "    _enc{name}(w, v);");
    let _ = writeln!(out, "    return w.finish();");
    let _ = writeln!(out, "}}");

    let _ = writeln!(
        out,
        "export function decode{name}(b: Uint8Array): {name} {{"
    );
    let _ = writeln!(out, "    return _dec{name}(new Reader(b));");
    let _ = writeln!(out, "}}");
}

fn emit_input_object(out: &mut String, type_def: &TypeDefinition) {
    let name = pascal_case(&type_def.name);

    let _ = writeln!(out, "\n// ─── input {} ───", type_def.name);
    let _ = writeln!(out, "export interface {name} {{");
    for field in &type_def.fields {
        let ts_ty = ts_type_for_reference(&field.r#type);
        let _ = writeln!(out, "    {}: {ts_ty};", property_key(&field.name));
    }
    let _ = writeln!(out, "}}");

    let _ = writeln!(
        out,
        "export function _enc{name}(w: Writer, v: {name}): void {{"
    );
    for field in &type_def.fields {
        emit_encode_field(out, "v", &field.name, &field.r#type);
    }
    let _ = writeln!(out, "}}");

    let _ = writeln!(out, "export function _dec{name}(r: Reader): {name} {{");
    let _ = writeln!(out, "    return {{");
    for field in &type_def.fields {
        emit_decode_field_initializer(out, &field.name, &field.r#type);
    }
    let _ = writeln!(out, "    }};");
    let _ = writeln!(out, "}}");
}

fn emit_operation_vars(out: &mut String, operation: &SchemaOperation) {
    let pascal = pascal_case(&operation.field_name);
    let vars_name = format!("{pascal}Vars");
    let op_const = op_const_name(&operation.field_name);
    let op_id = stable_op_id(operation.operation_type, &operation.field_name);

    let scope = match operation.operation_type {
        OperationType::Query => "query",
        OperationType::Mutation => "mutation",
        OperationType::Subscription => "subscription",
    };
    let _ = writeln!(out, "\n// ─── {scope} {} ───", operation.field_name);

    let _ = writeln!(
        out,
        "/** EINT op id for {} `{}`. Stable across Rust and TypeScript emitters. */",
        scope, operation.field_name
    );
    let _ = writeln!(out, "export const {op_const}: number = {op_id};");

    let _ = writeln!(out, "export interface {vars_name} {{");
    for argument in &operation.arguments {
        let ts_ty = ts_type_for_reference(&argument.r#type);
        let _ = writeln!(out, "    {}: {ts_ty};", property_key(&argument.name));
    }
    let _ = writeln!(out, "}}");

    let _ = writeln!(
        out,
        "export function encode{vars_name}(v: {vars_name}): Uint8Array {{"
    );
    let _ = writeln!(out, "    const w = new Writer();");
    for argument in &operation.arguments {
        emit_encode_argument(out, "v", argument);
    }
    let _ = writeln!(out, "    return w.finish();");
    let _ = writeln!(out, "}}");

    let _ = writeln!(
        out,
        "export function decode{vars_name}(b: Uint8Array): {vars_name} {{"
    );
    let _ = writeln!(out, "    const r = new Reader(b);");
    let _ = writeln!(out, "    return {{");
    for argument in &operation.arguments {
        emit_decode_field_initializer(out, &argument.name, &argument.r#type);
    }
    let _ = writeln!(out, "    }};");
    let _ = writeln!(out, "}}");
}

fn emit_encode_argument(out: &mut String, parent: &str, argument: &OperationArgument) {
    emit_encode_field(out, parent, &argument.name, &argument.r#type);
}

fn emit_encode_field(out: &mut String, parent: &str, field_name: &str, ty: &TypeReference) {
    let access = format!("{parent}.{}", property_key(field_name));

    if ty.is_list {
        let element_call = scalar_encode_call(&ty.base, "w", "x");
        let element_lambda = format!("(w, x) => {element_call}");
        if ty.nullable {
            let _ = writeln!(
                out,
                "    w.writeOption({access}, (w, xs) => w.writeList(xs, {element_lambda}));"
            );
        } else {
            let _ = writeln!(out, "    w.writeList({access}, {element_lambda});");
        }
        return;
    }

    if ty.nullable {
        let inner = scalar_encode_call(&ty.base, "w", "x");
        let _ = writeln!(out, "    w.writeOption({access}, (w, x) => {inner});");
    } else {
        let _ = writeln!(out, "    {};", scalar_encode_call(&ty.base, "w", &access));
    }
}

fn emit_decode_field_initializer(out: &mut String, field_name: &str, ty: &TypeReference) {
    let key = property_key(field_name);

    if ty.is_list {
        let element_call = scalar_decode_call(&ty.base, "r");
        let list_expr = format!("r.readList((r) => {element_call})");
        if ty.nullable {
            let _ = writeln!(
                out,
                "        {key}: r.readOption((r) => r.readList((r) => {element_call})),"
            );
        } else {
            let _ = writeln!(out, "        {key}: {list_expr},");
        }
        return;
    }

    if ty.nullable {
        let inner = scalar_decode_call(&ty.base, "r");
        let _ = writeln!(out, "        {key}: r.readOption((r) => {inner}),");
    } else {
        let _ = writeln!(out, "        {key}: {},", scalar_decode_call(&ty.base, "r"));
    }
}

fn scalar_encode_call(type_name: &str, writer: &str, value: &str) -> String {
    match type_name {
        "Boolean" => format!("{writer}.writeBool({value})"),
        "Int" => format!("{writer}.writeI32Le({value})"),
        "Float" => format!("{writer}.writeF32Le({value})"),
        "String" | "ID" => format!("{writer}.writeString({value})"),
        other => format!("_enc{}({writer}, {value})", pascal_case(other)),
    }
}

fn scalar_decode_call(type_name: &str, reader: &str) -> String {
    match type_name {
        "Boolean" => format!("{reader}.readBool()"),
        "Int" => format!("{reader}.readI32Le()"),
        "Float" => format!("{reader}.readF32Le()"),
        "String" | "ID" => format!("{reader}.readString()"),
        other => format!("_dec{}({reader})", pascal_case(other)),
    }
}

fn ts_type_for_reference(ty: &TypeReference) -> String {
    let mut base = match ty.base.as_str() {
        "ID" | "String" => "string".to_string(),
        "Int" | "Float" => "number".to_string(),
        "Boolean" => "boolean".to_string(),
        other => pascal_case(other),
    };

    if ty.is_list {
        let element = if matches!(ty.list_item_nullable, Some(true)) {
            format!("({base} | null)")
        } else {
            base.clone()
        };
        base = format!("{element}[]");
    }

    if ty.nullable {
        format!("{base} | null")
    } else {
        base
    }
}

/// Convert an operation field name to its `OP_<UPPER_SNAKE>` constant name.
///
/// Matches the Wesley operation-constant convention so emitted op id constants
/// share the same identifier shape across generated surfaces
/// (e.g. `createRecord` → `OP_CREATE_RECORD`).
fn op_const_name(name: &str) -> String {
    let mut out = String::new();
    for (index, ch) in name.chars().enumerate() {
        if ch.is_alphanumeric() {
            if ch.is_uppercase() && index > 0 {
                out.push('_');
            }
            out.push(ch.to_ascii_uppercase());
        } else {
            out.push('_');
        }
    }
    if out.is_empty() {
        return "OP_UNNAMED".to_string();
    }
    format!("OP_{out}")
}

fn pascal_case(name: &str) -> String {
    let mut out = String::new();
    let mut next_upper = true;
    for ch in name.chars() {
        if ch.is_alphanumeric() {
            if next_upper {
                out.push(ch.to_ascii_uppercase());
                next_upper = false;
            } else {
                out.push(ch);
            }
        } else {
            next_upper = true;
        }
    }
    if out.is_empty() {
        "Op".to_string()
    } else {
        out
    }
}

fn property_key(name: &str) -> String {
    if is_safe_identifier(name) {
        name.to_string()
    } else {
        let mut quoted = String::from("'");
        for ch in name.chars() {
            match ch {
                '\\' => quoted.push_str("\\\\"),
                '\'' => quoted.push_str("\\'"),
                _ => quoted.push(ch),
            }
        }
        quoted.push('\'');
        quoted
    }
}

fn is_safe_identifier(name: &str) -> bool {
    let mut chars = name.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    if !(first.is_ascii_alphabetic() || first == '_' || first == '$') {
        return false;
    }
    for ch in chars {
        if !(ch.is_ascii_alphanumeric() || ch == '_' || ch == '$') {
            return false;
        }
    }
    true
}

fn quote_string(value: &str) -> String {
    let mut out = String::from("'");
    for ch in value.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '\'' => out.push_str("\\'"),
            _ => out.push(ch),
        }
    }
    out.push('\'');
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use wesley_core::{list_schema_operations_sdl, lower_schema_sdl};

    const SDL: &str = "
        enum Color { RED GREEN BLUE }

        input MakeWidgetInput {
            label: String!
            count: Int!
            color: Color
            tags: [String!]!
        }

        type Widget { id: ID! label: String! }

        type Mutation {
            makeWidget(input: MakeWidgetInput!): Widget!
        }
    ";

    #[test]
    fn emits_typescript_codec_for_minimal_schema() {
        let ir = lower_schema_sdl(SDL).expect("schema lowers");
        let ops = list_schema_operations_sdl(SDL).expect("operations enumerable");

        let ts = emit_le_binary_typescript(&ir, &ops, DEFAULT_CODEC_IMPORT);

        assert!(ts.contains("import { Writer, Reader, CodecError } from '../../codec.js';"));
        assert!(ts.contains("export type Color =\n    | 'RED'\n    | 'GREEN'\n    | 'BLUE';"));
        assert!(ts.contains("case 'RED': w.writeU32Le(0); return;"));
        assert!(ts.contains("case 'BLUE': w.writeU32Le(2); return;"));
        assert!(ts.contains("export interface MakeWidgetInput"));
        assert!(ts.contains("label: string;"));
        assert!(ts.contains("color: Color | null;"));
        assert!(ts.contains("tags: string[];"));
        assert!(ts.contains("export interface MakeWidgetVars"));
        assert!(ts.contains("input: MakeWidgetInput;"));
        assert!(ts.contains("export function encodeMakeWidgetVars(v: MakeWidgetVars): Uint8Array"));
        assert!(ts.contains("export function decodeMakeWidgetVars(b: Uint8Array): MakeWidgetVars"));
    }

    #[test]
    fn encodes_nullable_with_option_tag_and_required_inline() {
        let ir = lower_schema_sdl(SDL).expect("schema lowers");
        let ops = list_schema_operations_sdl(SDL).expect("operations enumerable");

        let ts = emit_le_binary_typescript(&ir, &ops, DEFAULT_CODEC_IMPORT);

        // required String field -> direct writeString call
        assert!(ts.contains("w.writeString(v.label);"));
        // required Int field -> direct writeI32Le call
        assert!(ts.contains("w.writeI32Le(v.count);"));
        // nullable enum field -> writeOption wrapping enum encoder
        assert!(ts.contains("w.writeOption(v.color, (w, x) => _encColor(w, x));"));
        // required list of String! -> writeList without option wrapper
        assert!(ts.contains("w.writeList(v.tags, (w, x) => w.writeString(x));"));
    }

    #[test]
    fn quotes_property_keys_that_are_not_identifiers() {
        assert_eq!(property_key("ok"), "ok");
        assert_eq!(property_key("camelCase_2"), "camelCase_2");
        assert_eq!(property_key("with space"), "'with space'");
        assert_eq!(property_key(""), "''");
    }

    #[test]
    fn op_const_name_matches_wesley_operation_constant_convention() {
        assert_eq!(op_const_name("createRecord"), "OP_CREATE_RECORD");
        assert_eq!(op_const_name("updateRecord"), "OP_UPDATE_RECORD");
        assert_eq!(op_const_name("makeWidget"), "OP_MAKE_WIDGET");
        assert_eq!(op_const_name(""), "OP_UNNAMED");
    }

    #[test]
    fn emits_op_id_constant_for_each_operation() {
        let ir = lower_schema_sdl(SDL).expect("schema lowers");
        let ops = list_schema_operations_sdl(SDL).expect("operations enumerable");

        let ts = emit_le_binary_typescript(&ir, &ops, DEFAULT_CODEC_IMPORT);

        // Concrete op id pinned by wesley-core's stable_op_id tests.
        let expected_op_id =
            wesley_core::stable_op_id(wesley_core::OperationType::Mutation, "makeWidget");
        assert!(
            ts.contains(&format!(
                "export const OP_MAKE_WIDGET: number = {expected_op_id};"
            )),
            "expected OP_MAKE_WIDGET constant for op id {expected_op_id} in:\n{ts}",
        );
    }
}
