//! TypeScript LE binary codec emitter.
//!
//! Produces a TypeScript module for Wesley's deterministic little-endian
//! variable codec:
//!
//! - Enums encode their zero-based variant index (declaration order) as `u32` LE.
//! - Input objects encode their fields in declaration order with no separators.
//! - `Boolean` → 1 byte (`0x00` / `0x01`).
//! - `Int` → 4 bytes LE signed.
//! - `Float` → 4 bytes LE (canonicalized inside the Writer).
//! - `String` / `ID` → `u32` LE length + UTF-8 bytes.
//! - Nullable `T` → presence tag (`0x00` null / `0x01` present) + value if present.
//! - Non-null list `[T!]!` → `u32` LE element count + inline elements.
//!
//! Every emitted operation produces an `encode<Op>Vars(v) -> Uint8Array` /
//! `decode<Op>Vars(b) -> Result<<Op>Vars>` pair. Hosts or extension modules can
//! use those helpers as their transport boundary without Wesley owning the
//! runtime behavior behind the operation.

use std::fmt::Write;

use wesley_core::{OperationType, SchemaOperation, WesleyIR};
use wesley_emit_codec::{plan, CodecDef, CodecOp, FieldPlan, ScalarKind, StructKind};

/// Default import path the emitted module uses to reach the TypeScript
/// `Writer` / `Reader` / `CodecError` primitives. Suitable for files written
/// to `<root>/src/generated/<app>/<schema>.codec.generated.ts` when the
/// primitives live at `<root>/src/codec.ts`.
pub const DEFAULT_CODEC_IMPORT: &str = "../../codec.js";

const HEADER: &str = "\
/* @generated by wesley-emit-typescript le-binary. Do not edit. */
// SPDX-License-Identifier: Apache-2.0
//
// Wire layout is Wesley little-endian variable codec v0. Field order is SDL
// declaration order. Enums encode their zero-based variant index as u32 LE.
";

/// Emit a TypeScript LE binary codec module for the given Wesley IR.
///
/// `codec_import_path` is the module specifier the emitted file uses to
/// import `Writer`, `Reader`, and `CodecError`. Pass [`DEFAULT_CODEC_IMPORT`]
/// when the generated file is two directories below the codec primitives.
pub fn emit_le_binary_typescript(
    ir: &WesleyIR,
    operations: &[SchemaOperation],
    codec_import_path: &str,
) -> String {
    let program = TsProgram::from_ir(ir, operations, codec_import_path);

    print_program(&program)
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct TsProgram {
    imports: Vec<TsImport>,
    declarations: Vec<TsDeclaration>,
}

impl TsProgram {
    fn from_ir(ir: &WesleyIR, operations: &[SchemaOperation], codec_import_path: &str) -> Self {
        let mut declarations = Vec::new();

        for def in plan(ir, operations) {
            declarations.extend(declarations_for_codec_def(&def));
        }

        Self {
            imports: vec![TsImport {
                named: vec![
                    "Writer as RuntimeWriter",
                    "Reader as RuntimeReader",
                    "CodecError as RuntimeCodecError",
                ],
                from: codec_import_path.to_string(),
            }],
            declarations: std::iter::once(TsDeclaration::Raw(runtime_port_definitions()))
                .chain(declarations)
                .collect(),
        }
    }
}

fn declarations_for_codec_def(def: &CodecDef) -> Vec<TsDeclaration> {
    match def {
        CodecDef::Enum { name, variants } => enum_declarations(name, variants),
        CodecDef::Struct { name, kind, fields } => struct_declarations(name, *kind, fields),
        CodecDef::Operation {
            operation_type,
            field_name,
            fields,
        } => operation_vars_declarations(*operation_type, field_name, fields),
    }
}

fn runtime_port_definitions() -> String {
    "\
export type Result<T> =
    | { ok: true; value: T }
    | { ok: false; error: CodecError };

export interface CodecError {
    readonly message: string;
}

export interface Writer {
    writeU32Le(value: number): void;
    writeI32Le(value: number): void;
    writeF32Le(value: number): void;
    writeBool(value: boolean): void;
    writeString(value: string): void;
    writeOption<T>(value: T | null, write: (writer: Writer, value: T) => void): void;
    writeList<T>(value: T[], write: (writer: Writer, value: T) => void): void;
    finish(): Uint8Array;
}

export interface Reader {
    readU32Le(): number;
    readI32Le(): number;
    readF32Le(): number;
    readBool(): boolean;
    readString(): string;
    readOption<T>(read: (reader: Reader) => T): T | null;
    readList<T>(read: (reader: Reader) => T): T[];
    remaining(): number;
}

function ok<T>(value: T): Result<T> {
    return { ok: true, value };
}

function err<T>(error: CodecError): Result<T> {
    return { ok: false, error };
}

function codecErrorFromUnknown(error: unknown): CodecError {
    if (error instanceof RuntimeCodecError) {
        return error;
    }
    if (error instanceof Error) {
        return new RuntimeCodecError(error.message);
    }
    return new RuntimeCodecError(String(error));
}

function decodeWithBoundary<T>(b: Uint8Array, read: (reader: Reader) => T): Result<T> {
    try {
        const r = new RuntimeReader(b);
        const value = read(r);
        if (r.remaining() > 0) {
            return err(new RuntimeCodecError('trailing bytes after decode'));
        }
        return ok(value);
    } catch (error) {
        return err(codecErrorFromUnknown(error));
    }
}
"
    .to_string()
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct TsImport {
    named: Vec<&'static str>,
    from: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
enum TsDeclaration {
    Raw(String),
    Comment(String),
    TypeAlias(TsTypeAlias),
    Interface(TsInterface),
    Function(TsFunction),
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct TsTypeAlias {
    name: String,
    type_expr: TsTypeExpr,
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct TsInterface {
    name: String,
    properties: Vec<TsProperty>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct TsProperty {
    name: String,
    type_expr: TsTypeExpr,
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct TsFunction {
    name: String,
    params: Vec<TsParam>,
    return_type: TsTypeExpr,
    body: Vec<TsStatement>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct TsParam {
    name: String,
    type_expr: TsTypeExpr,
}

#[derive(Debug, Clone, PartialEq, Eq)]
enum TsStatement {
    Const {
        name: String,
        expr: TsExpr,
    },
    Return(TsExpr),
    ReturnVoid,
    ReturnObject(Vec<TsObjectProperty>),
    Expression(TsExpr),
    Switch {
        expr: TsExpr,
        cases: Vec<TsSwitchCase>,
        default: Vec<TsStatement>,
    },
    Throw(TsExpr),
    Comment(String),
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct TsSwitchCase {
    match_expr: TsExpr,
    body: Vec<TsStatement>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct TsObjectProperty {
    name: String,
    expr: TsExpr,
}

#[derive(Debug, Clone, PartialEq, Eq)]
enum TsExpr {
    Identifier(String),
    NumberLiteral(usize),
    StringLiteral(String),
    New {
        callee: String,
        args: Vec<TsExpr>,
    },
    Call {
        callee: Box<TsExpr>,
        args: Vec<TsExpr>,
    },
    PropertyAccess {
        target: Box<TsExpr>,
        property: String,
    },
    Arrow {
        params: Vec<String>,
        body: Box<TsExpr>,
    },
    Add {
        left: Box<TsExpr>,
        right: Box<TsExpr>,
    },
}

#[derive(Debug, Clone, PartialEq, Eq)]
enum TsTypeExpr {
    String,
    Number,
    Boolean,
    Void,
    Never,
    Uint8Array,
    Reference(String),
    StringLiteralUnion(Vec<String>),
    Null,
    Array(Box<TsTypeExpr>),
    Union(Vec<TsTypeExpr>),
    Generic { name: String, args: Vec<TsTypeExpr> },
}

impl TsTypeExpr {
    fn union(types: Vec<Self>) -> Self {
        let mut unique = Vec::new();

        for type_expr in types {
            if !unique.contains(&type_expr) {
                unique.push(type_expr);
            }
        }

        match unique.len() {
            0 => Self::Never,
            1 => unique.into_iter().next().expect("union has one item"),
            _ => Self::Union(unique),
        }
    }
}

fn enum_declarations(source_name: &str, values: &[String]) -> Vec<TsDeclaration> {
    let name = pascal_case(source_name);

    vec![
        TsDeclaration::Comment(format!("─── enum {source_name} ───")),
        TsDeclaration::TypeAlias(TsTypeAlias {
            name: name.clone(),
            type_expr: if values.is_empty() {
                TsTypeExpr::Never
            } else {
                TsTypeExpr::StringLiteralUnion(values.to_vec())
            },
        }),
        TsDeclaration::Function(encode_enum_function(&name, values)),
        TsDeclaration::Function(decode_enum_function(&name, values)),
        TsDeclaration::Function(encode_value_function(&name)),
        TsDeclaration::Function(decode_value_function(&name)),
    ]
}

fn encode_enum_function(name: &str, values: &[String]) -> TsFunction {
    let default = if values.is_empty() {
        vec![TsStatement::Comment("no variants".to_string())]
    } else {
        vec![TsStatement::Throw(invalid_codec_error(
            &format!("invalid {name} variant: "),
            ident("v"),
        ))]
    };

    TsFunction {
        name: format!("_enc{name}"),
        params: vec![
            TsParam {
                name: "w".to_string(),
                type_expr: TsTypeExpr::Reference("Writer".to_string()),
            },
            TsParam {
                name: "v".to_string(),
                type_expr: TsTypeExpr::Reference(name.to_string()),
            },
        ],
        return_type: TsTypeExpr::Void,
        body: vec![TsStatement::Switch {
            expr: ident("v"),
            cases: values
                .iter()
                .enumerate()
                .map(|(index, value)| TsSwitchCase {
                    match_expr: TsExpr::StringLiteral(value.clone()),
                    body: vec![
                        TsStatement::Expression(method_call(
                            ident("w"),
                            "writeU32Le",
                            vec![TsExpr::NumberLiteral(index)],
                        )),
                        TsStatement::ReturnVoid,
                    ],
                })
                .collect(),
            default,
        }],
    }
}

fn decode_enum_function(name: &str, values: &[String]) -> TsFunction {
    TsFunction {
        name: format!("_dec{name}"),
        params: vec![TsParam {
            name: "r".to_string(),
            type_expr: TsTypeExpr::Reference("Reader".to_string()),
        }],
        return_type: TsTypeExpr::Reference(name.to_string()),
        body: vec![
            TsStatement::Const {
                name: "d".to_string(),
                expr: method_call(ident("r"), "readU32Le", vec![]),
            },
            TsStatement::Switch {
                expr: ident("d"),
                cases: values
                    .iter()
                    .enumerate()
                    .map(|(index, value)| TsSwitchCase {
                        match_expr: TsExpr::NumberLiteral(index),
                        body: vec![TsStatement::Return(TsExpr::StringLiteral(value.clone()))],
                    })
                    .collect(),
                default: vec![TsStatement::Throw(invalid_codec_error(
                    &format!("invalid {name} discriminant: "),
                    ident("d"),
                ))],
            },
        ],
    }
}

fn encode_value_function(name: &str) -> TsFunction {
    TsFunction {
        name: format!("encode{name}"),
        params: vec![TsParam {
            name: "v".to_string(),
            type_expr: TsTypeExpr::Reference(name.to_string()),
        }],
        return_type: TsTypeExpr::Uint8Array,
        body: vec![
            TsStatement::Const {
                name: "w".to_string(),
                expr: TsExpr::New {
                    callee: "RuntimeWriter".to_string(),
                    args: Vec::new(),
                },
            },
            TsStatement::Expression(call_fn(
                &format!("_enc{name}"),
                vec![ident("w"), ident("v")],
            )),
            TsStatement::Return(method_call(ident("w"), "finish", vec![])),
        ],
    }
}

fn decode_value_function(name: &str) -> TsFunction {
    TsFunction {
        name: format!("decode{name}"),
        params: vec![TsParam {
            name: "b".to_string(),
            type_expr: TsTypeExpr::Uint8Array,
        }],
        return_type: result_type(TsTypeExpr::Reference(name.to_string())),
        body: vec![TsStatement::Return(call_fn(
            "decodeWithBoundary",
            vec![
                ident("b"),
                TsExpr::Arrow {
                    params: vec!["r".to_string()],
                    body: Box::new(call_fn(&format!("_dec{name}"), vec![ident("r")])),
                },
            ],
        ))],
    }
}

fn struct_declarations(
    source_name: &str,
    kind: StructKind,
    fields: &[FieldPlan],
) -> Vec<TsDeclaration> {
    let name = pascal_case(source_name);
    let label = match kind {
        StructKind::Input => "input",
        StructKind::Interface => "interface",
        StructKind::Object => "type",
    };

    vec![
        TsDeclaration::Comment(format!("─── {label} {source_name} ───")),
        TsDeclaration::Interface(TsInterface {
            name: name.clone(),
            properties: fields.iter().map(property_from_field_plan).collect(),
        }),
        TsDeclaration::Function(encode_struct_function(&name, fields)),
        TsDeclaration::Function(decode_struct_function(&name, fields)),
    ]
}

fn property_from_field_plan(field: &FieldPlan) -> TsProperty {
    TsProperty {
        name: field.name.clone(),
        type_expr: ts_type_for_op(&field.op),
    }
}

fn encode_struct_function(name: &str, fields: &[FieldPlan]) -> TsFunction {
    TsFunction {
        name: format!("_enc{name}"),
        params: vec![
            TsParam {
                name: "w".to_string(),
                type_expr: TsTypeExpr::Reference("Writer".to_string()),
            },
            TsParam {
                name: "v".to_string(),
                type_expr: TsTypeExpr::Reference(name.to_string()),
            },
        ],
        return_type: TsTypeExpr::Void,
        body: fields
            .iter()
            .map(|field| encode_field_statement(ident("v"), field))
            .collect(),
    }
}

fn decode_struct_function(name: &str, fields: &[FieldPlan]) -> TsFunction {
    TsFunction {
        name: format!("_dec{name}"),
        params: vec![TsParam {
            name: "r".to_string(),
            type_expr: TsTypeExpr::Reference("Reader".to_string()),
        }],
        return_type: TsTypeExpr::Reference(name.to_string()),
        body: vec![TsStatement::ReturnObject(
            fields
                .iter()
                .map(|field| TsObjectProperty {
                    name: field.name.clone(),
                    expr: decode_expr_for_op(&field.op),
                })
                .collect(),
        )],
    }
}

fn operation_vars_declarations(
    operation_type: OperationType,
    field_name: &str,
    fields: &[FieldPlan],
) -> Vec<TsDeclaration> {
    let pascal = pascal_case(field_name);
    let vars_name = format!("{pascal}Vars");
    let scope = match operation_type {
        OperationType::Query => "query",
        OperationType::Mutation => "mutation",
        OperationType::Subscription => "subscription",
    };

    vec![
        TsDeclaration::Comment(format!("─── {scope} {field_name} ───")),
        TsDeclaration::Interface(TsInterface {
            name: vars_name.clone(),
            properties: fields.iter().map(property_from_field_plan).collect(),
        }),
        TsDeclaration::Function(encode_struct_function(&vars_name, fields)),
        TsDeclaration::Function(decode_struct_function(&vars_name, fields)),
        TsDeclaration::Function(encode_operation_vars_function(&vars_name, fields)),
        TsDeclaration::Function(decode_operation_vars_function(&vars_name, fields)),
    ]
}

fn encode_operation_vars_function(vars_name: &str, _fields: &[FieldPlan]) -> TsFunction {
    let mut body = vec![TsStatement::Const {
        name: "w".to_string(),
        expr: TsExpr::New {
            callee: "RuntimeWriter".to_string(),
            args: Vec::new(),
        },
    }];
    body.push(TsStatement::Expression(call_fn(
        &format!("_enc{vars_name}"),
        vec![ident("w"), ident("v")],
    )));
    body.push(TsStatement::Return(method_call(
        ident("w"),
        "finish",
        vec![],
    )));

    TsFunction {
        name: format!("encode{vars_name}"),
        params: vec![TsParam {
            name: "v".to_string(),
            type_expr: TsTypeExpr::Reference(vars_name.to_string()),
        }],
        return_type: TsTypeExpr::Uint8Array,
        body,
    }
}

fn decode_operation_vars_function(vars_name: &str, _fields: &[FieldPlan]) -> TsFunction {
    TsFunction {
        name: format!("decode{vars_name}"),
        params: vec![TsParam {
            name: "b".to_string(),
            type_expr: TsTypeExpr::Uint8Array,
        }],
        return_type: result_type(TsTypeExpr::Reference(vars_name.to_string())),
        body: vec![TsStatement::Return(call_fn(
            "decodeWithBoundary",
            vec![
                ident("b"),
                TsExpr::Arrow {
                    params: vec!["r".to_string()],
                    body: Box::new(call_fn(&format!("_dec{vars_name}"), vec![ident("r")])),
                },
            ],
        ))],
    }
}

fn encode_field_statement(parent: TsExpr, field: &FieldPlan) -> TsStatement {
    let access = TsExpr::PropertyAccess {
        target: Box::new(parent),
        property: field.name.clone(),
    };

    TsStatement::Expression(encode_expr_for_op(access, &field.op))
}

fn encode_expr_for_op(value: TsExpr, op: &CodecOp) -> TsExpr {
    match op {
        CodecOp::Option(inner) => {
            let inner_expr = encode_expr_for_op(ident("x"), inner);
            method_call(
                ident("w"),
                "writeOption",
                vec![
                    value,
                    TsExpr::Arrow {
                        params: vec!["w".to_string(), "x".to_string()],
                        body: Box::new(inner_expr),
                    },
                ],
            )
        }
        CodecOp::List(inner) => {
            let element_lambda = TsExpr::Arrow {
                params: vec!["w".to_string(), "x".to_string()],
                body: Box::new(encode_expr_for_op(ident("x"), inner)),
            };
            method_call(ident("w"), "writeList", vec![value, element_lambda])
        }
        CodecOp::Scalar(ScalarKind::Bool) => method_call(ident("w"), "writeBool", vec![value]),
        CodecOp::Scalar(ScalarKind::Int) => method_call(ident("w"), "writeI32Le", vec![value]),
        CodecOp::Scalar(ScalarKind::Float) => method_call(ident("w"), "writeF32Le", vec![value]),
        CodecOp::Scalar(ScalarKind::String) => method_call(ident("w"), "writeString", vec![value]),
        CodecOp::Named(name) => call_fn(
            &format!("_enc{}", pascal_case(name)),
            vec![ident("w"), value],
        ),
    }
}

fn decode_expr_for_op(op: &CodecOp) -> TsExpr {
    match op {
        CodecOp::Option(inner) => method_call(
            ident("r"),
            "readOption",
            vec![TsExpr::Arrow {
                params: vec!["r".to_string()],
                body: Box::new(decode_expr_for_op(inner)),
            }],
        ),
        CodecOp::List(inner) => {
            let element_lambda = TsExpr::Arrow {
                params: vec!["r".to_string()],
                body: Box::new(decode_expr_for_op(inner)),
            };
            method_call(ident("r"), "readList", vec![element_lambda])
        }
        CodecOp::Scalar(ScalarKind::Bool) => method_call(ident("r"), "readBool", vec![]),
        CodecOp::Scalar(ScalarKind::Int) => method_call(ident("r"), "readI32Le", vec![]),
        CodecOp::Scalar(ScalarKind::Float) => method_call(ident("r"), "readF32Le", vec![]),
        CodecOp::Scalar(ScalarKind::String) => method_call(ident("r"), "readString", vec![]),
        CodecOp::Named(name) => call_fn(&format!("_dec{}", pascal_case(name)), vec![ident("r")]),
    }
}

fn ts_type_for_op(op: &CodecOp) -> TsTypeExpr {
    match op {
        CodecOp::Option(inner) => TsTypeExpr::union(vec![ts_type_for_op(inner), TsTypeExpr::Null]),
        CodecOp::List(inner) => TsTypeExpr::Array(Box::new(ts_type_for_op(inner))),
        CodecOp::Scalar(ScalarKind::Bool) => TsTypeExpr::Boolean,
        CodecOp::Scalar(ScalarKind::Int | ScalarKind::Float) => TsTypeExpr::Number,
        CodecOp::Scalar(ScalarKind::String) => TsTypeExpr::String,
        CodecOp::Named(name) => TsTypeExpr::Reference(pascal_case(name)),
    }
}

fn print_program(program: &TsProgram) -> String {
    let mut out = String::from(HEADER);
    out.push('\n');

    for import in &program.imports {
        print_import(&mut out, import);
    }

    for declaration in &program.declarations {
        out.push('\n');
        print_declaration(&mut out, declaration);
    }

    out
}

fn print_import(out: &mut String, import: &TsImport) {
    writeln!(
        out,
        "import {{ {} }} from {};",
        import.named.join(", "),
        quote_string(&import.from)
    )
    .expect("writing to string should not fail");
}

fn print_declaration(out: &mut String, declaration: &TsDeclaration) {
    match declaration {
        TsDeclaration::Raw(raw) => {
            out.push_str(raw);
            if !raw.ends_with('\n') {
                out.push('\n');
            }
        }
        TsDeclaration::Comment(comment) => {
            writeln!(out, "// {comment}").expect("writing to string should not fail");
        }
        TsDeclaration::TypeAlias(alias) => print_type_alias(out, alias),
        TsDeclaration::Interface(interface) => print_interface(out, interface),
        TsDeclaration::Function(function) => print_function(out, function),
    }
}

fn print_type_alias(out: &mut String, alias: &TsTypeAlias) {
    if let TsTypeExpr::StringLiteralUnion(values) = &alias.type_expr {
        writeln!(out, "export type {} =", alias.name).expect("writing to string should not fail");
        for (index, value) in values.iter().enumerate() {
            out.push_str("    | ");
            print_string_literal(out, value);
            if index + 1 == values.len() {
                out.push_str(";\n");
            } else {
                out.push('\n');
            }
        }
        return;
    }

    write!(out, "export type {} = ", alias.name).expect("writing to string should not fail");
    print_type_expr(out, &alias.type_expr, false);
    out.push_str(";\n");
}

fn print_interface(out: &mut String, interface: &TsInterface) {
    writeln!(out, "export interface {} {{", interface.name)
        .expect("writing to string should not fail");
    for property in &interface.properties {
        out.push_str("    ");
        out.push_str(&property_key(&property.name));
        out.push_str(": ");
        print_type_expr(out, &property.type_expr, false);
        out.push_str(";\n");
    }
    out.push_str("}\n");
}

fn print_function(out: &mut String, function: &TsFunction) {
    write!(out, "export function {}(", function.name).expect("writing to string should not fail");
    for (index, param) in function.params.iter().enumerate() {
        if index > 0 {
            out.push_str(", ");
        }
        out.push_str(&param.name);
        out.push_str(": ");
        print_type_expr(out, &param.type_expr, false);
    }
    out.push_str("): ");
    print_type_expr(out, &function.return_type, false);
    out.push_str(" {\n");
    for statement in &function.body {
        print_statement(out, statement, 1);
    }
    out.push_str("}\n");
}

fn print_statement(out: &mut String, statement: &TsStatement, indent_level: usize) {
    match statement {
        TsStatement::Const { name, expr } => {
            write_indent(out, indent_level);
            write!(out, "const {name} = ").expect("writing to string should not fail");
            print_expr(out, expr);
            out.push_str(";\n");
        }
        TsStatement::Return(expr) => {
            write_indent(out, indent_level);
            out.push_str("return ");
            print_expr(out, expr);
            out.push_str(";\n");
        }
        TsStatement::ReturnVoid => {
            write_indent(out, indent_level);
            out.push_str("return;\n");
        }
        TsStatement::ReturnObject(properties) => {
            write_indent(out, indent_level);
            out.push_str("return {\n");
            for property in properties {
                write_indent(out, indent_level + 1);
                out.push_str(&property_key(&property.name));
                out.push_str(": ");
                print_expr(out, &property.expr);
                out.push_str(",\n");
            }
            write_indent(out, indent_level);
            out.push_str("};\n");
        }
        TsStatement::Expression(expr) => {
            write_indent(out, indent_level);
            print_expr(out, expr);
            out.push_str(";\n");
        }
        TsStatement::Switch {
            expr,
            cases,
            default,
        } => print_switch(out, expr, cases, default, indent_level),
        TsStatement::Throw(expr) => {
            write_indent(out, indent_level);
            out.push_str("throw ");
            print_expr(out, expr);
            out.push_str(";\n");
        }
        TsStatement::Comment(comment) => {
            write_indent(out, indent_level);
            writeln!(out, "// {comment}").expect("writing to string should not fail");
        }
    }
}

fn print_switch(
    out: &mut String,
    expr: &TsExpr,
    cases: &[TsSwitchCase],
    default: &[TsStatement],
    indent_level: usize,
) {
    write_indent(out, indent_level);
    out.push_str("switch (");
    print_expr(out, expr);
    out.push_str(") {\n");

    for case in cases {
        let label = format!("case {}:", render_expr(&case.match_expr));
        print_switch_arm(out, &label, &case.body, indent_level + 1);
    }

    if cases.is_empty()
        && default.len() == 1
        && matches!(default.first(), Some(TsStatement::Comment(_)))
    {
        print_statement(
            out,
            default.first().expect("default has one statement"),
            indent_level + 1,
        );
    } else if !default.is_empty() {
        print_switch_arm(out, "default:", default, indent_level + 1);
    }

    write_indent(out, indent_level);
    out.push_str("}\n");
}

fn print_switch_arm(out: &mut String, label: &str, body: &[TsStatement], indent_level: usize) {
    let inline = body
        .iter()
        .map(inline_statement)
        .collect::<Option<Vec<_>>>();
    if let Some(inline) = inline {
        write_indent(out, indent_level);
        writeln!(out, "{label} {}", inline.join(" ")).expect("writing to string should not fail");
        return;
    }

    write_indent(out, indent_level);
    writeln!(out, "{label}").expect("writing to string should not fail");
    for statement in body {
        print_statement(out, statement, indent_level + 1);
    }
}

fn inline_statement(statement: &TsStatement) -> Option<String> {
    match statement {
        TsStatement::Expression(expr) => Some(format!("{};", render_expr(expr))),
        TsStatement::Return(expr) => Some(format!("return {};", render_expr(expr))),
        TsStatement::ReturnVoid => Some("return;".to_string()),
        TsStatement::Throw(expr) => Some(format!("throw {};", render_expr(expr))),
        TsStatement::Const { .. }
        | TsStatement::ReturnObject(_)
        | TsStatement::Switch { .. }
        | TsStatement::Comment(_) => None,
    }
}

fn print_type_expr(out: &mut String, type_expr: &TsTypeExpr, parenthesize_union: bool) {
    match type_expr {
        TsTypeExpr::String => out.push_str("string"),
        TsTypeExpr::Number => out.push_str("number"),
        TsTypeExpr::Boolean => out.push_str("boolean"),
        TsTypeExpr::Void => out.push_str("void"),
        TsTypeExpr::Never => out.push_str("never"),
        TsTypeExpr::Uint8Array => out.push_str("Uint8Array"),
        TsTypeExpr::Reference(name) => out.push_str(name),
        TsTypeExpr::StringLiteralUnion(values) => {
            if parenthesize_union {
                out.push('(');
            }
            for (index, value) in values.iter().enumerate() {
                if index > 0 {
                    out.push_str(" | ");
                }
                print_string_literal(out, value);
            }
            if parenthesize_union {
                out.push(')');
            }
        }
        TsTypeExpr::Null => out.push_str("null"),
        TsTypeExpr::Array(item) => {
            print_type_expr(out, item, true);
            out.push_str("[]");
        }
        TsTypeExpr::Union(types) => {
            if parenthesize_union {
                out.push('(');
            }
            for (index, nested) in types.iter().enumerate() {
                if index > 0 {
                    out.push_str(" | ");
                }
                print_type_expr(out, nested, false);
            }
            if parenthesize_union {
                out.push(')');
            }
        }
        TsTypeExpr::Generic { name, args } => {
            out.push_str(name);
            out.push('<');
            for (index, arg) in args.iter().enumerate() {
                if index > 0 {
                    out.push_str(", ");
                }
                print_type_expr(out, arg, false);
            }
            out.push('>');
        }
    }
}

fn render_expr(expr: &TsExpr) -> String {
    let mut out = String::new();
    print_expr(&mut out, expr);
    out
}

fn print_expr(out: &mut String, expr: &TsExpr) {
    match expr {
        TsExpr::Identifier(name) => out.push_str(name),
        TsExpr::NumberLiteral(value) => {
            write!(out, "{value}").expect("writing to string should not fail");
        }
        TsExpr::StringLiteral(value) => print_string_literal(out, value),
        TsExpr::New { callee, args } => {
            out.push_str("new ");
            out.push_str(callee);
            print_call_args(out, args);
        }
        TsExpr::Call { callee, args } => {
            print_expr(out, callee);
            print_call_args(out, args);
        }
        TsExpr::PropertyAccess { target, property } => {
            print_expr(out, target);
            if is_safe_identifier(property) {
                out.push('.');
                out.push_str(property);
            } else {
                out.push('[');
                print_string_literal(out, property);
                out.push(']');
            }
        }
        TsExpr::Arrow { params, body } => {
            out.push('(');
            out.push_str(&params.join(", "));
            out.push_str(") => ");
            print_expr(out, body);
        }
        TsExpr::Add { left, right } => {
            print_expr(out, left);
            out.push_str(" + ");
            print_expr(out, right);
        }
    }
}

fn print_call_args(out: &mut String, args: &[TsExpr]) {
    out.push('(');
    for (index, arg) in args.iter().enumerate() {
        if index > 0 {
            out.push_str(", ");
        }
        print_expr(out, arg);
    }
    out.push(')');
}

fn write_indent(out: &mut String, indent_level: usize) {
    for _ in 0..indent_level {
        out.push_str("    ");
    }
}

fn ident(name: &str) -> TsExpr {
    TsExpr::Identifier(name.to_string())
}

fn call_fn(name: &str, args: Vec<TsExpr>) -> TsExpr {
    TsExpr::Call {
        callee: Box::new(ident(name)),
        args,
    }
}

fn method_call(target: TsExpr, method: &str, args: Vec<TsExpr>) -> TsExpr {
    TsExpr::Call {
        callee: Box::new(TsExpr::PropertyAccess {
            target: Box::new(target),
            property: method.to_string(),
        }),
        args,
    }
}

fn invalid_codec_error(message_prefix: &str, value: TsExpr) -> TsExpr {
    TsExpr::New {
        callee: "RuntimeCodecError".to_string(),
        args: vec![TsExpr::Add {
            left: Box::new(TsExpr::StringLiteral(message_prefix.to_string())),
            right: Box::new(call_fn("String", vec![value])),
        }],
    }
}

fn result_type(value: TsTypeExpr) -> TsTypeExpr {
    TsTypeExpr::Generic {
        name: "Result".to_string(),
        args: vec![value],
    }
}

fn pascal_case(name: &str) -> String {
    let mut out = String::new();
    let mut next_upper = true;
    for ch in name.chars() {
        if ch.is_alphanumeric() {
            if next_upper {
                out.push(ch.to_ascii_uppercase());
                next_upper = false;
            } else {
                out.push(ch);
            }
        } else {
            next_upper = true;
        }
    }
    if out.is_empty() {
        "Op".to_string()
    } else {
        out
    }
}

fn property_key(name: &str) -> String {
    if is_safe_identifier(name) {
        name.to_string()
    } else {
        let mut quoted = String::from("'");
        for ch in name.chars() {
            match ch {
                '\\' => quoted.push_str("\\\\"),
                '\'' => quoted.push_str("\\'"),
                _ => quoted.push(ch),
            }
        }
        quoted.push('\'');
        quoted
    }
}

fn is_safe_identifier(name: &str) -> bool {
    let mut chars = name.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    if !(first.is_ascii_alphabetic() || first == '_' || first == '$') {
        return false;
    }
    for ch in chars {
        if !(ch.is_ascii_alphanumeric() || ch == '_' || ch == '$') {
            return false;
        }
    }
    true
}

fn print_string_literal(out: &mut String, value: &str) {
    out.push('\'');
    for ch in value.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '\'' => out.push_str("\\'"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            _ => out.push(ch),
        }
    }
    out.push('\'');
}

fn quote_string(value: &str) -> String {
    let mut out = String::new();
    print_string_literal(&mut out, value);
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use wesley_core::{
        list_schema_operations_sdl, lower_schema_sdl, TypeDefinition, TypeKind, TypeReference,
    };

    const SDL: &str = "
        enum Color { RED GREEN BLUE }

        input MakeWidgetInput {
            label: String!
            count: Int!
            color: Color
            tags: [String!]!
        }

        type Widget { id: ID! label: String! }

        type Query {
            widget(id: ID!): Widget!
        }

        type Mutation {
            makeWidget(input: MakeWidgetInput!): Widget!
        }
    ";

    fn assert_no_runtime_operation_markers(ts: &str) {
        let forbidden_constant_declaration = ["export const ", "OP", "_"].concat();
        let forbidden_phrase = ["op", "id"].join(" ");

        assert!(
            !ts.contains(&forbidden_constant_declaration),
            "unexpected runtime operation constant declaration in:\n{ts}"
        );
        assert!(
            !ts.contains(&forbidden_phrase),
            "unexpected runtime operation identifier claim in:\n{ts}"
        );
    }

    #[test]
    #[should_panic(expected = "unexpected runtime operation constant declaration")]
    fn runtime_marker_assertion_rejects_any_op_prefixed_constant() {
        let runtime_marker = ["export const ", "OP", "_DELETE_WIDGET = 42;"].concat();

        assert_no_runtime_operation_markers(&runtime_marker);
    }

    #[test]
    fn runtime_marker_assertion_allows_schema_values_containing_op_sequence() {
        let enum_value = ["ST", "OP", "_NOW"].concat();
        let sdl = format!(
            "
            enum WorkflowState {{ {enum_value} }}
            input TransitionInput {{
                state: WorkflowState!
            }}
        "
        );
        let ir = lower_schema_sdl(&sdl).expect("schema lowers");
        let ts = emit_le_binary_typescript(&ir, &[], DEFAULT_CODEC_IMPORT);

        assert!(ts.contains(&format!("'{enum_value}'")));
        assert_no_runtime_operation_markers(&ts);
    }

    #[test]
    fn emits_typescript_codec_for_minimal_schema() {
        let ir = lower_schema_sdl(SDL).expect("schema lowers");
        let ops = list_schema_operations_sdl(SDL).expect("operations enumerable");

        let ts = emit_le_binary_typescript(&ir, &ops, DEFAULT_CODEC_IMPORT);

        assert!(ts.contains(
            "import { Writer as RuntimeWriter, Reader as RuntimeReader, CodecError as RuntimeCodecError } from '../../codec.js';"
        ));
        assert!(ts.contains("export type Result<T> ="));
        assert!(ts.contains("export interface Writer {"));
        assert!(ts.contains("export interface Reader {"));
        assert!(ts.contains("function decodeWithBoundary<T>("));
        assert!(ts.contains("if (r.remaining() > 0) {"));
        assert!(ts.contains("export type Color =\n    | 'RED'\n    | 'GREEN'\n    | 'BLUE';"));
        assert!(ts.contains("case 'RED': w.writeU32Le(0); return;"));
        assert!(ts.contains("case 'BLUE': w.writeU32Le(2); return;"));
        assert!(ts.contains("export interface MakeWidgetInput"));
        assert!(ts.contains("label: string;"));
        assert!(ts.contains("color: Color | null;"));
        assert!(ts.contains("tags: string[];"));
        assert!(ts.contains("export interface MakeWidgetVars"));
        assert!(ts.contains("input: MakeWidgetInput;"));
        assert!(ts.contains("export function encodeMakeWidgetVars(v: MakeWidgetVars): Uint8Array"));
        assert!(ts.contains(
            "export function decodeMakeWidgetVars(b: Uint8Array): Result<MakeWidgetVars>"
        ));
    }

    #[test]
    fn emits_codec_for_output_object_types_but_not_operation_roots() {
        let ir = lower_schema_sdl(SDL).expect("schema lowers");
        let ops = list_schema_operations_sdl(SDL).expect("operations enumerable");

        let ts = emit_le_binary_typescript(&ir, &ops, DEFAULT_CODEC_IMPORT);

        // An output `type Widget` now gets a codec...
        assert!(ts.contains("// ─── type Widget ───"), "{ts}");
        assert!(ts.contains("export function _encWidget(w: Writer, v: Widget): void"));
        assert!(ts.contains("export function _decWidget(r: Reader): Widget"));
        // ...but the Mutation/Query operation roots do not.
        assert!(!ts.contains("_encMutation"), "{ts}");
        assert!(!ts.contains("_encQuery"), "{ts}");
    }

    #[test]
    fn emits_le_binary_typescript_from_golden_fixture() {
        let sdl = include_str!("../../../test/fixtures/typescript-emitter/le-binary-codec.graphql");
        let expected =
            include_str!("../../../test/fixtures/typescript-emitter/le-binary-codec.generated.ts");
        let ir = lower_schema_sdl(sdl).expect("golden schema lowers");
        let ops = list_schema_operations_sdl(sdl).expect("golden operations enumerable");

        let actual = emit_le_binary_typescript(&ir, &ops, DEFAULT_CODEC_IMPORT);

        assert_eq!(actual, expected);
        assert_no_runtime_operation_markers(&actual);
    }

    #[test]
    fn encodes_nullable_with_option_tag_and_required_inline() {
        let ir = lower_schema_sdl(SDL).expect("schema lowers");
        let ops = list_schema_operations_sdl(SDL).expect("operations enumerable");

        let ts = emit_le_binary_typescript(&ir, &ops, DEFAULT_CODEC_IMPORT);

        // required String field -> direct writeString call
        assert!(ts.contains("w.writeString(v.label);"));
        // required Int field -> direct writeI32Le call
        assert!(ts.contains("w.writeI32Le(v.count);"));
        // nullable enum field -> writeOption wrapping enum encoder
        assert!(ts.contains("w.writeOption(v.color, (w, x) => _encColor(w, x));"));
        // required list of String! -> writeList without option wrapper
        assert!(ts.contains("w.writeList(v.tags, (w, x) => w.writeString(x));"));
    }

    #[test]
    fn quotes_property_keys_that_are_not_identifiers() {
        assert_eq!(property_key("ok"), "ok");
        assert_eq!(property_key("camelCase_2"), "camelCase_2");
        assert_eq!(property_key("with space"), "'with space'");
        assert_eq!(property_key(""), "''");
    }

    #[test]
    fn bracket_accesses_non_identifier_input_object_fields_from_ast() {
        let ir = WesleyIR {
            version: "1.0.0".to_string(),
            metadata: None,
            types: vec![TypeDefinition {
                name: "OddInput".to_string(),
                kind: TypeKind::InputObject,
                description: None,
                directives: Default::default(),
                implements: Vec::new(),
                fields: vec![wesley_core::Field {
                    name: "with space".to_string(),
                    description: None,
                    r#type: TypeReference {
                        base: "String".to_string(),
                        nullable: false,
                        is_list: false,
                        list_item_nullable: None,
                        list_wrappers: Vec::new(),
                        leaf_nullable: None,
                    },
                    arguments: Vec::new(),
                    default_value: None,
                    directives: Default::default(),
                }],
                enum_values: Vec::new(),
                union_members: Vec::new(),
            }],
        };

        let ts = emit_le_binary_typescript(&ir, &[], DEFAULT_CODEC_IMPORT);

        assert!(ts.contains("'with space': string;"));
        assert!(ts.contains("w.writeString(v['with space']);"));
        assert!(ts.contains("'with space': r.readString(),"));
        assert!(
            !ts.contains("v.'with space'"),
            "property access must be syntax-aware:\n{ts}"
        );
    }

    #[test]
    fn does_not_emit_runtime_operation_constants() {
        let ir = lower_schema_sdl(SDL).expect("schema lowers");
        let ops = list_schema_operations_sdl(SDL).expect("operations enumerable");

        let ts = emit_le_binary_typescript(&ir, &ops, DEFAULT_CODEC_IMPORT);
        assert_no_runtime_operation_markers(&ts);
    }
}
