#!/usr/bin/env bats

load 'vendor/bats-plugins/bats-support/load'
load 'vendor/bats-plugins/bats-assert/load'

# The documentation replay must fail closed. Each test gives it one broken page
# and requires a refusal that names the problem. A replay that passes any of
# these pages would be reporting success without having checked something.
#
# Size: medium. Oracle: specified, from the rules at the top of
# scripts/run-doc-examples.mjs.

setup_file() {
  cargo build --quiet --bin wesley
  export WESLEY_BIN="${CARGO_TARGET_DIR:-$PWD/target}/debug/wesley"
  [ -x "$WESLEY_BIN" ]
}

setup() {
  PAGE="$BATS_TEST_TMPDIR/page.md"
  RUNNER="$PWD/scripts/run-doc-examples.mjs"
}

# A page the replay accepts. Every test below breaks exactly one thing in it.
good_page() {
  cat <<'MD'
# Example

<!-- file: s.graphql -->

```graphql
type Query {
  answer: Int
}
```

```bash
wesley schema hash --schema s.graphql
```

```text
HASH
```

```bash
wesley schema operations --schema s.graphql
```

<!-- stdout: json-subset -->

```json
[{ "fieldName": "answer" }]
```

```bash
wesley emit rust --schema s.graphql --out s.rs
```

<!-- shows: s.rs -->

```rust
// @generated by Wesley. Do not edit.
```
MD
}

# Writes the good page with the real hash filled in, then applies a sed script.
write_page() {
  good_page > "$PAGE"
  printf 'type Query {\n  answer: Int\n}\n' > "$BATS_TEST_TMPDIR/s.graphql"
  hash="$("$WESLEY_BIN" schema hash --schema "$BATS_TEST_TMPDIR/s.graphql")"
  sed -i.bak "s/^HASH$/$hash/" "$PAGE"
  if [ -n "${1:-}" ]; then sed -i.bak -E "$1" "$PAGE"; fi
}

replay() {
  run node "$RUNNER" --wesley "$WESLEY_BIN" "$PAGE"
}

@test "the unbroken page is accepted, with a witness count" {
  write_page
  replay
  assert_success
  assert_output --regexp 'ran 3, compared 3$'
}

@test "a misspelled annotation is refused instead of dropping its check" {
  write_page 's/<!-- shows: s.rs -->/<!-- show: s.rs -->/'
  replay
  assert_failure
  assert_output --partial 'unknown annotation `show`'
}

@test "an annotation with an invalid value is refused" {
  write_page 's/<!-- stdout: json-subset -->/<!-- stdout: json -->/'
  replay
  assert_failure
  assert_output --partial 'is not a valid value'
}

@test "an annotation separated from its block by prose is refused" {
  write_page 's/^<!-- shows: s.rs -->$/<!-- shows: s.rs -->\n\nSome prose in between./'
  replay
  assert_failure
  assert_output --partial 'annotation is not directly before a fenced block'
}

@test "a fence left open is refused" {
  write_page
  # Drop the final closing fence.
  sed -i.bak '$ d' "$PAGE"
  replay
  assert_failure
  assert_output --partial 'is never closed'
}

@test "an indented wesley line is refused, because it would not run" {
  write_page 's/^wesley schema hash/ wesley schema hash/'
  replay
  assert_failure
  assert_output --partial 'is indented, so it would not be run or checked'
}

@test "an output block with no command before it is refused" {
  write_page 's/^wesley schema hash --schema s.graphql$/echo not-wesley/'
  replay
  assert_failure
  assert_output --partial 'no command ran directly before it'
}

@test "output that differs from the page is refused, showing both" {
  write_page 's/^[0-9a-f]{64}$/0000000000000000000000000000000000000000000000000000000000000000/'
  replay
  assert_failure
  assert_output --partial 'differs from the page'
  assert_output --partial '--- actual'
}

@test "a JSON listing that shows a wrong value is refused, with its path" {
  write_page 's/"fieldName": "answer"/"fieldName": "question"/'
  replay
  assert_failure
  assert_output --partial '$[0].fieldName'
}

@test "a JSON listing that shows no values is refused, because it compares nothing" {
  write_page 's/^\[\{ "fieldName": "answer" \}\]$/[{}]/'
  replay
  assert_failure
  assert_output --partial 'shows no values'
}

@test "an emptied file excerpt is refused" {
  write_page 's#^// @generated by Wesley\. Do not edit\.$##'
  replay
  assert_failure
  assert_output --partial 'is empty'
}

@test "a file excerpt that is not in the written file is refused" {
  write_page 's#^// @generated by Wesley\. Do not edit\.$#// written by hand#'
  replay
  assert_failure
  assert_output --partial 'is not an excerpt of `s.rs`'
}

@test "a file annotation that escapes the scratch directory is refused and writes nothing" {
  write_page 's#<!-- file: s.graphql -->#<!-- file: ../escaped.graphql -->#'
  replay
  assert_failure
  assert_output --partial 'is outside the scratch directory'
  [ ! -e "$BATS_TEST_TMPDIR/../escaped.graphql" ]
}

@test "a command the CLI does not list is refused even in a block that is not run" {
  write_page
  printf '\n<!-- norun: example -->\n\n```bash\nwesley schema compare --schema s.graphql\n```\n' >> "$PAGE"
  replay
  assert_failure
  assert_output --partial 'is not a command `wesley --help` lists'
}

@test "a family invocation the CLI answers is accepted in a block that is not run" {
  write_page
  printf '\n<!-- norun: prints help -->\n\n```bash\nwesley schema\n```\n' >> "$PAGE"
  replay
  assert_success
}

@test "output the page does not show is refused" {
  write_page
  # Remove the hash's text block, leaving the command with unshown output.
  perl -0pi -e 's/```text\n[0-9a-f]{64}\n```\n\n//' "$PAGE"
  replay
  assert_failure
  assert_output --partial 'printed output the page does not show'
}

@test "a command that does not finish is refused after a bounded wait" {
  write_page
  stub="$BATS_TEST_TMPDIR/hanging-wesley"
  printf '#!/bin/bash\nif [ "$1" = "--help" ]; then exec "%s" --help; fi\nsleep 120\n' "$WESLEY_BIN" > "$stub"
  chmod +x "$stub"
  run node "$RUNNER" --wesley "$stub" "$PAGE"
  assert_failure
  assert_output --partial 'did not finish'
}

@test "a page with nothing to run is refused, whatever other pages contain" {
  write_page
  printf '# Empty\n\nNo commands here.\n' > "$BATS_TEST_TMPDIR/empty.md"
  run node "$RUNNER" --wesley "$WESLEY_BIN" "$PAGE" "$BATS_TEST_TMPDIR/empty.md"
  assert_failure
  assert_output --partial 'empty.md: no wesley commands were found to run'
}
