import { createHash } from 'node:crypto';

const REQUIRED_TOP_LEVEL_FIELDS = [
  'observerName',
  'kind',
  'operationName',
  'aperture',
  'basis',
  'state',
  'update',
  'emit',
  'budgets',
  'rights'
];

export function normalizeObserverSpec(spec, source = {}) {
  if (spec == null || typeof spec !== 'object' || Array.isArray(spec)) {
    throw new Error('Observer spec must be a plain object.');
  }

  for (const field of REQUIRED_TOP_LEVEL_FIELDS) {
    if (!(field in spec)) {
      throw new Error(`Observer spec is missing required field: ${field}`);
    }
  }

  const normalized = deepSort({
    observerName: requireString(spec.observerName, 'observerName'),
    kind: requireString(spec.kind, 'kind'),
    operationName: requireString(spec.operationName, 'operationName'),
    aperture: requireObject(spec.aperture, 'aperture'),
    basis: requireObject(spec.basis, 'basis'),
    state: requireObject(spec.state, 'state'),
    update: requireObject(spec.update, 'update'),
    emit: requireObject(spec.emit, 'emit'),
    budgets: requireObject(spec.budgets, 'budgets'),
    rights: requireObject(spec.rights, 'rights')
  });

  const canonicalJson = JSON.stringify(normalized);
  const specHash = createHash('sha256').update(canonicalJson).digest('hex');

  return {
    planId: `observer-plan:${normalized.observerName}:${specHash.slice(0, 16)}`,
    specHash,
    observerName: normalized.observerName,
    kind: normalized.kind,
    operationName: normalized.operationName,
    aperture: normalized.aperture,
    basis: normalized.basis,
    state: normalized.state,
    update: normalized.update,
    emit: normalized.emit,
    budgets: normalized.budgets,
    rights: normalized.rights,
    source: deepSort({
      specPath: source.specPath ?? '<unknown>',
      exportName: source.exportName ?? 'default'
    })
  };
}

export function generateObserverPlanTypeScript(plan) {
  const exportConstName = toCamelCase(`${plan.observerName}ObserverPlan`);
  const schemaField = quoteObject(plan);

  return [
    '// Generated by Wesley observer-plan. Do not edit by hand.',
    '',
    'export interface ObserverPlan {',
    '  readonly planId: string;',
    '  readonly specHash: string;',
    '  readonly observerName: string;',
    '  readonly kind: string;',
    '  readonly operationName: string;',
    '  readonly aperture: Record<string, string | number | readonly string[]>;',
    '  readonly basis: Record<string, string | readonly string[]>;',
    '  readonly state: Record<string, string>;',
    '  readonly update: Record<string, string>;',
    '  readonly emit: Record<string, string>;',
    '  readonly budgets: Record<string, string | number>;',
    '  readonly rights: Record<string, string>;',
    '  readonly source: Record<string, string>;',
    '}',
    '',
    `export const ${exportConstName} = ${schemaField} as const satisfies ObserverPlan;`,
    '',
    `export type ${toPascalCase(exportConstName)} = typeof ${exportConstName};`,
    ''
  ].join('\n');
}

function requireString(value, fieldName) {
  if (typeof value !== 'string' || value.trim().length === 0) {
    throw new Error(`Observer spec field ${fieldName} must be a non-empty string.`);
  }
  return value;
}

function requireObject(value, fieldName) {
  if (value == null || typeof value !== 'object' || Array.isArray(value)) {
    throw new Error(`Observer spec field ${fieldName} must be a plain object.`);
  }
  return value;
}

function deepSort(value) {
  if (Array.isArray(value)) {
    return value.map((entry) => deepSort(entry));
  }
  if (value != null && typeof value === 'object') {
    return Object.keys(value).sort().reduce((result, key) => {
      result[key] = deepSort(value[key]);
      return result;
    }, {});
  }
  return value;
}

function quoteObject(value, indent = 0) {
  const prefix = '  '.repeat(indent);
  if (Array.isArray(value)) {
    if (value.length === 0) {
      return '[]';
    }
    return `[\n${value.map((entry) => `${prefix}  ${quoteObject(entry, indent + 1)}`).join(',\n')}\n${prefix}]`;
  }
  if (value != null && typeof value === 'object') {
    const entries = Object.entries(value);
    if (entries.length === 0) {
      return '{}';
    }
    return `{\n${entries.map(([key, entry]) => `${prefix}  ${JSON.stringify(key)}: ${quoteObject(entry, indent + 1)}`).join(',\n')}\n${prefix}}`;
  }
  return JSON.stringify(value);
}

function toCamelCase(value) {
  const words = value
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .replace(/[^a-zA-Z0-9]+/g, ' ')
    .trim()
    .split(/\s+/)
    .filter(Boolean);
  if (words.length === 0) {
    return 'observerPlan';
  }
  return words[0].toLowerCase() + words.slice(1).map(capitalize).join('');
}

function toPascalCase(value) {
  return value
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .replace(/[^a-zA-Z0-9]+/g, ' ')
    .trim()
    .split(/\s+/)
    .filter(Boolean)
    .map(capitalize)
    .join('');
}

function capitalize(value) {
  return value.length === 0
    ? value
    : `${value[0].toUpperCase()}${value.slice(1)}`;
}
