[package]
name = "wesley-emit-typescript"
version = "0.0.4"
edition = "2021"
description = "AST-based TypeScript emitter for Wesley IR"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/flyingrobots/wesley"
homepage = "https://github.com/flyingrobots/wesley#readme"
documentation = "https://docs.rs/wesley-emit-typescript"
keywords = ["graphql", "compiler", "typescript", "codegen"]
categories = ["compilers"]

[dependencies]
serde_json = "1.0"
wesley-core = { path = "../wesley-core", version = "0.0.4" }

[dev-dependencies]
pretty_assertions = "1.4"
