site_name: Wesley Docs
site_url: https://flyingrobots.github.io/wesley/
repo_name: flyingrobots/wesley
repo_url: https://github.com/flyingrobots/wesley
edit_uri: ""
docs_dir: docs/site
nav:
  - Home: index.md
  - Quick Start: quick-start.md
  - Roadmap: roadmap.md
  - Scripts: scripts.md
  - Reference:
      - Lifecycle: ../architecture/lifecycle.md
      - README: ../README.md
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - fenced_code
  - tables
  - codehilite
