/**
 * TTD Protocol Compiler Orchestrator
 *
 * Main entry point for compiling TTD schemas to various outputs.
 *
 * Architecture:
 * - Parses GraphQL SDL with TTD directives
 * - Extracts TTD schema (channels, ops, rules, invariants, etc.)
 * - Validates the schema
 * - Generates outputs based on targets:
 *   - manifest: JSON files (schema.json, manifest.json, contracts.json)
 *   - typescript: TS types, Zod validators, registry
 *   - rust: NOT generated here - external tools consume the manifest
 */

import { extractTtdSchema } from '../extractor.mjs';
import { validateTtdSchema } from '../validation.mjs';
import { hashSchema } from '../hasher.mjs';
import { generateSchemaJson, generateContractsJson, generateManifest } from '../manifest.mjs';
import { generateTsTypes } from './ts-types.mjs';
import { generateTsZod } from './ts-zod.mjs';
import { generateTsRegistry } from './ts-registry.mjs';
import { systemClock } from '../../ports/clock.mjs';

/**
 * Compile TTD protocol from GraphQL SDL
 *
 * @param {Object} options
 * @param {string} options.sdl - GraphQL SDL with TTD directives
 * @param {string[]} options.targets - Output targets: 'manifest', 'typescript' (default: all)
 * @param {Object} options.deps - Dependencies for DI
 * @param {import('../../ports/clock.mjs').ClockPort} options.deps.clock - Clock port
 * @returns {Promise<Object>} Compilation result with files array
 */
export async function compileTtdProtocol({ sdl, targets = ['manifest', 'typescript'], deps = {} }) {
  const clock = deps.clock ?? systemClock;
  // Extract TTD schema from SDL
  const schema = extractTtdSchema(sdl, { clock });

  // Compute schema hash
  schema.schemaHash = hashSchema(sdl);

  // Validate schema
  const validation = validateTtdSchema(schema);

  if (!validation.valid) {
    const errorMessages = validation.errors.map(e => `${e.code}: ${e.message}`).join('\n');
    throw new Error(`Schema validation failed:\n${errorMessages}`);
  }

  const files = [];

  // Generate manifest files
  if (targets.includes('manifest')) {
    const schemaJson = generateSchemaJson(schema, { clock });
    const contractsJson = generateContractsJson(schema);
    const manifest = generateManifest(schema);

    files.push({
      path: 'manifest/schema.json',
      content: JSON.stringify(schemaJson, null, 2),
    });

    files.push({
      path: 'manifest/contracts.json',
      content: JSON.stringify(contractsJson, null, 2),
    });

    files.push({
      path: 'manifest/manifest.json',
      content: JSON.stringify(manifest, null, 2),
    });

    // Also output the raw TTD IR for external tools (like echo-ttd-gen)
    files.push({
      path: 'manifest/ttd-ir.json',
      content: JSON.stringify({
        ir_version: 'ttd-ir/v1',
        schema_sha256: schema.schemaHash,
        generated_at: clock.now(),
        generated_by: {
          tool: '@wesley/generator-ttd',
          version: '0.1.0',
        },
        ...schema,
      }, null, 2),
    });
  }

  // Generate TypeScript files
  if (targets.includes('typescript')) {
    files.push({
      path: 'typescript/types.ts',
      content: generateTsTypes(schema),
    });

    files.push({
      path: 'typescript/zod.ts',
      content: generateTsZod(schema),
    });

    files.push({
      path: 'typescript/registry.ts',
      content: generateTsRegistry(schema),
    });

    // Index file
    files.push({
      path: 'typescript/index.ts',
      content: `/**
 * TTD Generated TypeScript
 *
 * Auto-generated by @wesley/generator-ttd
 * DO NOT EDIT
 */

export * from './types';
export * from './zod';
export * from './registry';
`,
    });
  }

  // Note: Rust generation is handled by external tools (e.g., echo-ttd-gen)
  // that consume the ttd-ir.json file
  if (targets.includes('rust')) {
    // Add a placeholder README explaining the architecture
    files.push({
      path: 'rust/README.md',
      content: `# Rust Code Generation

Rust code is NOT generated directly by Wesley.

Instead, use an external Rust tool that consumes the TTD IR:

\`\`\`bash
# Generate Rust code from TTD IR
cat manifest/ttd-ir.json | echo-ttd-gen --out rust/

# Or with cargo
cargo run -p echo-ttd-gen < manifest/ttd-ir.json > rust/generated.rs
\`\`\`

This architecture ensures:
1. Rust code is generated using proper Rust AST tools (syn, quote, prettyplease)
2. Wesley remains language-agnostic at its core
3. Target-language tools can evolve independently

See: https://github.com/flyingrobots/echo/tree/main/crates/echo-ttd-gen
`,
    });
  }

  return {
    files,
    schemaHash: schema.schemaHash,
    validation,
    schema, // Include extracted schema for inspection
  };
}

// Re-export for convenience
export { generateTsTypes } from './ts-types.mjs';
export { generateTsZod } from './ts-zod.mjs';
export { generateTsRegistry } from './ts-registry.mjs';
