/**
 * Rust CBOR Codecs Generator
 *
 * Generates minicbor encode/decode implementations for TTD types.
 */

/**
 * Convert camelCase to snake_case
 */
function toSnakeCase(str) {
  return str.replace(/([A-Z])/g, '_$1').toLowerCase().replace(/^_/, '');
}

/**
 * Generate Rust CBOR codecs from TTD schema
 */
export function generateRustCbor(schema) {
  const lines = [];

  lines.push('//! TTD CBOR Codecs');
  lines.push('//!');
  lines.push('//! Auto-generated by @wesley/generator-ttd');
  lines.push('//! Canonical CBOR: fields encoded in sorted key order');
  lines.push('');
  lines.push('use minicbor::{Encode, Decode, Encoder, Decoder};');
  lines.push('use minicbor::encode::Write;');
  lines.push('use super::types::*;');
  lines.push('');

  // Generate type ID constants for registry types
  for (const regEntry of schema.registry || []) {
    const constName = regEntry.typeName.replace(/([A-Z])/g, '_$1').toUpperCase().replace(/^_/, '');
    lines.push(`/// Type ID for ${regEntry.typeName}`);
    lines.push(`pub const ${constName}_TYPE_ID: u32 = ${regEntry.id};`);
  }

  if (schema.registry?.length > 0) {
    lines.push('');
  }

  // Generate encode/decode implementations for types
  for (const typeDef of schema.types || []) {
    const isRegistry = schema.registry?.some(r => r.typeName === typeDef.name);

    // Generate Encode impl
    lines.push(`impl<C> Encode<C> for ${typeDef.name} {`);
    lines.push('    fn encode<W: Write>(&self, e: &mut Encoder<W>, _ctx: &mut C) -> Result<(), minicbor::encode::Error<W::Error>> {');

    if (isRegistry) {
      const constName = typeDef.name.replace(/([A-Z])/g, '_$1').toUpperCase().replace(/^_/, '');
      lines.push(`        const TYPE_ID: u32 = ${constName}_TYPE_ID;`);
    }

    // Sort fields by name for canonical encoding
    const sortedFields = [...(typeDef.fields || [])].sort((a, b) => a.name.localeCompare(b.name));
    lines.push(`        e.map(${sortedFields.length})?;`);

    for (const field of sortedFields) {
      const snakeName = toSnakeCase(field.name);
      lines.push(`        e.str("${field.name}")?.encode(&self.${snakeName})?;`);
    }

    lines.push('        Ok(())');
    lines.push('    }');
    lines.push('}');
    lines.push('');

    // Generate Decode impl
    lines.push(`impl<'b, C> Decode<'b, C> for ${typeDef.name} {`);
    lines.push("    fn decode(d: &mut Decoder<'b>, _ctx: &mut C) -> Result<Self, minicbor::decode::Error> {");
    lines.push('        let len = d.map()?.ok_or(minicbor::decode::Error::message("expected map"))?;');

    for (const field of typeDef.fields || []) {
      const snakeName = toSnakeCase(field.name);
      lines.push(`        let mut ${snakeName} = None;`);
    }

    lines.push('        for _ in 0..len {');
    lines.push('            let key: &str = d.str()?;');
    lines.push('            match key {');

    for (const field of typeDef.fields || []) {
      const snakeName = toSnakeCase(field.name);
      lines.push(`                "${field.name}" => ${snakeName} = Some(d.decode()?),`);
    }

    lines.push('                _ => { d.skip()?; }');
    lines.push('            }');
    lines.push('        }');
    lines.push('        Ok(Self {');

    for (const field of typeDef.fields || []) {
      const snakeName = toSnakeCase(field.name);
      if (field.required) {
        lines.push(`            ${snakeName}: ${snakeName}.ok_or(minicbor::decode::Error::message("missing ${field.name}"))?,`);
      } else {
        lines.push(`            ${snakeName},`);
      }
    }

    lines.push('        })');
    lines.push('    }');
    lines.push('}');
    lines.push('');
  }

  return lines.join('\n');
}
