/**
 * Rust Types Generator
 *
 * Generates Rust struct and enum definitions from TTD schema.
 */

/**
 * Convert camelCase to snake_case
 */
function toSnakeCase(str) {
  return str.replace(/([A-Z])/g, '_$1').toLowerCase().replace(/^_/, '');
}

/**
 * Convert SCREAMING_CASE to PascalCase
 */
function toPascalCase(str) {
  return str
    .toLowerCase()
    .split('_')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join('');
}

/**
 * Map GraphQL type to Rust type
 */
function mapType(gqlType, required) {
  const typeMap = {
    ID: 'String',
    String: 'String',
    Int: 'i64',
    Float: 'f64',
    Boolean: 'bool',
  };

  const rustType = typeMap[gqlType] || gqlType;
  return required ? rustType : `Option<${rustType}>`;
}

/**
 * Generate Rust types from TTD schema
 */
export function generateRustTypes(schema) {
  const lines = [];

  lines.push('//! TTD Generated Types');
  lines.push('//!');
  lines.push('//! Auto-generated by @wesley/generator-ttd');
  lines.push('');
  lines.push('use serde::{Deserialize, Serialize};');
  lines.push('');

  // Generate enums
  for (const enumDef of schema.enums || []) {
    lines.push('#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]');
    lines.push(`pub enum ${enumDef.name} {`);
    for (const value of enumDef.values) {
      const pascalValue = toPascalCase(value);
      if (pascalValue !== value) {
        lines.push(`    #[serde(rename = "${value}")]`);
      }
      lines.push(`    ${pascalValue},`);
    }
    lines.push('}');
    lines.push('');
  }

  // Generate structs for types
  for (const typeDef of schema.types || []) {
    lines.push('#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]');
    lines.push(`pub struct ${typeDef.name} {`);

    for (const field of typeDef.fields || []) {
      const snakeName = toSnakeCase(field.name);
      const rustType = mapType(field.type, field.required);

      if (snakeName !== field.name) {
        lines.push(`    #[serde(rename = "${field.name}")]`);
      }
      lines.push(`    pub ${snakeName}: ${rustType},`);
    }

    lines.push('}');
    lines.push('');
  }

  // Generate operation argument structs
  for (const op of schema.ops || []) {
    if (op.args && op.args.length > 0) {
      const structName = `${op.name.charAt(0).toUpperCase()}${op.name.slice(1)}Args`;
      lines.push('#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]');
      lines.push(`pub struct ${structName} {`);

      for (const arg of op.args) {
        const snakeName = toSnakeCase(arg.name);
        const rustType = mapType(arg.type, arg.required);

        if (snakeName !== arg.name) {
          lines.push(`    #[serde(rename = "${arg.name}")]`);
        }
        lines.push(`    pub ${snakeName}: ${rustType},`);
      }

      lines.push('}');
      lines.push('');
    }
  }

  return lines.join('\n');
}
