/**
 * TypeScript Types Generator
 *
 * Generates TypeScript interfaces and types from TTD schema.
 */

/**
 * Map GraphQL type to TypeScript type
 */
function mapType(gqlType, required, list) {
  const typeMap = {
    ID: 'string',
    String: 'string',
    Int: 'number',
    Float: 'number',
    Boolean: 'boolean',
  };

  let tsType = typeMap[gqlType] || gqlType;

  if (list) {
    tsType = `${tsType}[]`;
  }

  return required ? tsType : `${tsType} | null`;
}

/**
 * Generate TypeScript types from TTD schema
 */
export function generateTsTypes(schema) {
  const lines = [];

  lines.push('/**');
  lines.push(' * TTD Generated Types');
  lines.push(' *');
  lines.push(' * Auto-generated by @wesley/generator-ttd');
  lines.push(' * DO NOT EDIT');
  lines.push(' */');
  lines.push('');

  // Generate enums
  for (const enumDef of schema.enums || []) {
    lines.push(`/**`);
    lines.push(` * ${enumDef.name} enum`);
    lines.push(` */`);
    lines.push(`export enum ${enumDef.name} {`);
    for (const value of enumDef.values) {
      lines.push(`  ${value} = '${value}',`);
    }
    lines.push('}');
    lines.push('');
  }

  // Generate interfaces for types
  for (const typeDef of schema.types || []) {
    lines.push(`/**`);
    lines.push(` * ${typeDef.name} interface`);
    if (typeDef.version) {
      lines.push(` * @version ${typeDef.version.major}.${typeDef.version.minor}.${typeDef.version.patch || 0}`);
    }
    lines.push(` */`);
    lines.push(`export interface ${typeDef.name} {`);

    for (const field of typeDef.fields || []) {
      const tsType = mapType(field.type, field.required, field.list);
      const optional = field.required ? '' : '?';
      lines.push(`  ${field.name}${optional}: ${tsType};`);
    }

    lines.push('}');
    lines.push('');
  }

  // Generate operation argument interfaces
  for (const op of schema.ops || []) {
    if (op.args && op.args.length > 0) {
      const interfaceName = `${op.name.charAt(0).toUpperCase()}${op.name.slice(1)}Args`;
      lines.push(`/**`);
      lines.push(` * Arguments for ${op.name} operation`);
      lines.push(` */`);
      lines.push(`export interface ${interfaceName} {`);

      for (const arg of op.args) {
        const tsType = mapType(arg.type, arg.required, arg.list);
        const optional = arg.required ? '' : '?';
        lines.push(`  ${arg.name}${optional}: ${tsType};`);
      }

      lines.push('}');
      lines.push('');
    }
  }

  return lines.join('\n');
}
