/**
 * TypeScript Zod Validators Generator
 *
 * Generates Zod schemas for runtime validation from TTD schema.
 */

/**
 * Map GraphQL type to Zod validator
 */
function mapTypeToZod(gqlType) {
  const typeMap = {
    ID: 'z.string()',
    String: 'z.string()',
    Int: 'z.number().int()',
    Float: 'z.number()',
    Boolean: 'z.boolean()',
  };

  return typeMap[gqlType] || `${gqlType}Schema`;
}

/**
 * Generate constraint validators
 */
function generateConstraints(constraint) {
  if (!constraint) return '';

  const validators = [];

  if (constraint.min !== undefined) {
    validators.push(`.min(${constraint.min})`);
  }
  if (constraint.max !== undefined) {
    validators.push(`.max(${constraint.max})`);
  }
  if (constraint.minLength !== undefined) {
    validators.push(`.min(${constraint.minLength})`);
  }
  if (constraint.maxLength !== undefined) {
    validators.push(`.max(${constraint.maxLength})`);
  }
  if (constraint.pattern) {
    validators.push(`.regex(/${constraint.pattern}/)`);
  }

  return validators.join('');
}

/**
 * Generate Zod schemas from TTD schema
 */
export function generateTsZod(schema) {
  const lines = [];

  lines.push('/**');
  lines.push(' * TTD Generated Zod Validators');
  lines.push(' *');
  lines.push(' * Auto-generated by @wesley/generator-ttd');
  lines.push(' * DO NOT EDIT');
  lines.push(' */');
  lines.push('');
  lines.push("import { z } from 'zod';");
  lines.push('');

  // Generate enum schemas
  for (const enumDef of schema.enums || []) {
    const values = enumDef.values.map(v => `'${v}'`).join(', ');
    lines.push(`/**`);
    lines.push(` * Zod schema for ${enumDef.name}`);
    lines.push(` */`);
    lines.push(`export const ${enumDef.name}Schema = z.enum([${values}]);`);
    lines.push(`export type ${enumDef.name} = z.infer<typeof ${enumDef.name}Schema>;`);
    lines.push('');
  }

  // Generate object schemas
  for (const typeDef of schema.types || []) {
    lines.push(`/**`);
    lines.push(` * Zod schema for ${typeDef.name}`);
    lines.push(` */`);
    lines.push(`export const ${typeDef.name}Schema = z.object({`);

    for (const field of typeDef.fields || []) {
      let zodType = mapTypeToZod(field.type);

      // Add constraints
      const constraints = generateConstraints(field.constraint);
      if (constraints) {
        zodType = `${zodType}${constraints}`;
      }

      // Handle list types
      if (field.list) {
        zodType = `z.array(${zodType})`;
      }

      // Handle optional fields
      if (!field.required) {
        zodType = `${zodType}.nullable()`;
      }

      lines.push(`  ${field.name}: ${zodType},`);
    }

    lines.push('});');
    lines.push(`export type ${typeDef.name} = z.infer<typeof ${typeDef.name}Schema>;`);
    lines.push('');
  }

  // Generate operation argument schemas
  for (const op of schema.ops || []) {
    if (op.args && op.args.length > 0) {
      const schemaName = `${op.name.charAt(0).toUpperCase()}${op.name.slice(1)}ArgsSchema`;
      lines.push(`/**`);
      lines.push(` * Zod schema for ${op.name} arguments`);
      lines.push(` */`);
      lines.push(`export const ${schemaName} = z.object({`);

      for (const arg of op.args) {
        let zodType = mapTypeToZod(arg.type);

        if (arg.list) {
          zodType = `z.array(${zodType})`;
        }

        if (!arg.required) {
          zodType = `${zodType}.optional()`;
        }

        lines.push(`  ${arg.name}: ${zodType},`);
      }

      lines.push('});');
      lines.push(`export type ${op.name.charAt(0).toUpperCase()}${op.name.slice(1)}Args = z.infer<typeof ${schemaName}>;`);
      lines.push('');
    }
  }

  return lines.join('\n');
}
