name: "Install bats and jq"
description: "Installs bats and jq via apt-get on ubuntu-latest"
runs:
  using: "composite"
  steps:
    - name: Install bats
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y bats jq
