name: 'Install Bats, JQ, and ripgrep'
description: 'Installs bats, jq, and ripgrep on Ubuntu runners'
runs:
  using: 'composite'
  steps:
    - name: apt-get update
      shell: bash
      run: sudo apt-get update
    - name: install bats, jq, and ripgrep
      shell: bash
      run: sudo apt-get install -y bats jq ripgrep
