import { parse, Kind } from 'graphql';
import { unwrapType } from './graphql-utils.mjs';

/**
 * Emit `wasm_abi_codec.generated.ts` containing TypeScript encode/decode
 * functions for WASM ABI response types, plus binary envelope helpers.
 *
 * Wire format is byte-identical to the Rust codec (emitWasmAbiCodec).
 *
 * @param {string} abiSdl - GraphQL SDL defining ABI response types
 * @returns {string | null}
 */
export function emitWasmAbiCodecTs(abiSdl) {
  const types = parseAbiTypes(abiSdl);
  if (types.length === 0) return null;

  const lines = [];

  lines.push('// Auto-generated by @wesley/generator-echo — DO NOT EDIT');
  lines.push('');

  // Type interfaces
  for (const type of types) {
    emitInterface(lines, type);
  }

  // AbiResult type
  lines.push('export type AbiResult<T> = { ok: true; value: T } | { ok: false; error: AbiError };');
  lines.push('');

  // Helpers
  emitHelpers(lines);

  // Per-type encode/decode
  for (const type of types) {
    emitObjectCodec(lines, type);
  }

  // Envelope
  emitEnvelope(lines, types);

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// ABI SDL parser
// ---------------------------------------------------------------------------

function parseAbiTypes(sdl) {
  const doc = parse(sdl);
  const types = [];

  for (const def of doc.definitions) {
    if (def.kind === Kind.OBJECT_TYPE_DEFINITION) {
      const fields = (def.fields ?? []).map((f) => {
        const { typeName, required, list } = unwrapType(f.type);
        return { name: f.name.value, type: typeName, required, list };
      });
      types.push({ name: def.name.value, kind: 'OBJECT', fields });
    }
  }

  types.sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
  return types;
}


// ---------------------------------------------------------------------------
// Interface emission
// ---------------------------------------------------------------------------

function tsTypeForField(fieldType, required, list) {
  let tsType;
  switch (fieldType) {
  case 'Boolean':
    tsType = 'boolean';
    break;
  case 'String':
    tsType = 'string';
    break;
  case 'Hash32':
    tsType = 'Uint8Array';
    break;
  case 'Bytes':
    tsType = 'Uint8Array';
    break;
  case 'U32':
    tsType = 'number';
    break;
  case 'U64':
    tsType = 'bigint';
    break;
  default:
    tsType = fieldType;
    break;
  }
  if (list) tsType = `${tsType}[]`;
  if (!required) tsType = `${tsType} | null`;
  return tsType;
}

function emitInterface(lines, type) {
  const fields = [...(type.fields ?? [])].sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
  lines.push(`export interface ${type.name} {`);
  for (const field of fields) {
    const tsType = tsTypeForField(field.type, field.required, field.list);
    const opt = field.required ? '' : '?';
    lines.push(`  ${field.name}${opt}: ${tsType};`);
  }
  lines.push('}');
  lines.push('');
}

// ---------------------------------------------------------------------------
// Shared encode/decode helpers
// ---------------------------------------------------------------------------

function emitHelpers(lines) {
  lines.push('const _textEncoder = new TextEncoder();');
  lines.push('const _textDecoder = new TextDecoder();');
  lines.push('');

  // --- Encode helpers ---

  lines.push('function _encodeBool(buf: number[], v: boolean): void {');
  lines.push('  buf.push(v ? 0x01 : 0x00);');
  lines.push('}');
  lines.push('');

  lines.push('function _encodeU32(buf: number[], v: number): void {');
  lines.push('  const tmp = new DataView(new ArrayBuffer(4));');
  lines.push('  tmp.setUint32(0, v, true);');
  lines.push('  for (let i = 0; i < 4; i++) buf.push(tmp.getUint8(i));');
  lines.push('}');
  lines.push('');

  lines.push('function _encodeU64(buf: number[], v: bigint): void {');
  lines.push('  const tmp = new DataView(new ArrayBuffer(8));');
  lines.push('  tmp.setBigUint64(0, v, true);');
  lines.push('  for (let i = 0; i < 8; i++) buf.push(tmp.getUint8(i));');
  lines.push('}');
  lines.push('');

  lines.push('function _encodeString(buf: number[], v: string): void {');
  lines.push('  const encoded = _textEncoder.encode(v);');
  lines.push('  const tmp = new DataView(new ArrayBuffer(4));');
  lines.push('  tmp.setUint32(0, encoded.length, true);');
  lines.push('  for (let i = 0; i < 4; i++) buf.push(tmp.getUint8(i));');
  lines.push('  for (let i = 0; i < encoded.length; i++) buf.push(encoded[i]);');
  lines.push('}');
  lines.push('');

  lines.push('function _encodeHash32(buf: number[], v: Uint8Array): void {');
  lines.push('  if (v.length !== 32) throw new Error("Hash32 must be exactly 32 bytes, got " + v.length);');
  lines.push('  for (let i = 0; i < 32; i++) buf.push(v[i]);');
  lines.push('}');
  lines.push('');

  lines.push('function _encodeBytes(buf: number[], v: Uint8Array): void {');
  lines.push('  const tmp = new DataView(new ArrayBuffer(4));');
  lines.push('  tmp.setUint32(0, v.length, true);');
  lines.push('  for (let i = 0; i < 4; i++) buf.push(tmp.getUint8(i));');
  lines.push('  for (let i = 0; i < v.length; i++) buf.push(v[i]);');
  lines.push('}');
  lines.push('');

  lines.push('function _encodeOption<T>(buf: number[], v: T | null, encodeInner: (buf: number[], v: T) => void): void {');
  lines.push('  if (v == null) {');
  lines.push('    buf.push(0x00);');
  lines.push('  } else {');
  lines.push('    buf.push(0x01);');
  lines.push('    encodeInner(buf, v);');
  lines.push('  }');
  lines.push('}');
  lines.push('');

  lines.push('function _encodeList<T>(buf: number[], v: T[], encodeInner: (buf: number[], v: T) => void): void {');
  lines.push('  const tmp = new DataView(new ArrayBuffer(4));');
  lines.push('  tmp.setUint32(0, v.length, true);');
  lines.push('  for (let i = 0; i < 4; i++) buf.push(tmp.getUint8(i));');
  lines.push('  for (const item of v) encodeInner(buf, item);');
  lines.push('}');
  lines.push('');

  // --- Decode helpers ---

  lines.push('function _decodeBool(bytes: Uint8Array, offset: { v: number }): boolean {');
  lines.push('  if (offset.v >= bytes.length) throw new Error("unexpected end of input");');
  lines.push('  const v = bytes[offset.v] !== 0x00;');
  lines.push('  offset.v += 1;');
  lines.push('  return v;');
  lines.push('}');
  lines.push('');

  lines.push('function _decodeU32(bytes: Uint8Array, offset: { v: number }): number {');
  lines.push('  if (offset.v + 4 > bytes.length) throw new Error("unexpected end of input");');
  lines.push('  const dv = new DataView(bytes.buffer, bytes.byteOffset + offset.v, 4);');
  lines.push('  const val = dv.getUint32(0, true);');
  lines.push('  offset.v += 4;');
  lines.push('  return val;');
  lines.push('}');
  lines.push('');

  lines.push('function _decodeU64(bytes: Uint8Array, offset: { v: number }): bigint {');
  lines.push('  if (offset.v + 8 > bytes.length) throw new Error("unexpected end of input");');
  lines.push('  const dv = new DataView(bytes.buffer, bytes.byteOffset + offset.v, 8);');
  lines.push('  const val = dv.getBigUint64(0, true);');
  lines.push('  offset.v += 8;');
  lines.push('  return val;');
  lines.push('}');
  lines.push('');

  lines.push('function _decodeString(bytes: Uint8Array, offset: { v: number }): string {');
  lines.push('  if (offset.v + 4 > bytes.length) throw new Error("unexpected end of input");');
  lines.push('  const dv = new DataView(bytes.buffer, bytes.byteOffset + offset.v, 4);');
  lines.push('  const len = dv.getUint32(0, true);');
  lines.push('  offset.v += 4;');
  lines.push('  if (offset.v + len > bytes.length) throw new Error("unexpected end of input");');
  lines.push('  const val = _textDecoder.decode(bytes.subarray(offset.v, offset.v + len));');
  lines.push('  offset.v += len;');
  lines.push('  return val;');
  lines.push('}');
  lines.push('');

  lines.push('function _decodeHash32(bytes: Uint8Array, offset: { v: number }): Uint8Array {');
  lines.push('  if (offset.v + 32 > bytes.length) throw new Error("unexpected end of input");');
  lines.push('  const val = bytes.slice(offset.v, offset.v + 32);');
  lines.push('  offset.v += 32;');
  lines.push('  return val;');
  lines.push('}');
  lines.push('');

  lines.push('function _decodeBytes(bytes: Uint8Array, offset: { v: number }): Uint8Array {');
  lines.push('  if (offset.v + 4 > bytes.length) throw new Error("unexpected end of input");');
  lines.push('  const dv = new DataView(bytes.buffer, bytes.byteOffset + offset.v, 4);');
  lines.push('  const len = dv.getUint32(0, true);');
  lines.push('  offset.v += 4;');
  lines.push('  if (offset.v + len > bytes.length) throw new Error("unexpected end of input");');
  lines.push('  const val = bytes.slice(offset.v, offset.v + len);');
  lines.push('  offset.v += len;');
  lines.push('  return val;');
  lines.push('}');
  lines.push('');

  lines.push('function _decodeOption<T>(bytes: Uint8Array, offset: { v: number }, decodeInner: (bytes: Uint8Array, offset: { v: number }) => T): T | null {');
  lines.push('  if (offset.v >= bytes.length) throw new Error("unexpected end of input");');
  lines.push('  const tag = bytes[offset.v];');
  lines.push('  offset.v += 1;');
  lines.push('  if (tag === 0x00) return null;');
  lines.push('  if (tag === 0x01) return decodeInner(bytes, offset);');
  lines.push('  throw new Error(`invalid option tag: ${tag}`);');
  lines.push('}');
  lines.push('');

  lines.push('function _decodeList<T>(bytes: Uint8Array, offset: { v: number }, decodeInner: (bytes: Uint8Array, offset: { v: number }) => T): T[] {');
  lines.push('  if (offset.v + 4 > bytes.length) throw new Error("unexpected end of input");');
  lines.push('  const dv = new DataView(bytes.buffer, bytes.byteOffset + offset.v, 4);');
  lines.push('  const count = dv.getUint32(0, true);');
  lines.push('  offset.v += 4;');
  lines.push('  const items: T[] = [];');
  lines.push('  for (let i = 0; i < count; i++) items.push(decodeInner(bytes, offset));');
  lines.push('  return items;');
  lines.push('}');
  lines.push('');
}

// ---------------------------------------------------------------------------
// Per-type encode/decode codegen
// ---------------------------------------------------------------------------

function encodeCallForScalar(typeName, accessor) {
  switch (typeName) {
  case 'Boolean':
    return `_encodeBool(buf, ${accessor});`;
  case 'U32':
    return `_encodeU32(buf, ${accessor});`;
  case 'U64':
    return `_encodeU64(buf, ${accessor});`;
  case 'String':
    return `_encodeString(buf, ${accessor});`;
  case 'Hash32':
    return `_encodeHash32(buf, ${accessor});`;
  case 'Bytes':
    return `_encodeBytes(buf, ${accessor});`;
  default:
    return `_encode${typeName}(buf, ${accessor});`;
  }
}

function encodeInnerClosureForType(typeName) {
  switch (typeName) {
  case 'Boolean':
    return '_encodeBool';
  case 'U32':
    return '_encodeU32';
  case 'U64':
    return '_encodeU64';
  case 'String':
    return '_encodeString';
  case 'Hash32':
    return '_encodeHash32';
  case 'Bytes':
    return '_encodeBytes';
  default:
    return `(buf, v) => _encode${typeName}(buf, v)`;
  }
}

function decodeCallForType(typeName) {
  switch (typeName) {
  case 'Boolean':
    return '_decodeBool';
  case 'U32':
    return '_decodeU32';
  case 'U64':
    return '_decodeU64';
  case 'String':
    return '_decodeString';
  case 'Hash32':
    return '_decodeHash32';
  case 'Bytes':
    return '_decodeBytes';
  default:
    return `(bytes, off) => { const _r = decode${typeName}(bytes, off.v); off.v += _r.bytesRead; return _r.value; }`;
  }
}

function decodeDirectCallForType(typeName, fieldName) {
  switch (typeName) {
  case 'Boolean':
    return `const ${fieldName} = _decodeBool(bytes, off);`;
  case 'U32':
    return `const ${fieldName} = _decodeU32(bytes, off);`;
  case 'U64':
    return `const ${fieldName} = _decodeU64(bytes, off);`;
  case 'String':
    return `const ${fieldName} = _decodeString(bytes, off);`;
  case 'Hash32':
    return `const ${fieldName} = _decodeHash32(bytes, off);`;
  case 'Bytes':
    return `const ${fieldName} = _decodeBytes(bytes, off);`;
  default:
    return `const _${fieldName}Res = decode${typeName}(bytes, off.v); const ${fieldName} = _${fieldName}Res.value; off.v += _${fieldName}Res.bytesRead;`;
  }
}

function emitFieldEncode(lines, field, accessor) {
  const { type, required, list } = field;

  if (list && required) {
    lines.push(`  _encodeList(buf, ${accessor}, ${encodeInnerClosureForType(type)});`);
  } else if (list && !required) {
    lines.push(`  _encodeOption(buf, ${accessor}, (buf, inner) => _encodeList(buf, inner, ${encodeInnerClosureForType(type)}));`);
  } else if (!required) {
    lines.push(`  _encodeOption(buf, ${accessor}, ${encodeInnerClosureForType(type)});`);
  } else {
    lines.push(`  ${encodeCallForScalar(type, accessor)}`);
  }
}

function emitFieldDecode(lines, field) {
  const { name, type, required, list } = field;

  if (list && required) {
    lines.push(`  const ${name} = _decodeList(bytes, off, ${decodeCallForType(type)});`);
  } else if (list && !required) {
    lines.push(`  const ${name} = _decodeOption(bytes, off, (bytes, off) => _decodeList(bytes, off, ${decodeCallForType(type)}));`);
  } else if (!required) {
    lines.push(`  const ${name} = _decodeOption(bytes, off, ${decodeCallForType(type)});`);
  } else {
    lines.push(`  ${decodeDirectCallForType(type, name)}`);
  }
}

function emitObjectCodec(lines, type) {
  const fields = [...(type.fields ?? [])].sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));

  // In-place encode
  lines.push(`function _encode${type.name}(buf: number[], value: ${type.name}): void {`);
  for (const field of fields) {
    emitFieldEncode(lines, field, `value.${field.name}`);
  }
  lines.push('}');
  lines.push('');

  // Public encode
  lines.push(`export function encode${type.name}(value: ${type.name}): Uint8Array {`);
  lines.push('  const buf: number[] = [];');
  lines.push(`  _encode${type.name}(buf, value);`);
  lines.push('  return new Uint8Array(buf);');
  lines.push('}');
  lines.push('');

  // Public decode
  lines.push(`export function decode${type.name}(bytes: Uint8Array, offset?: number): { value: ${type.name}; bytesRead: number } {`);
  lines.push('  const off = { v: offset ?? 0 };');
  for (const field of fields) {
    emitFieldDecode(lines, field);
  }
  lines.push('  return {');
  lines.push(`    value: { ${fields.map((f) => f.name).join(', ')} },`);
  lines.push('    bytesRead: off.v - (offset ?? 0),');
  lines.push('  };');
  lines.push('}');
  lines.push('');
}

// ---------------------------------------------------------------------------
// Envelope emission
// ---------------------------------------------------------------------------

function emitEnvelope(lines, types) {
  // encodeOk
  lines.push('/** Wrap an already-encoded success payload in the ABI envelope. */');
  lines.push('export function encodeOk(payload: Uint8Array): Uint8Array {');
  lines.push('  const buf = new Uint8Array(1 + payload.length);');
  lines.push('  buf[0] = 0x01;');
  lines.push('  buf.set(payload, 1);');
  lines.push('  return buf;');
  lines.push('}');
  lines.push('');

  // encodeErr
  lines.push('/** Encode an error response in the ABI envelope. */');
  lines.push('export function encodeErr(code: number, message: string): Uint8Array {');
  lines.push('  const buf: number[] = [];');
  lines.push('  buf.push(0x00);');
  lines.push('  _encodeU32(buf, code);');
  lines.push('  _encodeString(buf, message);');
  lines.push('  return new Uint8Array(buf);');
  lines.push('}');
  lines.push('');

  // decodeEnvelope
  lines.push('/**');
  lines.push(' * Decode the ABI envelope. Returns an AbiResult wrapping the decoded payload.');
  lines.push(' * Success envelope: [0x01] [payload...]');
  lines.push(' * Error envelope:   [0x00] [u32 LE code] [u32 LE msg_len] [UTF-8 msg...]');
  lines.push(' */');
  lines.push('export function decodeEnvelope<T>(');
  lines.push('  bytes: Uint8Array,');
  lines.push('  decodePayload: (bytes: Uint8Array, offset?: number) => { value: T; bytesRead: number },');
  lines.push('): AbiResult<T> {');
  lines.push('  if (bytes.length === 0) throw new Error("unexpected end of input");');
  lines.push('  const tag = bytes[0];');
  lines.push('  if (tag === 0x01) {');
  lines.push('    const result = decodePayload(bytes, 1);');
  lines.push('    return { ok: true, value: result.value };');
  lines.push('  }');
  lines.push('  if (tag === 0x00) {');
  lines.push('    const off = { v: 1 };');
  lines.push('    const code = _decodeU32(bytes, off);');
  lines.push('    const message = _decodeString(bytes, off);');
  lines.push('    return { ok: false, error: { code, message } };');
  lines.push('  }');
  lines.push('  throw new Error("invalid envelope tag: " + tag);');
  lines.push('}');
  lines.push('');

  // Convenience envelope decoders for response types
  // (skip AbiError, ChannelData, HeadInfo — those are not top-level responses)
  const responseTypes = types.filter((t) =>
    t.name.endsWith('Response') || t.name === 'RegistryInfo'
  );

  for (const type of responseTypes) {
    lines.push(`/** Decode a ${type.name} from its ABI envelope. */`);
    lines.push(`export function decode${type.name}Envelope(bytes: Uint8Array): AbiResult<${type.name}> {`);
    lines.push(`  return decodeEnvelope(bytes, decode${type.name});`);
    lines.push('}');
    lines.push('');
  }
}
