/**
 * Emit a TypeScript `raw_le_codec.generated.ts` file containing deterministic
 * encode/decode functions for every OBJECT and ENUM type in the IR.
 *
 * Layout follows SPEC-0008 (byte-identical to the Rust raw_le codec):
 * - Fields encoded in alphabetical order
 * - Little-endian byte order for all numerics
 * - Collision-free Option prefix (0x00 = None, 0x01 = Some)
 * - NaN canonicalization for f32 (0x7FC00000)
 *
 * Returns `null` when the IR contains no OBJECT or ENUM types.
 *
 * @param {{ types: Array<{ name: string, kind: string, fields?: Array<{ name: string, type: string, required: boolean, list: boolean }>, values?: string[] }> }} ir
 * @returns {string | null}
 */
export function emitRawLeTsCodec(ir) {
  const encodableTypes = (ir.types ?? []).filter(
    (t) => t.kind === 'OBJECT' || t.kind === 'ENUM',
  );

  if (encodableTypes.length === 0) return null;

  const lines = [];

  lines.push('// Auto-generated by @wesley/generator-echo — DO NOT EDIT');
  lines.push('');

  // Emit type interfaces/enums first
  for (const type of encodableTypes) {
    if (type.kind === 'ENUM') {
      emitEnumType(lines, type);
    } else if (type.kind === 'OBJECT') {
      emitObjectInterface(lines, type, encodableTypes);
    }
  }

  // Shared helpers
  emitHelpers(lines);

  // Per-type encode/decode functions
  for (const type of encodableTypes) {
    if (type.kind === 'ENUM') {
      emitEnumCodec(lines, type);
    } else if (type.kind === 'OBJECT') {
      emitObjectCodec(lines, type);
    }
  }

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Type / Interface emission
// ---------------------------------------------------------------------------

function emitEnumType(lines, type) {
  const sorted = [...type.values].sort((a, b) => a < b ? -1 : a > b ? 1 : 0);
  lines.push(`export type ${type.name} = ${sorted.map((v) => `'${v}'`).join(' | ')};`);
  lines.push('');
}

function tsTypeForField(fieldType, required, list, encodableTypes) {
  let tsType;
  switch (fieldType) {
    case 'Boolean':
      tsType = 'boolean';
      break;
    case 'Int':
    case 'Float':
      tsType = 'number';
      break;
    case 'String':
    case 'ID':
      tsType = 'string';
      break;
    default: {
      // Could be an enum or object type
      tsType = fieldType;
      break;
    }
  }
  if (list) tsType = `${tsType}[]`;
  if (!required) tsType = `${tsType} | null | undefined`;
  return tsType;
}

function emitObjectInterface(lines, type, encodableTypes) {
  const fields = [...(type.fields ?? [])].sort((a, b) => a.name < b.name ? -1 : a.name > b.name ? 1 : 0);
  lines.push(`export interface ${type.name} {`);
  for (const field of fields) {
    const tsType = tsTypeForField(field.type, field.required, field.list, encodableTypes);
    const opt = field.required ? '' : '?';
    lines.push(`  ${field.name}${opt}: ${tsType};`);
  }
  lines.push('}');
  lines.push('');
}

// ---------------------------------------------------------------------------
// Shared encode/decode helpers
// ---------------------------------------------------------------------------

function emitHelpers(lines) {
  // TextEncoder singleton
  lines.push('const _textEncoder = new TextEncoder();');
  lines.push('const _textDecoder = new TextDecoder();');
  lines.push('');

  // _encodeBool
  lines.push('function _encodeBool(buf: number[], v: boolean): void {');
  lines.push('  buf.push(v ? 0x01 : 0x00);');
  lines.push('}');
  lines.push('');

  // _encodeI32
  lines.push('function _encodeI32(buf: number[], v: number): void {');
  lines.push('  const tmp = new DataView(new ArrayBuffer(4));');
  lines.push('  tmp.setInt32(0, v, true);');
  lines.push('  for (let i = 0; i < 4; i++) buf.push(tmp.getUint8(i));');
  lines.push('}');
  lines.push('');

  // _encodeF32
  lines.push('function _encodeF32(buf: number[], v: number): void {');
  lines.push('  const tmp = new DataView(new ArrayBuffer(4));');
  lines.push('  if (Number.isNaN(v)) {');
  lines.push('    tmp.setUint32(0, 0x7FC00000, true);');
  lines.push('  } else {');
  lines.push('    tmp.setFloat32(0, v, true);');
  lines.push('  }');
  lines.push('  for (let i = 0; i < 4; i++) buf.push(tmp.getUint8(i));');
  lines.push('}');
  lines.push('');

  // _encodeString
  lines.push('function _encodeString(buf: number[], v: string): void {');
  lines.push('  const encoded = _textEncoder.encode(v);');
  lines.push('  const tmp = new DataView(new ArrayBuffer(4));');
  lines.push('  tmp.setUint32(0, encoded.length, true);');
  lines.push('  for (let i = 0; i < 4; i++) buf.push(tmp.getUint8(i));');
  lines.push('  for (let i = 0; i < encoded.length; i++) buf.push(encoded[i]);');
  lines.push('}');
  lines.push('');

  // _encodeOption
  lines.push('function _encodeOption<T>(buf: number[], v: T | null | undefined, encodeInner: (buf: number[], v: T) => void): void {');
  lines.push('  if (v == null) {');
  lines.push('    buf.push(0x00);');
  lines.push('  } else {');
  lines.push('    buf.push(0x01);');
  lines.push('    encodeInner(buf, v);');
  lines.push('  }');
  lines.push('}');
  lines.push('');

  // _encodeList
  lines.push('function _encodeList<T>(buf: number[], v: T[], encodeInner: (buf: number[], v: T) => void): void {');
  lines.push('  const tmp = new DataView(new ArrayBuffer(4));');
  lines.push('  tmp.setUint32(0, v.length, true);');
  lines.push('  for (let i = 0; i < 4; i++) buf.push(tmp.getUint8(i));');
  lines.push('  for (const item of v) encodeInner(buf, item);');
  lines.push('}');
  lines.push('');

  // Decode helpers
  lines.push('function _decodeBool(bytes: Uint8Array, offset: { v: number }): boolean {');
  lines.push('  if (offset.v >= bytes.length) throw new Error("unexpected end of input");');
  lines.push('  const v = bytes[offset.v] !== 0x00;');
  lines.push('  offset.v += 1;');
  lines.push('  return v;');
  lines.push('}');
  lines.push('');

  lines.push('function _decodeI32(bytes: Uint8Array, offset: { v: number }): number {');
  lines.push('  if (offset.v + 4 > bytes.length) throw new Error("unexpected end of input");');
  lines.push('  const dv = new DataView(bytes.buffer, bytes.byteOffset + offset.v, 4);');
  lines.push('  const val = dv.getInt32(0, true);');
  lines.push('  offset.v += 4;');
  lines.push('  return val;');
  lines.push('}');
  lines.push('');

  lines.push('function _decodeF32(bytes: Uint8Array, offset: { v: number }): number {');
  lines.push('  if (offset.v + 4 > bytes.length) throw new Error("unexpected end of input");');
  lines.push('  const dv = new DataView(bytes.buffer, bytes.byteOffset + offset.v, 4);');
  lines.push('  const val = dv.getFloat32(0, true);');
  lines.push('  offset.v += 4;');
  lines.push('  return val;');
  lines.push('}');
  lines.push('');

  lines.push('function _decodeString(bytes: Uint8Array, offset: { v: number }): string {');
  lines.push('  if (offset.v + 4 > bytes.length) throw new Error("unexpected end of input");');
  lines.push('  const dv = new DataView(bytes.buffer, bytes.byteOffset + offset.v, 4);');
  lines.push('  const len = dv.getUint32(0, true);');
  lines.push('  offset.v += 4;');
  lines.push('  if (offset.v + len > bytes.length) throw new Error("unexpected end of input");');
  lines.push('  const val = _textDecoder.decode(bytes.subarray(offset.v, offset.v + len));');
  lines.push('  offset.v += len;');
  lines.push('  return val;');
  lines.push('}');
  lines.push('');

  lines.push('function _decodeOption<T>(bytes: Uint8Array, offset: { v: number }, decodeInner: (bytes: Uint8Array, offset: { v: number }) => T): T | null {');
  lines.push('  if (offset.v >= bytes.length) throw new Error("unexpected end of input");');
  lines.push('  const tag = bytes[offset.v];');
  lines.push('  offset.v += 1;');
  lines.push('  if (tag === 0x00) return null;');
  lines.push('  if (tag === 0x01) return decodeInner(bytes, offset);');
  lines.push('  throw new Error(`invalid option tag: ${tag}`);');
  lines.push('}');
  lines.push('');

  lines.push('function _decodeList<T>(bytes: Uint8Array, offset: { v: number }, decodeInner: (bytes: Uint8Array, offset: { v: number }) => T): T[] {');
  lines.push('  if (offset.v + 4 > bytes.length) throw new Error("unexpected end of input");');
  lines.push('  const dv = new DataView(bytes.buffer, bytes.byteOffset + offset.v, 4);');
  lines.push('  const count = dv.getUint32(0, true);');
  lines.push('  offset.v += 4;');
  lines.push('  const items: T[] = [];');
  lines.push('  for (let i = 0; i < count; i++) items.push(decodeInner(bytes, offset));');
  lines.push('  return items;');
  lines.push('}');
  lines.push('');
}

// ---------------------------------------------------------------------------
// Per-type codegen
// ---------------------------------------------------------------------------

const SCALAR_TYPES = new Set(['Boolean', 'Int', 'Float', 'String', 'ID']);

function isScalar(typeName) {
  return SCALAR_TYPES.has(typeName);
}

/**
 * Emit encode/decode for an ENUM type.
 * Variants sorted alphabetically; index is u32 LE.
 */
function emitEnumCodec(lines, type) {
  const sorted = [...type.values].sort((a, b) => a < b ? -1 : a > b ? 1 : 0);

  // encode
  lines.push(`export function encode${type.name}(value: ${type.name}): Uint8Array {`);
  lines.push('  const buf: number[] = [];');
  lines.push('  const tmp = new DataView(new ArrayBuffer(4));');
  lines.push('  let idx: number;');
  lines.push('  switch (value) {');
  sorted.forEach((v, i) => {
    lines.push(`    case '${v}': idx = ${i}; break;`);
  });
  lines.push(`    default: throw new Error('invalid enum variant: ' + value);`);
  lines.push('  }');
  lines.push('  tmp.setUint32(0, idx, true);');
  lines.push('  for (let i = 0; i < 4; i++) buf.push(tmp.getUint8(i));');
  lines.push('  return new Uint8Array(buf);');
  lines.push('}');
  lines.push('');

  // decode
  lines.push(`export function decode${type.name}(bytes: Uint8Array, offset?: number): { value: ${type.name}; bytesRead: number } {`);
  lines.push('  const off = { v: offset ?? 0 };');
  lines.push('  if (off.v + 4 > bytes.length) throw new Error("unexpected end of input");');
  lines.push('  const dv = new DataView(bytes.buffer, bytes.byteOffset + off.v, 4);');
  lines.push('  const idx = dv.getUint32(0, true);');
  lines.push('  off.v += 4;');
  lines.push('  let value: ' + type.name + ';');
  lines.push('  switch (idx) {');
  sorted.forEach((v, i) => {
    lines.push(`    case ${i}: value = '${v}'; break;`);
  });
  lines.push('    default: throw new Error("invalid enum variant: " + idx);');
  lines.push('  }');
  lines.push('  return { value, bytesRead: off.v - (offset ?? 0) };');
  lines.push('}');
  lines.push('');
}

/**
 * Emit encode/decode for an OBJECT type.
 * Fields sorted alphabetically.
 */
function emitObjectCodec(lines, type) {
  const fields = [...(type.fields ?? [])].sort((a, b) => a.name < b.name ? -1 : a.name > b.name ? 1 : 0);

  // In-place encode — appends directly to a shared buf (avoids intermediate Uint8Array alloc)
  lines.push(`function _encode${type.name}(buf: number[], value: ${type.name}): void {`);

  for (const field of fields) {
    emitFieldEncode(lines, field, `value.${field.name}`);
  }

  lines.push('}');
  lines.push('');

  // Public encode — returns Uint8Array
  lines.push(`export function encode${type.name}(value: ${type.name}): Uint8Array {`);
  lines.push('  const buf: number[] = [];');
  lines.push(`  _encode${type.name}(buf, value);`);
  lines.push('  return new Uint8Array(buf);');
  lines.push('}');
  lines.push('');

  // decode function
  lines.push(`export function decode${type.name}(bytes: Uint8Array, offset?: number): { value: ${type.name}; bytesRead: number } {`);
  lines.push('  const off = { v: offset ?? 0 };');

  for (const field of fields) {
    emitFieldDecode(lines, field);
  }

  lines.push(`  return {`);
  lines.push(`    value: { ${fields.map((f) => f.name).join(', ')} },`);
  lines.push(`    bytesRead: off.v - (offset ?? 0),`);
  lines.push(`  };`);
  lines.push('}');
  lines.push('');
}

// ---------------------------------------------------------------------------
// Field-level encode helpers
// ---------------------------------------------------------------------------

function encodeCallForScalar(typeName, accessor) {
  switch (typeName) {
    case 'Boolean':
      return `_encodeBool(buf, ${accessor});`;
    case 'Int':
      return `_encodeI32(buf, ${accessor});`;
    case 'Float':
      return `_encodeF32(buf, ${accessor});`;
    case 'String':
    case 'ID':
      return `_encodeString(buf, ${accessor});`;
    default:
      // Nested object — encode in-place, no intermediate allocation
      return `_encode${typeName}(buf, ${accessor});`;
  }
}

function encodeInnerClosureForType(typeName) {
  switch (typeName) {
    case 'Boolean':
      return '_encodeBool';
    case 'Int':
      return '_encodeI32';
    case 'Float':
      return '_encodeF32';
    case 'String':
    case 'ID':
      return '_encodeString';
    default:
      return `(buf, v) => _encode${typeName}(buf, v)`;
  }
}

function emitFieldEncode(lines, field, accessor) {
  const { type, required, list } = field;

  if (list && required) {
    lines.push(`  _encodeList(buf, ${accessor}, ${encodeInnerClosureForType(type)});`);
  } else if (list && !required) {
    lines.push(`  _encodeOption(buf, ${accessor}, (buf, inner) => _encodeList(buf, inner, ${encodeInnerClosureForType(type)}));`);
  } else if (!required) {
    lines.push(`  _encodeOption(buf, ${accessor}, ${encodeInnerClosureForType(type)});`);
  } else {
    lines.push(`  ${encodeCallForScalar(type, accessor)}`);
  }
}

// ---------------------------------------------------------------------------
// Field-level decode helpers
// ---------------------------------------------------------------------------

function decodeCallForType(typeName) {
  switch (typeName) {
    case 'Boolean':
      return '_decodeBool';
    case 'Int':
      return '_decodeI32';
    case 'Float':
      return '_decodeF32';
    case 'String':
    case 'ID':
      return '_decodeString';
    default:
      return `(bytes, off) => { const _r = decode${typeName}(bytes, off.v); off.v += _r.bytesRead; return _r.value; }`;
  }
}

function decodeDirectCallForType(typeName, fieldName) {
  switch (typeName) {
    case 'Boolean':
      return `const ${fieldName} = _decodeBool(bytes, off);`;
    case 'Int':
      return `const ${fieldName} = _decodeI32(bytes, off);`;
    case 'Float':
      return `const ${fieldName} = _decodeF32(bytes, off);`;
    case 'String':
    case 'ID':
      return `const ${fieldName} = _decodeString(bytes, off);`;
    default: {
      // Nested object — use its decode function, advance offset
      return `const _${fieldName}Res = decode${typeName}(bytes, off.v); const ${fieldName} = _${fieldName}Res.value; off.v += _${fieldName}Res.bytesRead;`;
    }
  }
}

function emitFieldDecode(lines, field) {
  const { name, type, required, list } = field;

  if (list && required) {
    lines.push(`  const ${name} = _decodeList(bytes, off, ${decodeCallForType(type)});`);
  } else if (list && !required) {
    lines.push(`  const ${name} = _decodeOption(bytes, off, (bytes, off) => _decodeList(bytes, off, ${decodeCallForType(type)}));`);
  } else if (!required) {
    lines.push(`  const ${name} = _decodeOption(bytes, off, ${decodeCallForType(type)});`);
  } else {
    lines.push(`  ${decodeDirectCallForType(type, name)}`);
  }
}
