import { RustWriter } from './rust-writer.mjs';
import { parse, Kind } from 'graphql';
import { unwrapType } from './graphql-utils.mjs';

/**
 * Emit `wasm_abi_codec.generated.rs` containing deterministic encode/decode
 * functions for WASM ABI response types, plus binary envelope helpers.
 *
 * Wire format follows SPEC-0008 with extensions for ABI scalars:
 * - Hash32: raw 32 bytes (no length prefix — schema knows the size)
 * - Bytes: u32 LE length prefix + raw bytes
 * - U32: 4 bytes little-endian
 * - U64: 8 bytes little-endian
 *
 * Envelope:
 * - Success: [0x01] [encoded payload...]
 * - Error:   [0x00] [u32 LE code] [u32 LE msg_len] [UTF-8 msg...]
 *
 * @param {string} abiSdl - GraphQL SDL defining ABI response types
 * @returns {string | null}
 */
export function emitWasmAbiCodec(abiSdl) {
  const types = parseAbiTypes(abiSdl);
  if (types.length === 0) return null;

  const w = new RustWriter();

  w.writeLine('// Auto-generated by @wesley/generator-echo — DO NOT EDIT');
  w.writeLine('#![forbid(unsafe_code)]');
  w.writeLine();

  emitDecodeError(w);
  emitHelpers(w);

  for (const type of types) {
    emitStruct(w, type);
  }

  for (const type of types) {
    emitObjectImpl(w, type);
  }

  emitEnvelope(w);

  return w.toString();
}

// ---------------------------------------------------------------------------
// ABI SDL parser
// ---------------------------------------------------------------------------

function parseAbiTypes(sdl) {
  const doc = parse(sdl);
  const types = [];

  for (const def of doc.definitions) {
    if (def.kind === Kind.OBJECT_TYPE_DEFINITION) {
      const fields = (def.fields ?? []).map((f) => {
        const { typeName, required, list } = unwrapType(f.type);
        return { name: f.name.value, type: typeName, required, list };
      });
      types.push({ name: def.name.value, kind: 'OBJECT', fields });
    }
  }

  types.sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
  return types;
}


// ---------------------------------------------------------------------------
// DecodeError
// ---------------------------------------------------------------------------

function emitDecodeError(w) {
  w.writeLine('#[derive(Debug, Clone, PartialEq)]');
  w.writeLine('pub enum AbiDecodeError {');
  w.indent();
  w.writeLine('UnexpectedEof,');
  w.writeLine('InvalidOptionTag(u8),');
  w.writeLine('Utf8Error(std::string::FromUtf8Error),');
  w.writeLine('InvalidEnvelopeTag(u8),');
  w.writeLine('ErrorResponse { code: u32, message: String },');
  w.dedent();
  w.writeLine('}');
  w.writeLine();

  w.writeLine('impl std::fmt::Display for AbiDecodeError {');
  w.indent();
  w.writeLine("fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {");
  w.indent();
  w.writeLine('match self {');
  w.indent();
  w.writeLine('AbiDecodeError::UnexpectedEof => write!(f, "unexpected end of input"),');
  w.writeLine('AbiDecodeError::InvalidOptionTag(t) => write!(f, "invalid option tag: {}", t),');
  w.writeLine('AbiDecodeError::Utf8Error(e) => write!(f, "utf8 error: {}", e),');
  w.writeLine('AbiDecodeError::InvalidEnvelopeTag(t) => write!(f, "invalid envelope tag: {}", t),');
  w.writeLine('AbiDecodeError::ErrorResponse { code, message } => write!(f, "ABI error {}: {}", code, message),');
  w.dedent();
  w.writeLine('}');
  w.dedent();
  w.writeLine('}');
  w.dedent();
  w.writeLine('}');
  w.writeLine();
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function emitHelpers(w) {
  // --- Encode helpers ---

  w.writeLine('fn encode_bool(v: bool) -> u8 {');
  w.indent();
  w.writeLine('if v { 0x01 } else { 0x00 }');
  w.dedent();
  w.writeLine('}');
  w.writeLine();

  w.writeLine('fn encode_u32_le(v: u32) -> [u8; 4] {');
  w.indent();
  w.writeLine('v.to_le_bytes()');
  w.dedent();
  w.writeLine('}');
  w.writeLine();

  w.writeLine('fn encode_u64_le(v: u64) -> [u8; 8] {');
  w.indent();
  w.writeLine('v.to_le_bytes()');
  w.dedent();
  w.writeLine('}');
  w.writeLine();

  w.writeLine('fn encode_string(s: &str) -> Vec<u8> {');
  w.indent();
  w.writeLine('let bytes = s.as_bytes();');
  w.writeLine('let mut buf = Vec::with_capacity(4 + bytes.len());');
  w.writeLine('buf.extend_from_slice(&(bytes.len() as u32).to_le_bytes());');
  w.writeLine('buf.extend_from_slice(bytes);');
  w.writeLine('buf');
  w.dedent();
  w.writeLine('}');
  w.writeLine();

  w.writeLine('fn encode_bytes(v: &[u8]) -> Vec<u8> {');
  w.indent();
  w.writeLine('let mut buf = Vec::with_capacity(4 + v.len());');
  w.writeLine('buf.extend_from_slice(&(v.len() as u32).to_le_bytes());');
  w.writeLine('buf.extend_from_slice(v);');
  w.writeLine('buf');
  w.dedent();
  w.writeLine('}');
  w.writeLine();

  w.writeLine('fn encode_option<T, F>(v: &Option<T>, encode_inner: F) -> Vec<u8>');
  w.writeLine('where');
  w.indent();
  w.writeLine('F: Fn(&T) -> Vec<u8>,');
  w.dedent();
  w.writeLine('{');
  w.indent();
  w.writeLine('match v {');
  w.indent();
  w.writeLine('None => vec![0x00],');
  w.writeLine('Some(inner) => {');
  w.indent();
  w.writeLine('let mut buf = vec![0x01];');
  w.writeLine('buf.extend(encode_inner(inner));');
  w.writeLine('buf');
  w.dedent();
  w.writeLine('}');
  w.dedent();
  w.writeLine('}');
  w.dedent();
  w.writeLine('}');
  w.writeLine();

  w.writeLine('fn encode_list<T, F>(v: &[T], encode_inner: F) -> Vec<u8>');
  w.writeLine('where');
  w.indent();
  w.writeLine('F: Fn(&T) -> Vec<u8>,');
  w.dedent();
  w.writeLine('{');
  w.indent();
  w.writeLine('let mut buf = Vec::new();');
  w.writeLine('buf.extend_from_slice(&(v.len() as u32).to_le_bytes());');
  w.writeLine('for item in v {');
  w.indent();
  w.writeLine('buf.extend(encode_inner(item));');
  w.dedent();
  w.writeLine('}');
  w.writeLine('buf');
  w.dedent();
  w.writeLine('}');
  w.writeLine();

  // --- Decode helpers ---

  w.writeLine('fn decode_bool(bytes: &[u8], offset: &mut usize) -> Result<bool, AbiDecodeError> {');
  w.indent();
  w.writeLine('if *offset >= bytes.len() { return Err(AbiDecodeError::UnexpectedEof); }');
  w.writeLine('let v = bytes[*offset] != 0x00;');
  w.writeLine('*offset += 1;');
  w.writeLine('Ok(v)');
  w.dedent();
  w.writeLine('}');
  w.writeLine();

  w.writeLine('fn decode_u32_le(bytes: &[u8], offset: &mut usize) -> Result<u32, AbiDecodeError> {');
  w.indent();
  w.writeLine('if *offset + 4 > bytes.len() { return Err(AbiDecodeError::UnexpectedEof); }');
  w.writeLine('let v = u32::from_le_bytes([bytes[*offset], bytes[*offset + 1], bytes[*offset + 2], bytes[*offset + 3]]);');
  w.writeLine('*offset += 4;');
  w.writeLine('Ok(v)');
  w.dedent();
  w.writeLine('}');
  w.writeLine();

  w.writeLine('fn decode_u64_le(bytes: &[u8], offset: &mut usize) -> Result<u64, AbiDecodeError> {');
  w.indent();
  w.writeLine('if *offset + 8 > bytes.len() { return Err(AbiDecodeError::UnexpectedEof); }');
  w.writeLine('let v = u64::from_le_bytes([');
  w.indent();
  w.writeLine('bytes[*offset], bytes[*offset + 1], bytes[*offset + 2], bytes[*offset + 3],');
  w.writeLine('bytes[*offset + 4], bytes[*offset + 5], bytes[*offset + 6], bytes[*offset + 7],');
  w.dedent();
  w.writeLine(']);');
  w.writeLine('*offset += 8;');
  w.writeLine('Ok(v)');
  w.dedent();
  w.writeLine('}');
  w.writeLine();

  w.writeLine('fn decode_string(bytes: &[u8], offset: &mut usize) -> Result<String, AbiDecodeError> {');
  w.indent();
  w.writeLine('if *offset + 4 > bytes.len() { return Err(AbiDecodeError::UnexpectedEof); }');
  w.writeLine('let len = u32::from_le_bytes([bytes[*offset], bytes[*offset + 1], bytes[*offset + 2], bytes[*offset + 3]]) as usize;');
  w.writeLine('*offset += 4;');
  w.writeLine('if *offset + len > bytes.len() { return Err(AbiDecodeError::UnexpectedEof); }');
  w.writeLine('let v = String::from_utf8(bytes[*offset..*offset + len].to_vec()).map_err(AbiDecodeError::Utf8Error)?;');
  w.writeLine('*offset += len;');
  w.writeLine('Ok(v)');
  w.dedent();
  w.writeLine('}');
  w.writeLine();

  w.writeLine('fn decode_hash32(bytes: &[u8], offset: &mut usize) -> Result<[u8; 32], AbiDecodeError> {');
  w.indent();
  w.writeLine('if *offset + 32 > bytes.len() { return Err(AbiDecodeError::UnexpectedEof); }');
  w.writeLine('let mut v = [0u8; 32];');
  w.writeLine('v.copy_from_slice(&bytes[*offset..*offset + 32]);');
  w.writeLine('*offset += 32;');
  w.writeLine('Ok(v)');
  w.dedent();
  w.writeLine('}');
  w.writeLine();

  w.writeLine('fn decode_bytes(bytes: &[u8], offset: &mut usize) -> Result<Vec<u8>, AbiDecodeError> {');
  w.indent();
  w.writeLine('if *offset + 4 > bytes.len() { return Err(AbiDecodeError::UnexpectedEof); }');
  w.writeLine('let len = u32::from_le_bytes([bytes[*offset], bytes[*offset + 1], bytes[*offset + 2], bytes[*offset + 3]]) as usize;');
  w.writeLine('*offset += 4;');
  w.writeLine('if *offset + len > bytes.len() { return Err(AbiDecodeError::UnexpectedEof); }');
  w.writeLine('let v = bytes[*offset..*offset + len].to_vec();');
  w.writeLine('*offset += len;');
  w.writeLine('Ok(v)');
  w.dedent();
  w.writeLine('}');
  w.writeLine();

  w.writeLine('fn decode_option<T, F>(bytes: &[u8], offset: &mut usize, decode_inner: F) -> Result<Option<T>, AbiDecodeError>');
  w.writeLine('where');
  w.indent();
  w.writeLine('F: Fn(&[u8], &mut usize) -> Result<T, AbiDecodeError>,');
  w.dedent();
  w.writeLine('{');
  w.indent();
  w.writeLine('if *offset >= bytes.len() { return Err(AbiDecodeError::UnexpectedEof); }');
  w.writeLine('let tag = bytes[*offset];');
  w.writeLine('*offset += 1;');
  w.writeLine('match tag {');
  w.indent();
  w.writeLine('0x00 => Ok(None),');
  w.writeLine('0x01 => Ok(Some(decode_inner(bytes, offset)?)),');
  w.writeLine('t => Err(AbiDecodeError::InvalidOptionTag(t)),');
  w.dedent();
  w.writeLine('}');
  w.dedent();
  w.writeLine('}');
  w.writeLine();

  w.writeLine('fn decode_list<T, F>(bytes: &[u8], offset: &mut usize, decode_inner: F) -> Result<Vec<T>, AbiDecodeError>');
  w.writeLine('where');
  w.indent();
  w.writeLine('F: Fn(&[u8], &mut usize) -> Result<T, AbiDecodeError>,');
  w.dedent();
  w.writeLine('{');
  w.indent();
  w.writeLine('if *offset + 4 > bytes.len() { return Err(AbiDecodeError::UnexpectedEof); }');
  w.writeLine('let count = u32::from_le_bytes([bytes[*offset], bytes[*offset + 1], bytes[*offset + 2], bytes[*offset + 3]]) as usize;');
  w.writeLine('*offset += 4;');
  w.writeLine('let mut items = Vec::with_capacity(count);');
  w.writeLine('for _ in 0..count {');
  w.indent();
  w.writeLine('items.push(decode_inner(bytes, offset)?);');
  w.dedent();
  w.writeLine('}');
  w.writeLine('Ok(items)');
  w.dedent();
  w.writeLine('}');
  w.writeLine();
}

// ---------------------------------------------------------------------------
// Struct emission
// ---------------------------------------------------------------------------

function rustTypeFor(fieldType, required, list) {
  let rt;
  switch (fieldType) {
  case 'Boolean':
    rt = 'bool';
    break;
  case 'String':
    rt = 'String';
    break;
  case 'Hash32':
    rt = '[u8; 32]';
    break;
  case 'Bytes':
    rt = 'Vec<u8>';
    break;
  case 'U32':
    rt = 'u32';
    break;
  case 'U64':
    rt = 'u64';
    break;
  default:
    rt = fieldType;
    break;
  }
  if (list) rt = `Vec<${rt}>`;
  if (!required) rt = `Option<${rt}>`;
  return rt;
}

function emitStruct(w, type) {
  const fields = [...(type.fields ?? [])].sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
  w.writeLine('#[derive(Debug, Clone, PartialEq)]');
  w.writeLine(`pub struct ${type.name} {`);
  w.indent();
  for (const field of fields) {
    const snake = toSnakeCase(field.name);
    const rt = rustTypeFor(field.type, field.required, field.list);
    w.writeLine(`pub ${snake}: ${rt},`);
  }
  w.dedent();
  w.writeLine('}');
  w.writeLine();
}

// ---------------------------------------------------------------------------
// Encode/decode impl emission
// ---------------------------------------------------------------------------

function encodeExprForScalar(typeName, accessor) {
  switch (typeName) {
  case 'Boolean':
    return `buf.push(encode_bool(${accessor}));`;
  case 'U32':
    return `buf.extend_from_slice(&encode_u32_le(${accessor}));`;
  case 'U64':
    return `buf.extend_from_slice(&encode_u64_le(${accessor}));`;
  case 'String':
    return `buf.extend(encode_string(&${accessor}));`;
  case 'Hash32':
    return `buf.extend_from_slice(&${accessor});`;
  case 'Bytes':
    return `buf.extend(encode_bytes(&${accessor}));`;
  default:
    return `buf.extend(${accessor}.encode_raw_le());`;
  }
}

function encodeClosureForType(typeName) {
  switch (typeName) {
  case 'Boolean':
    return '|v| vec![encode_bool(*v)]';
  case 'U32':
    return '|v| encode_u32_le(*v).to_vec()';
  case 'U64':
    return '|v| encode_u64_le(*v).to_vec()';
  case 'String':
    return '|v| encode_string(v)';
  case 'Hash32':
    return '|v| v.to_vec()';
  case 'Bytes':
    return '|v| encode_bytes(v)';
  default:
    return '|v| v.encode_raw_le()';
  }
}

function decodeCallForType(typeName, offsetExpr = '&mut offset') {
  switch (typeName) {
  case 'Boolean':
    return `decode_bool(bytes, ${offsetExpr})?`;
  case 'U32':
    return `decode_u32_le(bytes, ${offsetExpr})?`;
  case 'U64':
    return `decode_u64_le(bytes, ${offsetExpr})?`;
  case 'String':
    return `decode_string(bytes, ${offsetExpr})?`;
  case 'Hash32':
    return `decode_hash32(bytes, ${offsetExpr})?`;
  case 'Bytes':
    return `decode_bytes(bytes, ${offsetExpr})?`;
  default:
    return `${typeName}::decode_raw_le_at(bytes, ${offsetExpr})?`;
  }
}

function decodeClosureForType(typeName) {
  switch (typeName) {
  case 'Boolean':
    return 'decode_bool';
  case 'U32':
    return 'decode_u32_le';
  case 'U64':
    return 'decode_u64_le';
  case 'String':
    return 'decode_string';
  case 'Hash32':
    return 'decode_hash32';
  case 'Bytes':
    return 'decode_bytes';
  default:
    return `${typeName}::decode_raw_le_at`;
  }
}

function emitFieldEncode(w, field, snake) {
  const { type, required, list } = field;

  if (list && required) {
    w.writeLine(`buf.extend(encode_list(&self.${snake}, ${encodeClosureForType(type)}));`);
  } else if (list && !required) {
    w.writeLine(`buf.extend(encode_option(&self.${snake}, |inner| encode_list(inner, ${encodeClosureForType(type)})));`);
  } else if (!required) {
    w.writeLine(`buf.extend(encode_option(&self.${snake}, ${encodeClosureForType(type)}));`);
  } else {
    w.writeLine(encodeExprForScalar(type, `self.${snake}`));
  }
}

function emitFieldDecode(w, field, snake, offsetExpr = '&mut offset') {
  const { type, required, list } = field;

  if (list && required) {
    w.writeLine(`let ${snake} = decode_list(bytes, ${offsetExpr}, ${decodeClosureForType(type)})?;`);
  } else if (list && !required) {
    w.writeLine(`let ${snake} = decode_option(bytes, ${offsetExpr}, |b, o| decode_list(b, o, ${decodeClosureForType(type)}))?;`);
  } else if (!required) {
    w.writeLine(`let ${snake} = decode_option(bytes, ${offsetExpr}, ${decodeClosureForType(type)})?;`);
  } else {
    w.writeLine(`let ${snake} = ${decodeCallForType(type, offsetExpr)};`);
  }
}

function emitObjectImpl(w, type) {
  const fields = [...(type.fields ?? [])].sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));

  w.writeLine(`impl ${type.name} {`);
  w.indent();

  // encode
  w.writeLine('pub fn encode_raw_le(&self) -> Vec<u8> {');
  w.indent();
  w.writeLine('let mut buf = Vec::new();');
  for (const field of fields) {
    const snake = toSnakeCase(field.name);
    emitFieldEncode(w, field, snake);
  }
  w.writeLine('buf');
  w.dedent();
  w.writeLine('}');
  w.writeLine();

  // decode (standalone)
  w.writeLine('pub fn decode_raw_le(bytes: &[u8]) -> Result<Self, AbiDecodeError> {');
  w.indent();
  w.writeLine('let mut offset = 0;');
  for (const field of fields) {
    const snake = toSnakeCase(field.name);
    emitFieldDecode(w, field, snake);
  }
  w.writeLine('Ok(Self {');
  w.indent();
  for (const field of fields) {
    const snake = toSnakeCase(field.name);
    w.writeLine(`${snake},`);
  }
  w.dedent();
  w.writeLine('})');
  w.dedent();
  w.writeLine('}');
  w.writeLine();

  // decode_raw_le_at (with shared offset for nested structs)
  w.writeLine('pub fn decode_raw_le_at(bytes: &[u8], offset: &mut usize) -> Result<Self, AbiDecodeError> {');
  w.indent();
  for (const field of fields) {
    const snake = toSnakeCase(field.name);
    emitFieldDecode(w, field, snake, 'offset');
  }
  w.writeLine('Ok(Self {');
  w.indent();
  for (const field of fields) {
    const snake = toSnakeCase(field.name);
    w.writeLine(`${snake},`);
  }
  w.dedent();
  w.writeLine('})');
  w.dedent();
  w.writeLine('}');

  w.dedent();
  w.writeLine('}');
  w.writeLine();
}

// ---------------------------------------------------------------------------
// Envelope emission
// ---------------------------------------------------------------------------

function emitEnvelope(w) {
  w.writeLine('/// Wrap an already-encoded success payload in the ABI envelope.');
  w.writeLine('/// Format: [0x01] [payload bytes...]');
  w.writeLine('pub fn encode_ok(payload: &[u8]) -> Vec<u8> {');
  w.indent();
  w.writeLine('let mut buf = Vec::with_capacity(1 + payload.len());');
  w.writeLine('buf.push(0x01);');
  w.writeLine('buf.extend_from_slice(payload);');
  w.writeLine('buf');
  w.dedent();
  w.writeLine('}');
  w.writeLine();

  w.writeLine('/// Encode an error response in the ABI envelope.');
  w.writeLine('/// Format: [0x00] [u32 LE code] [u32 LE msg_len] [UTF-8 msg...]');
  w.writeLine('pub fn encode_err(code: u32, message: &str) -> Vec<u8> {');
  w.indent();
  w.writeLine('let msg_bytes = message.as_bytes();');
  w.writeLine('let mut buf = Vec::with_capacity(1 + 4 + 4 + msg_bytes.len());');
  w.writeLine('buf.push(0x00);');
  w.writeLine('buf.extend_from_slice(&code.to_le_bytes());');
  w.writeLine('buf.extend_from_slice(&(msg_bytes.len() as u32).to_le_bytes());');
  w.writeLine('buf.extend_from_slice(msg_bytes);');
  w.writeLine('buf');
  w.dedent();
  w.writeLine('}');
  w.writeLine();

  w.writeLine('/// Decode the ABI envelope tag byte.');
  w.writeLine('/// Returns Ok(payload_slice) for success (0x01) or Err(AbiDecodeError::ErrorResponse) for error (0x00).');
  w.writeLine("pub fn decode_envelope(bytes: &[u8]) -> Result<&[u8], AbiDecodeError> {");
  w.indent();
  w.writeLine('if bytes.is_empty() { return Err(AbiDecodeError::UnexpectedEof); }');
  w.writeLine('match bytes[0] {');
  w.indent();
  w.writeLine('0x01 => Ok(&bytes[1..]),');
  w.writeLine('0x00 => {');
  w.indent();
  w.writeLine('let mut offset = 1;');
  w.writeLine('let code = decode_u32_le(bytes, &mut offset)?;');
  w.writeLine('let message = decode_string(bytes, &mut offset)?;');
  w.writeLine('Err(AbiDecodeError::ErrorResponse { code, message })');
  w.dedent();
  w.writeLine('}');
  w.writeLine('t => Err(AbiDecodeError::InvalidEnvelopeTag(t)),');
  w.dedent();
  w.writeLine('}');
  w.dedent();
  w.writeLine('}');
  w.writeLine();
}

// ---------------------------------------------------------------------------
// Utilities
// ---------------------------------------------------------------------------

/**
 * Convert a camelCase name to snake_case.
 * @param {string} name
 * @returns {string}
 */
function toSnakeCase(name) {
  return name
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1_$2')
    .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
    .toLowerCase();
}
