import { RustWriter } from './rust-writer.mjs';

/**
 * Emit Rust `impl JoinFn` blocks for every OBJECT type that has at least one
 * field annotated with `@wes_join`.
 *
 * Returns `null` when the IR contains no join-annotated types (no file needed).
 *
 * @param {{ types: Array<{ name: string, kind: string, has_join: boolean, fields?: Array<{ name: string, join: { strategy: string } | null }> }> }} ir
 * @returns {string | null}
 */
export function emitJoinImpls(ir) {
  const joinTypes = (ir.types ?? []).filter(
    (t) => t.kind === 'OBJECT' && t.has_join === true,
  );

  if (joinTypes.length === 0) return null;

  const w = new RustWriter();

  w.writeLine('// Auto-generated by @wesley/generator-echo — DO NOT EDIT');
  w.writeLine('use echo_lattice::{JoinFn, lattice};');
  w.writeLine();

  for (const type of joinTypes) {
    w.writeLine(`impl JoinFn for ${type.name} {`);
    w.indent();
    w.writeLine('fn join(&self, other: &Self) -> Self {');
    w.indent();
    w.writeLine('Self {');
    w.indent();

    for (const field of type.fields) {
      const name = toSnakeCase(field.name);
      if (field.join === null) {
        w.writeLine(`${name}: self.${name}.clone(),`);
      } else {
        const expr = joinExpr(field.join.strategy, name);
        w.writeLine(`${name}: ${expr},`);
      }
    }

    w.dedent();
    w.writeLine('}');
    w.dedent();
    w.writeLine('}');
    w.dedent();
    w.writeLine('}');
    w.writeLine();
  }

  return w.toString();
}

/**
 * Map a join strategy to its Rust lattice call expression.
 *
 * @param {string} strategy - "union" | "max" | "lww"
 * @param {string} field    - snake_case field name
 * @returns {string}
 */
function joinExpr(strategy, field) {
  switch (strategy) {
    case 'union':
      return `lattice::union(&self.${field}, &other.${field})`;
    case 'max':
      return `lattice::max(self.${field}, other.${field})`;
    case 'lww':
      return `lattice::lww(self.${field}.clone(), other.${field}.clone())`;
    default:
      throw new Error(`Unknown join strategy: ${strategy}`);
  }
}

/**
 * Convert a camelCase name to snake_case.
 * @param {string} name
 * @returns {string}
 */
function toSnakeCase(name) {
  return name.replace(/([A-Z])/g, '_$1').toLowerCase().replace(/^_/, '');
}
