function pascalCase(value) {
  return String(value)
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .replace(/[^A-Za-z0-9]+/g, ' ')
    .trim()
    .split(/\s+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

function snakeCase(value) {
  return String(value)
    .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
    .replace(/[^A-Za-z0-9]+/g, '_')
    .replace(/_{2,}/g, '_')
    .replace(/^_+|_+$/g, '')
    .toLowerCase();
}

function rustType(typeName) {
  switch (typeName) {
    case 'String':
    case 'ID':
      return 'String';
    case 'Int':
      return 'i64';
    case 'Float':
      return 'f64';
    case 'Boolean':
      return 'bool';
    default:
      return typeName;
  }
}

function capabilityTraitName(mode, resource) {
  return `${pascalCase(mode)}${pascalCase(resource)}`;
}

function capabilityMethodName(mode, resource) {
  return `${mode}_${snakeCase(resource)}`;
}

function opTraitStem(opName) {
  return pascalCase(opName);
}

function emitArgsStruct(op) {
  const argsName = `${opTraitStem(op.name)}Args`;
  if (!op.args?.length) {
    return [
      '#[derive(Debug, Clone, PartialEq, Eq)]',
      `pub struct ${argsName};`,
      ''
    ].join('\n');
  }

  const lines = [
    '#[derive(Debug, Clone, PartialEq)]',
    `pub struct ${argsName} {`
  ];
  for (const arg of op.args) {
    const argType = rustType(arg.type);
    const baseType = arg.list ? `Vec<${argType}>` : argType;
    const fullType = arg.required ? baseType : `Option<${baseType}>`;
    lines.push(`    pub ${snakeCase(arg.name)}: ${fullType},`);
  }
  lines.push('}');
  lines.push('');
  return lines.join('\n');
}

function emitCapabilityTrait(mode, resource) {
  const traitName = capabilityTraitName(mode, resource);
  const methodName = capabilityMethodName(mode, resource);
  const ty = rustType(resource);

  if (mode === 'read') {
    return [
      `pub trait ${traitName} {`,
      `    fn ${methodName}(&self) -> &${ty};`,
      '}',
      ''
    ].join('\n');
  }

  if (mode === 'delete') {
    return [
      `pub trait ${traitName} {`,
      `    fn ${methodName}(&mut self);`,
      '}',
      ''
    ].join('\n');
  }

  return [
    `pub trait ${traitName} {`,
    `    fn ${methodName}(&mut self, value: ${ty});`,
    '}',
    ''
  ].join('\n');
}

function emitContextTrait(op) {
  const stem = opTraitStem(op.name);
  const bounds = [];
  for (const resource of op.footprint?.reads ?? []) bounds.push(capabilityTraitName('read', resource));
  for (const resource of op.footprint?.writes ?? []) bounds.push(capabilityTraitName('write', resource));
  for (const resource of op.footprint?.creates ?? []) bounds.push(capabilityTraitName('create', resource));
  for (const resource of op.footprint?.deletes ?? []) bounds.push(capabilityTraitName('delete', resource));
  const uniqueBounds = [...new Set(bounds)];
  const boundList = uniqueBounds.join(' + ');

  return [
    uniqueBounds.length
      ? `pub trait ${stem}Context: ${boundList} {}`
      : `pub trait ${stem}Context {}`,
    uniqueBounds.length
      ? `impl<T> ${stem}Context for T where T: ${boundList} {}`
      : `impl<T> ${stem}Context for T {}`,
    ''
  ].join('\n');
}

function emitRewriteTrait(op) {
  const stem = opTraitStem(op.name);
  const argsName = `${stem}Args`;
  const resultType = rustType(op.result_type);

  return [
    `pub trait ${stem}Rewrite {`,
    '    type Error;',
    '',
    `    fn apply<C>(&self, ctx: &mut C, args: ${argsName}) -> Result<${resultType}, Self::Error>`,
    `    where C: ${stem}Context;`,
    '}',
    ''
  ].join('\n');
}

export function emitRewriteApi(ir) {
  const mutationOps = (ir.ops ?? []).filter((op) => op.kind === 'MUTATION' && op.footprint);
  if (!mutationOps.length) return null;

  const capabilityKeys = new Map();
  for (const op of mutationOps) {
    for (const resource of op.footprint.reads ?? []) capabilityKeys.set(`read:${resource}`, ['read', resource]);
    for (const resource of op.footprint.writes ?? []) capabilityKeys.set(`write:${resource}`, ['write', resource]);
    for (const resource of op.footprint.creates ?? []) capabilityKeys.set(`create:${resource}`, ['create', resource]);
    for (const resource of op.footprint.deletes ?? []) capabilityKeys.set(`delete:${resource}`, ['delete', resource]);
  }

  const lines = [
    '// Generated by @wesley/generator-echo. Do not edit.',
    '// Proof-slice rewrite API: capability-bounded Rust authoring surface.',
    ''
  ];

  for (const [mode, resource] of capabilityKeys.values()) {
    lines.push(emitCapabilityTrait(mode, resource));
  }

  for (const op of mutationOps) {
    lines.push(emitArgsStruct(op));
    lines.push(emitContextTrait(op));
    lines.push(emitRewriteTrait(op));
  }

  return lines.join('\n');
}
