/**
 * Emit a TypeScript `client.generated.ts` providing:
 * - Handshake constants for integration gates
 * - Typed dispatch (mutation) and query APIs
 * - Canonical pump loop for view-op envelope parsing and routing
 *
 * The generated file is self-contained — all op metadata is embedded
 * directly so it compiles in strict TypeScript mode with no manual edits.
 *
 * @param {{ ops?: Array<{ kind: string, name: string, op_id: number, args: Array<{ name: string, type: string, required: boolean, list: boolean }>, result_type: string }>, schema_sha256?: string, codec_id?: string, registry_version?: number }} ir
 * @returns {string}
 */
export function emitClient(ir) {
  const lines = [];
  const ops = ir.ops ?? [];
  const contractVersion = ir.contract_version ?? '1.0.0';
  const schemaSha = ir.schema_sha256 ?? '';
  const codecId = ir.codec_id ?? 'cbor-canon-v1';
  const registryVersion = ir.registry_version ?? 1;

  lines.push('// AUTO-GENERATED by @wesley/generator-echo — DO NOT EDIT.');
  lines.push('');

  // --- Handshake constants ---
  lines.push('/** Registry handshake constants for integration gates. */');
  lines.push('export const HANDSHAKE = {');
  lines.push(`  contract_version: ${JSON.stringify(contractVersion)},`);
  lines.push(`  schema_sha256: ${JSON.stringify(schemaSha)},`);
  lines.push(`  codec_id: ${JSON.stringify(codecId)},`);
  lines.push(`  registry_version: ${registryVersion},`);
  lines.push('} as const;');
  lines.push('');

  // --- Interfaces ---
  lines.push('export interface RegistryInfo {');
  lines.push('  schema_sha256: string;');
  lines.push('  codec_id: string;');
  lines.push('  registry_version: number;');
  lines.push('}');
  lines.push('');

  lines.push('export interface EchoWasm {');
  lines.push('  encode_command(op_id: number, payload: Uint8Array): Uint8Array;');
  lines.push('  encode_query_vars(query_id: number, payload: Uint8Array): Uint8Array;');
  lines.push('  execute_query(query_id: number, vars_bytes: Uint8Array): Uint8Array;');
  lines.push('  get_registry_info(): Uint8Array;');
  lines.push('}');
  lines.push('');

  lines.push('export interface ViewOpEnvelope {');
  lines.push('  opId: number;');
  lines.push('  payload: Uint8Array;');
  lines.push('}');
  lines.push('');

  lines.push('export interface ViewOpHandler {');
  lines.push('  (payload: Uint8Array): void;');
  lines.push('}');
  lines.push('');

  lines.push('export interface DiagnosticsChannel {');
  lines.push('  unknownOp?(opId: number, rawPayload: Uint8Array): void;');
  lines.push('  decodeError?(error: Error, rawPayload: Uint8Array): void;');
  lines.push('}');
  lines.push('');

  // --- Embedded op index ---
  lines.push('/** Op metadata indexed by name. */');
  lines.push('const OP_INDEX = new Map<string, { kind: string; op_id: number; result_type: string }>([');
  for (const op of ops) {
    lines.push(`  [${JSON.stringify(op.name)}, { kind: ${JSON.stringify(op.kind)}, op_id: ${op.op_id}, result_type: ${JSON.stringify(op.result_type)} }],`);
  }
  lines.push(']);');
  lines.push('');

  lines.push('/** Reverse lookup: op_id → op name. */');
  lines.push('const OP_BY_ID = new Map<number, string>([');
  for (const op of ops) {
    lines.push(`  [${op.op_id}, ${JSON.stringify(op.name)}],`);
  }
  lines.push(']);');
  lines.push('');

  // --- WesleyClient ---
  lines.push('/**');
  lines.push(' * Generated runtime client for Echo WASM dispatch and query.');
  lines.push(' *');
  lines.push(' * Usage:');
  lines.push(' *   const client = new WesleyClient(wasmInstance);');
  lines.push(' *   const cmd = client.dispatch("setTheme", encodedArgs);');
  lines.push(' *   const result = client.query("appState", new Uint8Array(0));');
  lines.push(' */');
  lines.push('export class WesleyClient {');
  lines.push('  private readonly wasm: EchoWasm;');
  lines.push('');
  lines.push('  constructor(wasm: EchoWasm) {');
  lines.push('    if (!wasm || typeof wasm.encode_command !== "function" || typeof wasm.execute_query !== "function") {');
  lines.push('      throw new Error("WesleyClient: wasm instance must implement EchoWasm interface (encode_command, encode_query_vars, execute_query, get_registry_info)");');
  lines.push('    }');
  lines.push('    this.wasm = wasm;');
  lines.push('  }');
  lines.push('');

  lines.push('  /** Verify remote registry info matches generated contract. */');
  lines.push('  verifyRegistry(info: RegistryInfo): void {');
  lines.push('    if (info.schema_sha256 !== HANDSHAKE.schema_sha256) {');
  lines.push('      throw new Error(`Schema hash mismatch: expected ${HANDSHAKE.schema_sha256}, got ${info.schema_sha256}`);');
  lines.push('    }');
  lines.push('    if (info.codec_id !== HANDSHAKE.codec_id) {');
  lines.push('      throw new Error(`Codec mismatch: expected ${HANDSHAKE.codec_id}, got ${info.codec_id}`);');
  lines.push('    }');
  lines.push('    if (info.registry_version !== HANDSHAKE.registry_version) {');
  lines.push('      throw new Error(`Registry version mismatch: expected ${HANDSHAKE.registry_version}, got ${info.registry_version}`);');
  lines.push('    }');
  lines.push('  }');
  lines.push('');

  lines.push('  /**');
  lines.push('   * Dispatch a mutation intent.');
  lines.push('   * @param opName — Mutation name (must match a declared MUTATION op).');
  lines.push('   * @param payload — Pre-encoded argument bytes.');
  lines.push('   * @returns Encoded command bytes ready for transport.');
  lines.push('   */');
  lines.push('  dispatch(opName: string, payload: Uint8Array): Uint8Array {');
  lines.push('    const op = OP_INDEX.get(opName);');
  lines.push('    if (!op) throw new Error(`Unknown operation: ${opName}`);');
  lines.push('    if (op.kind !== "MUTATION") throw new Error(`${opName} is a ${op.kind}, not a MUTATION — use query() instead`);');
  lines.push('    return this.wasm.encode_command(op.op_id, payload);');
  lines.push('  }');
  lines.push('');

  lines.push('  /**');
  lines.push('   * Execute a query.');
  lines.push('   * @param queryName — Query name (must match a declared QUERY op).');
  lines.push('   * @param vars — Pre-encoded query variable bytes.');
  lines.push('   * @returns Raw result bytes from WASM execution.');
  lines.push('   */');
  lines.push('  query(queryName: string, vars: Uint8Array): Uint8Array {');
  lines.push('    const op = OP_INDEX.get(queryName);');
  lines.push('    if (!op) throw new Error(`Unknown query: ${queryName}`);');
  lines.push('    if (op.kind !== "QUERY") throw new Error(`${queryName} is a ${op.kind}, not a QUERY — use dispatch() instead`);');
  lines.push('    return this.wasm.execute_query(op.op_id, vars);');
  lines.push('  }');
  lines.push('');

  lines.push('  /** Look up an op_id by name. Throws if unknown. */');
  lines.push('  findOpId(name: string): number {');
  lines.push('    const op = OP_INDEX.get(name);');
  lines.push('    if (!op) throw new Error(`Unknown op name: ${name}`);');
  lines.push('    return op.op_id;');
  lines.push('  }');
  lines.push('');

  lines.push('  /** Look up an op name by id. Returns undefined if unknown. */');
  lines.push('  resolveOpName(opId: number): string | undefined {');
  lines.push('    return OP_BY_ID.get(opId);');
  lines.push('  }');

  lines.push('}');
  lines.push('');

  // --- View-op envelope parsing ---
  lines.push('/**');
  lines.push(' * Parse a binary buffer into view-op envelopes.');
  lines.push(' * Envelope format: [op_id:u32le][payload_len:u32le][payload:bytes]');
  lines.push(' */');
  lines.push('export function parseViewOps(buffer: Uint8Array): ViewOpEnvelope[] {');
  lines.push('  const envelopes: ViewOpEnvelope[] = [];');
  lines.push('  let offset = 0;');
  lines.push('  while (offset + 8 <= buffer.length) {');
  lines.push('    const dv = new DataView(buffer.buffer, buffer.byteOffset + offset, 8);');
  lines.push('    const opId = dv.getUint32(0, true);');
  lines.push('    const payloadLen = dv.getUint32(4, true);');
  lines.push('    offset += 8;');
  lines.push('    if (offset + payloadLen > buffer.length) {');
  lines.push('      throw new Error(`Truncated view-op payload at offset ${offset - 8}: expected ${payloadLen} bytes, ${buffer.length - offset} available`);');
  lines.push('    }');
  lines.push('    envelopes.push({ opId, payload: buffer.subarray(offset, offset + payloadLen) });');
  lines.push('    offset += payloadLen;');
  lines.push('  }');
  lines.push('  if (offset !== buffer.length) {');
  lines.push('    throw new Error(`Trailing ${buffer.length - offset} byte(s) after last view-op envelope`);');
  lines.push('  }');
  lines.push('  return envelopes;');
  lines.push('}');
  lines.push('');

  // --- Pump ---
  lines.push('/**');
  lines.push(' * Create a canonical pump loop that decodes view-op envelopes');
  lines.push(' * and routes them to registered handlers by op_id.');
  lines.push(' *');
  lines.push(' * Unknown op IDs are surfaced to the diagnostics channel with raw payload.');
  lines.push(' * Empty buffers return cleanly without emitting callbacks.');
  lines.push(' *');
  lines.push(' * @param handlers — Map of op_id → handler function.');
  lines.push(' * @param diagnostics — Optional channel for unknown ops and decode errors.');
  lines.push(' * @returns A pump function that processes a view-op buffer.');
  lines.push(' */');
  lines.push('export function createPump(');
  lines.push('  handlers: Map<number, ViewOpHandler>,');
  lines.push('  diagnostics?: DiagnosticsChannel,');
  lines.push('): (buffer: Uint8Array) => void {');
  lines.push('  return function pump(buffer: Uint8Array): void {');
  lines.push('    if (buffer.length === 0) return;');
  lines.push('    const envelopes = parseViewOps(buffer);');
  lines.push('    for (const { opId, payload } of envelopes) {');
  lines.push('      const handler = handlers.get(opId);');
  lines.push('      if (handler) {');
  lines.push('        try {');
  lines.push('          handler(payload);');
  lines.push('        } catch (err) {');
  lines.push('          if (diagnostics?.decodeError) {');
  lines.push('            diagnostics.decodeError(err instanceof Error ? err : new Error(String(err)), payload);');
  lines.push('          } else {');
  lines.push('            throw err;');
  lines.push('          }');
  lines.push('        }');
  lines.push('      } else if (diagnostics?.unknownOp) {');
  lines.push('        diagnostics.unknownOp(opId, payload);');
  lines.push('      }');
  lines.push('    }');
  lines.push('  };');
  lines.push('}');

  return lines.join('\n');
}
