import { RustWriter } from './rust-writer.mjs';

/**
 * Emit a Rust `raw_le_codec.generated.rs` file containing deterministic
 * encode/decode functions for every OBJECT and ENUM type in the IR.
 *
 * Layout follows SPEC-0008:
 * - Fields encoded in alphabetical order
 * - Little-endian byte order for all numerics
 * - Collision-free Option<T> prefix (0x00 = None, 0x01 = Some)
 * - NaN canonicalization for f32
 *
 * Returns `null` when the IR contains no OBJECT or ENUM types.
 *
 * @param {{ types: Array<{ name: string, kind: string, fields?: Array<{ name: string, type: string, required: boolean, list: boolean }>, values?: string[] }> }} ir
 * @returns {string | null}
 */
export function emitRawLeCodec(ir) {
  const encodableTypes = (ir.types ?? []).filter(
    (t) => t.kind === 'OBJECT' || t.kind === 'ENUM',
  );

  if (encodableTypes.length === 0) return null;

  const w = new RustWriter();

  w.writeLine('// Auto-generated by @wesley/generator-echo — DO NOT EDIT');
  w.writeLine('#![forbid(unsafe_code)]');
  w.writeLine();

  // DecodeError
  emitDecodeError(w);

  // Shared helpers
  emitHelpers(w);

  // Per-type impls
  for (const type of encodableTypes) {
    if (type.kind === 'ENUM') {
      emitEnumCodec(w, type);
    } else if (type.kind === 'OBJECT') {
      emitObjectCodec(w, type);
    }
  }

  return w.toString();
}

/**
 * Emit the `DecodeError` enum.
 */
function emitDecodeError(w) {
  w.writeLine('#[derive(Debug, Clone, PartialEq)]');
  w.writeLine('pub enum DecodeError {');
  w.indent();
  w.writeLine('UnexpectedEof,');
  w.writeLine('InvalidOptionTag(u8),');
  w.writeLine('InvalidEnumVariant(u32),');
  w.writeLine('Utf8Error(std::string::FromUtf8Error),');
  w.dedent();
  w.writeLine('}');
  w.writeLine();

  w.writeLine('impl std::fmt::Display for DecodeError {');
  w.indent();
  w.writeLine('fn fmt(&self, f: &mut std::fmt::Formatter<\'_>) -> std::fmt::Result {');
  w.indent();
  w.writeLine('match self {');
  w.indent();
  w.writeLine('DecodeError::UnexpectedEof => write!(f, "unexpected end of input"),');
  w.writeLine('DecodeError::InvalidOptionTag(t) => write!(f, "invalid option tag: {}", t),');
  w.writeLine('DecodeError::InvalidEnumVariant(v) => write!(f, "invalid enum variant: {}", v),');
  w.writeLine('DecodeError::Utf8Error(e) => write!(f, "utf8 error: {}", e),');
  w.dedent();
  w.writeLine('}');
  w.dedent();
  w.writeLine('}');
  w.dedent();
  w.writeLine('}');
  w.writeLine();
}

/**
 * Emit shared helper functions for encoding/decoding primitives.
 */
function emitHelpers(w) {
  // encode helpers
  w.writeLine('fn encode_bool(v: bool) -> u8 {');
  w.indent();
  w.writeLine('if v { 0x01 } else { 0x00 }');
  w.dedent();
  w.writeLine('}');
  w.writeLine();

  w.writeLine('fn encode_i32_le(v: i32) -> [u8; 4] {');
  w.indent();
  w.writeLine('v.to_le_bytes()');
  w.dedent();
  w.writeLine('}');
  w.writeLine();

  w.writeLine('fn encode_f32_le(v: f32) -> [u8; 4] {');
  w.indent();
  w.writeLine('let v = if v.is_nan() { f32::from_bits(0x7FC00000) } else { v };');
  w.writeLine('v.to_le_bytes()');
  w.dedent();
  w.writeLine('}');
  w.writeLine();

  w.writeLine('fn encode_string(s: &str) -> Vec<u8> {');
  w.indent();
  w.writeLine('let bytes = s.as_bytes();');
  w.writeLine('let mut buf = Vec::with_capacity(4 + bytes.len());');
  w.writeLine('buf.extend_from_slice(&(bytes.len() as u32).to_le_bytes());');
  w.writeLine('buf.extend_from_slice(bytes);');
  w.writeLine('buf');
  w.dedent();
  w.writeLine('}');
  w.writeLine();

  w.writeLine('fn encode_option<T, F>(v: &Option<T>, encode_inner: F) -> Vec<u8>');
  w.writeLine('where');
  w.indent();
  w.writeLine('F: Fn(&T) -> Vec<u8>,');
  w.dedent();
  w.writeLine('{');
  w.indent();
  w.writeLine('match v {');
  w.indent();
  w.writeLine('None => vec![0x00],');
  w.writeLine('Some(inner) => {');
  w.indent();
  w.writeLine('let mut buf = vec![0x01];');
  w.writeLine('buf.extend(encode_inner(inner));');
  w.writeLine('buf');
  w.dedent();
  w.writeLine('}');
  w.dedent();
  w.writeLine('}');
  w.dedent();
  w.writeLine('}');
  w.writeLine();

  w.writeLine('fn encode_list<T, F>(v: &[T], encode_inner: F) -> Vec<u8>');
  w.writeLine('where');
  w.indent();
  w.writeLine('F: Fn(&T) -> Vec<u8>,');
  w.dedent();
  w.writeLine('{');
  w.indent();
  w.writeLine('let mut buf = Vec::new();');
  w.writeLine('buf.extend_from_slice(&(v.len() as u32).to_le_bytes());');
  w.writeLine('for item in v {');
  w.indent();
  w.writeLine('buf.extend(encode_inner(item));');
  w.dedent();
  w.writeLine('}');
  w.writeLine('buf');
  w.dedent();
  w.writeLine('}');
  w.writeLine();

  // decode helpers
  w.writeLine('fn decode_bool(bytes: &[u8], offset: &mut usize) -> Result<bool, DecodeError> {');
  w.indent();
  w.writeLine('if *offset >= bytes.len() { return Err(DecodeError::UnexpectedEof); }');
  w.writeLine('let v = bytes[*offset] != 0x00;');
  w.writeLine('*offset += 1;');
  w.writeLine('Ok(v)');
  w.dedent();
  w.writeLine('}');
  w.writeLine();

  w.writeLine('fn decode_i32_le(bytes: &[u8], offset: &mut usize) -> Result<i32, DecodeError> {');
  w.indent();
  w.writeLine('if *offset + 4 > bytes.len() { return Err(DecodeError::UnexpectedEof); }');
  w.writeLine('let v = i32::from_le_bytes([bytes[*offset], bytes[*offset + 1], bytes[*offset + 2], bytes[*offset + 3]]);');
  w.writeLine('*offset += 4;');
  w.writeLine('Ok(v)');
  w.dedent();
  w.writeLine('}');
  w.writeLine();

  w.writeLine('fn decode_f32_le(bytes: &[u8], offset: &mut usize) -> Result<f32, DecodeError> {');
  w.indent();
  w.writeLine('if *offset + 4 > bytes.len() { return Err(DecodeError::UnexpectedEof); }');
  w.writeLine('let v = f32::from_le_bytes([bytes[*offset], bytes[*offset + 1], bytes[*offset + 2], bytes[*offset + 3]]);');
  w.writeLine('*offset += 4;');
  w.writeLine('Ok(v)');
  w.dedent();
  w.writeLine('}');
  w.writeLine();

  w.writeLine('fn decode_string(bytes: &[u8], offset: &mut usize) -> Result<String, DecodeError> {');
  w.indent();
  w.writeLine('if *offset + 4 > bytes.len() { return Err(DecodeError::UnexpectedEof); }');
  w.writeLine('let len = u32::from_le_bytes([bytes[*offset], bytes[*offset + 1], bytes[*offset + 2], bytes[*offset + 3]]) as usize;');
  w.writeLine('*offset += 4;');
  w.writeLine('if *offset + len > bytes.len() { return Err(DecodeError::UnexpectedEof); }');
  w.writeLine('let v = String::from_utf8(bytes[*offset..*offset + len].to_vec()).map_err(DecodeError::Utf8Error)?;');
  w.writeLine('*offset += len;');
  w.writeLine('Ok(v)');
  w.dedent();
  w.writeLine('}');
  w.writeLine();

  w.writeLine('fn decode_option<T, F>(bytes: &[u8], offset: &mut usize, decode_inner: F) -> Result<Option<T>, DecodeError>');
  w.writeLine('where');
  w.indent();
  w.writeLine('F: Fn(&[u8], &mut usize) -> Result<T, DecodeError>,');
  w.dedent();
  w.writeLine('{');
  w.indent();
  w.writeLine('if *offset >= bytes.len() { return Err(DecodeError::UnexpectedEof); }');
  w.writeLine('let tag = bytes[*offset];');
  w.writeLine('*offset += 1;');
  w.writeLine('match tag {');
  w.indent();
  w.writeLine('0x00 => Ok(None),');
  w.writeLine('0x01 => Ok(Some(decode_inner(bytes, offset)?)),');
  w.writeLine('t => Err(DecodeError::InvalidOptionTag(t)),');
  w.dedent();
  w.writeLine('}');
  w.dedent();
  w.writeLine('}');
  w.writeLine();

  w.writeLine('fn decode_list<T, F>(bytes: &[u8], offset: &mut usize, decode_inner: F) -> Result<Vec<T>, DecodeError>');
  w.writeLine('where');
  w.indent();
  w.writeLine('F: Fn(&[u8], &mut usize) -> Result<T, DecodeError>,');
  w.dedent();
  w.writeLine('{');
  w.indent();
  w.writeLine('if *offset + 4 > bytes.len() { return Err(DecodeError::UnexpectedEof); }');
  w.writeLine('let count = u32::from_le_bytes([bytes[*offset], bytes[*offset + 1], bytes[*offset + 2], bytes[*offset + 3]]) as usize;');
  w.writeLine('*offset += 4;');
  w.writeLine('let mut items = Vec::with_capacity(count);');
  w.writeLine('for _ in 0..count {');
  w.indent();
  w.writeLine('items.push(decode_inner(bytes, offset)?);');
  w.dedent();
  w.writeLine('}');
  w.writeLine('Ok(items)');
  w.dedent();
  w.writeLine('}');
  w.writeLine();
}

// ---------------------------------------------------------------------------
// Per-type codegen
// ---------------------------------------------------------------------------

/**
 * Emit encode/decode impl for an ENUM type.
 * Variants are sorted alphabetically; index is u32 LE.
 */
function emitEnumCodec(w, type) {
  const sorted = [...type.values].sort((a, b) => a.localeCompare(b));

  // encode
  w.writeLine(`impl ${type.name} {`);
  w.indent();
  w.writeLine('pub fn encode_raw_le(&self) -> Vec<u8> {');
  w.indent();
  w.writeLine('let idx: u32 = match self {');
  w.indent();
  sorted.forEach((v, i) => {
    w.writeLine(`Self::${v} => ${i},`);
  });
  w.dedent();
  w.writeLine('};');
  w.writeLine('idx.to_le_bytes().to_vec()');
  w.dedent();
  w.writeLine('}');
  w.writeLine();

  // decode
  w.writeLine('pub fn decode_raw_le(bytes: &[u8], offset: &mut usize) -> Result<Self, DecodeError> {');
  w.indent();
  w.writeLine('if *offset + 4 > bytes.len() { return Err(DecodeError::UnexpectedEof); }');
  w.writeLine('let idx = u32::from_le_bytes([bytes[*offset], bytes[*offset + 1], bytes[*offset + 2], bytes[*offset + 3]]);');
  w.writeLine('*offset += 4;');
  w.writeLine('match idx {');
  w.indent();
  sorted.forEach((v, i) => {
    w.writeLine(`${i} => Ok(Self::${v}),`);
  });
  w.writeLine('v => Err(DecodeError::InvalidEnumVariant(v)),');
  w.dedent();
  w.writeLine('}');
  w.dedent();
  w.writeLine('}');

  w.dedent();
  w.writeLine('}');
  w.writeLine();
}

/**
 * Emit encode/decode impl for an OBJECT type.
 * Fields are sorted alphabetically.
 */
function emitObjectCodec(w, type) {
  const fields = [...(type.fields ?? [])].sort((a, b) => a.name.localeCompare(b.name));

  w.writeLine(`impl ${type.name} {`);
  w.indent();

  // encode
  w.writeLine('pub fn encode_raw_le(&self) -> Vec<u8> {');
  w.indent();
  w.writeLine('let mut buf = Vec::new();');

  for (const field of fields) {
    const snake = toSnakeCase(field.name);
    emitFieldEncode(w, field, snake);
  }

  w.writeLine('buf');
  w.dedent();
  w.writeLine('}');
  w.writeLine();

  // decode
  w.writeLine('pub fn decode_raw_le(bytes: &[u8]) -> Result<Self, DecodeError> {');
  w.indent();
  w.writeLine('let mut offset = 0;');

  for (const field of fields) {
    const snake = toSnakeCase(field.name);
    emitFieldDecode(w, field, snake);
  }

  w.writeLine('Ok(Self {');
  w.indent();
  for (const field of fields) {
    const snake = toSnakeCase(field.name);
    w.writeLine(`${snake},`);
  }
  w.dedent();
  w.writeLine('})');
  w.dedent();
  w.writeLine('}');

  w.dedent();
  w.writeLine('}');
  w.writeLine();
}

// ---------------------------------------------------------------------------
// Field-level encode/decode emission
// ---------------------------------------------------------------------------

const SCALAR_TYPES = new Set(['Boolean', 'Int', 'Float', 'String', 'ID']);

function isScalar(typeName) {
  return SCALAR_TYPES.has(typeName);
}

function encodeExprForScalar(typeName, accessor) {
  switch (typeName) {
    case 'Boolean':
      return `buf.push(encode_bool(${accessor}));`;
    case 'Int':
      return `buf.extend_from_slice(&encode_i32_le(${accessor}));`;
    case 'Float':
      return `buf.extend_from_slice(&encode_f32_le(${accessor}));`;
    case 'String':
    case 'ID':
      return `buf.extend(encode_string(&${accessor}));`;
    default:
      // nested object / enum — call its encode_raw_le
      return `buf.extend(${accessor}.encode_raw_le());`;
  }
}

function encodeClosureForType(typeName) {
  switch (typeName) {
    case 'Boolean':
      return '|v| vec![encode_bool(*v)]';
    case 'Int':
      return '|v| encode_i32_le(*v).to_vec()';
    case 'Float':
      return '|v| encode_f32_le(*v).to_vec()';
    case 'String':
    case 'ID':
      return '|v| encode_string(v)';
    default:
      return '|v| v.encode_raw_le()';
  }
}

function decodeCallForType(typeName) {
  switch (typeName) {
    case 'Boolean':
      return 'decode_bool(bytes, &mut offset)?';
    case 'Int':
      return 'decode_i32_le(bytes, &mut offset)?';
    case 'Float':
      return 'decode_f32_le(bytes, &mut offset)?';
    case 'String':
    case 'ID':
      return 'decode_string(bytes, &mut offset)?';
    default:
      return `${typeName}::decode_raw_le_at(bytes, &mut offset)?`;
  }
}

function decodeClosureForType(typeName) {
  switch (typeName) {
    case 'Boolean':
      return 'decode_bool';
    case 'Int':
      return 'decode_i32_le';
    case 'Float':
      return 'decode_f32_le';
    case 'String':
    case 'ID':
      return 'decode_string';
    default:
      return `${typeName}::decode_raw_le_at`;
  }
}

function emitFieldEncode(w, field, snake) {
  const { type, required, list } = field;

  if (list && required) {
    // Required list: &[T]
    w.writeLine(`buf.extend(encode_list(&self.${snake}, ${encodeClosureForType(type)}));`);
  } else if (list && !required) {
    // Optional list: Option<Vec<T>>
    w.writeLine(`buf.extend(encode_option(&self.${snake}, |inner| encode_list(inner, ${encodeClosureForType(type)})));`);
  } else if (!required) {
    // Optional scalar/object
    w.writeLine(`buf.extend(encode_option(&self.${snake}, ${encodeClosureForType(type)}));`);
  } else {
    // Required scalar/object
    w.writeLine(encodeExprForScalar(type, `self.${snake}`));
  }
}

function emitFieldDecode(w, field, snake) {
  const { type, required, list } = field;

  if (list && required) {
    w.writeLine(`let ${snake} = decode_list(bytes, &mut offset, ${decodeClosureForType(type)})?;`);
  } else if (list && !required) {
    w.writeLine(`let ${snake} = decode_option(bytes, &mut offset, |b, o| decode_list(b, o, ${decodeClosureForType(type)}))?;`);
  } else if (!required) {
    w.writeLine(`let ${snake} = decode_option(bytes, &mut offset, ${decodeClosureForType(type)})?;`);
  } else {
    w.writeLine(`let ${snake} = ${decodeCallForType(type)};`);
  }
}

/**
 * Convert a camelCase name to snake_case.
 * @param {string} name
 * @returns {string}
 */
function toSnakeCase(name) {
  return name.replace(/([A-Z])/g, '_$1').toLowerCase().replace(/^_/, '');
}
