import { RustWriter } from './rust-writer.mjs';

/**
 * Emit Rust guarded view structs for every OBJECT type that has at least one
 * field annotated with `@wes_view`.
 *
 * For each rule name, generates:
 * - `{TypeName}{Rule}ReadView` — fields with access "READ" (or both READ+WRITE)
 * - `{TypeName}{Rule}WriteView` — fields with access "WRITE" (or both READ+WRITE)
 *
 * Returns `null` when the IR contains no view-annotated types (no file needed).
 *
 * @param {{ types: Array<{ name: string, kind: string, fields?: Array<{ name: string, type: string, required: boolean, list: boolean, views: Array<{ rule: string, access: string }> | null }> }> }} ir
 * @returns {string | null}
 */
export function emitGuardedViews(ir) {
  const viewTypes = (ir.types ?? []).filter(
    (t) => t.kind === 'OBJECT' && (t.fields ?? []).some((f) => f.views !== null)
  );

  if (viewTypes.length === 0) return null;

  // Collect all unique rule names across all types (sorted for deterministic output)
  const allRules = new Set();
  for (const type of viewTypes) {
    for (const field of type.fields ?? []) {
      for (const v of field.views ?? []) {
        allRules.add(v.rule);
      }
    }
  }
  const sortedRules = [...allRules].sort();

  const w = new RustWriter();

  w.writeLine('// Auto-generated by @wesley/generator-echo — DO NOT EDIT');
  w.writeLine();

  for (const type of viewTypes) {
    for (const rule of sortedRules) {
      // Collect fields for this rule
      const readFields = [];
      const writeFields = [];

      for (const field of type.fields ?? []) {
        if (!field.views) continue;
        const viewsForRule = field.views.filter((v) => v.rule === rule);
        if (viewsForRule.length === 0) continue;

        const hasRead = viewsForRule.some((v) => v.access === 'READ');
        const hasWrite = viewsForRule.some((v) => v.access === 'WRITE');

        if (hasRead) readFields.push(field);
        if (hasWrite) writeFields.push(field);
      }

      const capitalizedRule = capitalize(rule);

      // Emit ReadView
      if (readFields.length > 0) {
        const sortedRead = [...readFields].sort((a, b) => a.name < b.name ? -1 : a.name > b.name ? 1 : 0);
        emitReadView(w, type.name, capitalizedRule, sortedRead);
      }

      // Emit WriteView
      if (writeFields.length > 0) {
        const sortedWrite = [...writeFields].sort((a, b) => a.name < b.name ? -1 : a.name > b.name ? 1 : 0);
        emitWriteView(w, type.name, capitalizedRule, sortedWrite);
      }
    }
  }

  return w.toString();
}

/**
 * Emit ReadView struct + from_full impl.
 */
function emitReadView(w, typeName, rule, fields) {
  const structName = `${typeName}${rule}ReadView`;

  w.writeLine(`pub struct ${structName} {`);
  w.indent();
  for (const field of fields) {
    const snake = toSnakeCase(field.name);
    const rustType = mapRustType(field);
    w.writeLine(`pub ${snake}: ${rustType},`);
  }
  w.dedent();
  w.writeLine('}');
  w.writeLine();

  // from_full
  w.writeLine(`impl ${structName} {`);
  w.indent();
  w.writeLine(`pub fn from_full(full: &${typeName}) -> Self {`);
  w.indent();
  w.writeLine('Self {');
  w.indent();
  for (const field of fields) {
    const snake = toSnakeCase(field.name);
    const expr = cloneExpr(field, `full.${snake}`);
    w.writeLine(`${snake}: ${expr},`);
  }
  w.dedent();
  w.writeLine('}');
  w.dedent();
  w.writeLine('}');
  w.dedent();
  w.writeLine('}');
  w.writeLine();
}

/**
 * Emit WriteView struct + apply_write impl.
 */
function emitWriteView(w, typeName, rule, fields) {
  const structName = `${typeName}${rule}WriteView`;

  w.writeLine(`pub struct ${structName} {`);
  w.indent();
  for (const field of fields) {
    const snake = toSnakeCase(field.name);
    const rustType = mapRustType(field);
    w.writeLine(`pub ${snake}: ${rustType},`);
  }
  w.dedent();
  w.writeLine('}');
  w.writeLine();

  // apply_write
  w.writeLine(`impl ${structName} {`);
  w.indent();
  w.writeLine(`pub fn apply_write(view: Self, target: &mut ${typeName}) {`);
  w.indent();
  for (const field of fields) {
    const snake = toSnakeCase(field.name);
    w.writeLine(`target.${snake} = view.${snake};`);
  }
  w.dedent();
  w.writeLine('}');
  w.dedent();
  w.writeLine('}');
  w.writeLine();
}

/**
 * Map a GraphQL field to its Rust type string.
 * @param {{ type: string, required: boolean, list: boolean }} field
 * @returns {string}
 */
function mapRustType(field) {
  let inner = scalarToRust(field.type);

  if (field.list) {
    inner = `Vec<${inner}>`;
  }

  if (!field.required) {
    inner = `Option<${inner}>`;
  }

  return inner;
}

/**
 * Map a GraphQL scalar/type name to Rust type.
 * Note: Float maps to f32 (not f64) deliberately — SPEC-0008 raw_le wire
 * format uses 4-byte LE floats, and the generated Rust structs match.
 * @param {string} typeName
 * @returns {string}
 */
function scalarToRust(typeName) {
  switch (typeName) {
  case 'Boolean':
    return 'bool';
  case 'Int':
    return 'i32';
  case 'Float':
    return 'f32';
  case 'String':
  case 'ID':
    return 'String';
  default:
    return typeName;
  }
}

/**
 * Determine whether a field's Rust type needs `.clone()` in from_full.
 * Copy types (bool, i32, f32) don't need clone.
 * String, Vec, Option containing non-Copy, and nested objects need clone.
 */
function needsClone(field) {
  // If it's a list or optional, always clone (Vec and Option are not Copy)
  if (field.list || !field.required) return true;

  // For required non-list scalars, only Copy types don't need clone
  switch (field.type) {
  case 'Boolean':
  case 'Int':
  case 'Float':
    return false;
  default:
    // String, ID, and nested objects need clone
    return true;
  }
}

/**
 * Build the expression for copying a field from the full struct.
 * @param {object} field
 * @param {string} accessor - e.g. "full.name"
 * @returns {string}
 */
function cloneExpr(field, accessor) {
  if (needsClone(field)) {
    return `${accessor}.clone()`;
  }
  return accessor;
}

/**
 * Capitalize the first letter of a string.
 * @param {string} str
 * @returns {string}
 */
function capitalize(str) {
  if (!str) return str;
  return str.charAt(0).toUpperCase() + str.slice(1);
}

/**
 * Convert a camelCase name to snake_case.
 * @param {string} name
 * @returns {string}
 */
function toSnakeCase(name) {
  return name.replace(/([A-Z])/g, '_$1').toLowerCase().replace(/^_/, '');
}
