/**
 * Generator function for Echo (Rust/WASM) artifacts.
 */
export async function generateEcho(ir, options = {}) {
  const { types = [] } = ir;
  let rustCode = '// Generated by Wesley Echo Generator\n\n';
  rustCode += 'use serde::{Serialize, Deserialize};\n\n';

  for (const type of types) {
    if (type.kind === 'ENUM') {
      rustCode += '#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]\n';
      rustCode += `pub enum ${type.name} {\n`;
      for (const value of type.values) {
        rustCode += `    ${value},\n`;
      }
      rustCode += `}\n\n`;
    } else if (type.kind === 'OBJECT') {
      rustCode += '#[derive(Debug, Clone, Serialize, Deserialize)]\n';
      rustCode += `pub struct ${type.name} {\n`;
      for (const field of type.fields) {
        const rustType = mapType(field.type, field.required);
        rustCode += `    pub ${field.name}: ${rustType},\n`;
      }
      rustCode += `}\n\n`;
    }
  }

  return {
    files: [
      {
        path: 'generated.rs',
        content: rustCode
      }
    ]
  };
}

function mapType(gqlType, required) {
  let rustType = '';
  switch (gqlType) {
    case 'Boolean': rustType = 'bool'; break;
    case 'String': rustType = 'String'; break;
    case 'Int': rustType = 'i32'; break;
    case 'Float': rustType = 'f32'; break;
    default: rustType = gqlType; // Custom type or Enum
  }

  if (!required) {
    return `Option<${rustType}>`;
  }
  return rustType;
}
