/**
 * Generator function for Vue artifacts.
 *
 * For plugin-based invocation (PluginRunner, CLI), use VuePlugin instead:
 *   import { VuePlugin } from '@wesley/generator-vue/plugin';
 */
export async function generateVue(ir, options = {}) {
  if (!ir || typeof ir !== 'object') {
    throw new Error('generateVue: expected an IR object');
  }
  if (!Array.isArray(ir.types)) {
    throw new Error('generateVue: expected ir.types to be an array');
  }

  const outPath = options.outPath ?? 'types.generated.ts';

  const knownTypes = new Set([
    'Boolean',
    'String',
    'Int',
    'Float',
    'ID',
    ...ir.types.map((t) => t?.name).filter(Boolean)
  ]);

  const lines = [];
  lines.push('// AUTO-GENERATED. DO NOT EDIT.');
  lines.push('// Generated by @wesley/generator-vue');
  lines.push('');

  // Enums first (so interfaces can refer to them).
  for (const t of ir.types) {
    if (!t || t.kind !== 'ENUM') continue;
    const name = t.name;
    const values = Array.isArray(t.values) ? t.values : [];

    lines.push(`export enum ${name} {`);
    for (const v of values) {
      const key = toTsEnumKey(v);
      lines.push(`  ${key} = ${JSON.stringify(v)},`);
    }
    lines.push('}');
    lines.push('');
  }

  // Object interfaces.
  for (const t of ir.types) {
    if (!t || t.kind !== 'OBJECT') continue;
    const name = t.name;
    const fields = Array.isArray(t.fields) ? t.fields : [];

    lines.push(`export interface ${name} {`);
    for (const f of fields) {
      if (!f || typeof f.name !== 'string') continue;
      const required = f.required !== false;
      const list = f.list === true;
      const typeName = typeof f.type === 'string' ? f.type : 'Unknown';
      const tsType = tsTypeForGql(typeName, { knownTypes });
      const fullType = list ? `${tsType}[]` : tsType;
      lines.push(`  ${f.name}${required ? '' : '?'}: ${fullType};`);
    }
    lines.push('}');
    lines.push('');
  }

  return {
    files: [{ path: outPath, content: lines.join('\n') }]
  };
}

function tsTypeForGql(typeName, { knownTypes }) {
  switch (typeName) {
    case 'Boolean':
      return 'boolean';
    case 'String':
    case 'ID':
      return 'string';
    case 'Int':
    case 'Float':
      return 'number';
    default:
      return knownTypes.has(typeName) ? typeName : 'any';
  }
}

function toTsEnumKey(value) {
  if (typeof value !== 'string' || value.length === 0) return 'UNKNOWN';
  let out = value.replace(/[^A-Za-z0-9_]/g, '_');
  if (/^[0-9]/.test(out)) out = `_${out}`;
  return out;
}
