/* @generated by wesley-emit-typescript le-binary. Do not edit. */
// SPDX-License-Identifier: Apache-2.0
//
// Wire layout is Wesley little-endian variable codec v0. Field order is SDL
// declaration order. Enums encode their zero-based variant index as u32 LE.

import { Writer as RuntimeWriter, Reader as RuntimeReader, CodecError as RuntimeCodecError } from '../../codec.js';

export type Result<T> =
    | { ok: true; value: T }
    | { ok: false; error: CodecError };

export interface CodecError {
    readonly message: string;
}

export interface Writer {
    writeU32Le(value: number): void;
    writeI32Le(value: number): void;
    writeF32Le(value: number): void;
    writeBool(value: boolean): void;
    writeString(value: string): void;
    writeOption<T>(value: T | null, write: (writer: Writer, value: T) => void): void;
    writeList<T>(value: T[], write: (writer: Writer, value: T) => void): void;
    finish(): Uint8Array;
}

export interface Reader {
    readU32Le(): number;
    readI32Le(): number;
    readF32Le(): number;
    readBool(): boolean;
    readString(): string;
    readOption<T>(read: (reader: Reader) => T): T | null;
    readList<T>(read: (reader: Reader) => T): T[];
    remaining(): number;
}

function ok<T>(value: T): Result<T> {
    return { ok: true, value };
}

function err<T>(error: CodecError): Result<T> {
    return { ok: false, error };
}

function codecErrorFromUnknown(error: unknown): CodecError {
    if (error instanceof RuntimeCodecError) {
        return error;
    }
    if (error instanceof Error) {
        return new RuntimeCodecError(error.message);
    }
    return new RuntimeCodecError(String(error));
}

function decodeWithBoundary<T>(b: Uint8Array, read: (reader: Reader) => T): Result<T> {
    try {
        const r = new RuntimeReader(b);
        const value = read(r);
        if (r.remaining() > 0) {
            return err(new RuntimeCodecError('trailing bytes after decode'));
        }
        return ok(value);
    } catch (error) {
        return err(codecErrorFromUnknown(error));
    }
}

// ─── enum Color ───

export type Color =
    | 'RED'
    | 'GREEN'
    | 'BLUE';

export function _encColor(w: Writer, v: Color): void {
    switch (v) {
        case 'RED': w.writeU32Le(0); return;
        case 'GREEN': w.writeU32Le(1); return;
        case 'BLUE': w.writeU32Le(2); return;
        default: throw new RuntimeCodecError('invalid Color variant: ' + String(v));
    }
}

export function _decColor(r: Reader): Color {
    const d = r.readU32Le();
    switch (d) {
        case 0: return 'RED';
        case 1: return 'GREEN';
        case 2: return 'BLUE';
        default: throw new RuntimeCodecError('invalid Color discriminant: ' + String(d));
    }
}

export function encodeColor(v: Color): Uint8Array {
    const w = new RuntimeWriter();
    _encColor(w, v);
    return w.finish();
}

export function decodeColor(b: Uint8Array): Result<Color> {
    return decodeWithBoundary(b, (r) => _decColor(r));
}

// ─── input MakeWidgetInput ───

export interface MakeWidgetInput {
    label: string;
    count: number;
    ratio: number;
    enabled: boolean;
    color: Color | null;
    solo: Solo;
    tags: string[];
    nullishTags: (string | null)[];
    maybeTags: string[] | null;
    optionalNullishTags: (string | null)[] | null;
    matrix: number[][];
    optionalMatrix: (number[] | null)[] | null;
}

export function _encMakeWidgetInput(w: Writer, v: MakeWidgetInput): void {
    w.writeString(v.label);
    w.writeI32Le(v.count);
    w.writeF32Le(v.ratio);
    w.writeBool(v.enabled);
    w.writeOption(v.color, (w, x) => _encColor(w, x));
    _encSolo(w, v.solo);
    w.writeList(v.tags, (w, x) => w.writeString(x));
    w.writeList(v.nullishTags, (w, x) => w.writeOption(x, (w, x) => w.writeString(x)));
    w.writeOption(v.maybeTags, (w, x) => w.writeList(x, (w, x) => w.writeString(x)));
    w.writeOption(v.optionalNullishTags, (w, x) => w.writeList(x, (w, x) => w.writeOption(x, (w, x) => w.writeString(x))));
    w.writeList(v.matrix, (w, x) => w.writeList(x, (w, x) => w.writeI32Le(x)));
    w.writeOption(v.optionalMatrix, (w, x) => w.writeList(x, (w, x) => w.writeOption(x, (w, x) => w.writeList(x, (w, x) => w.writeI32Le(x)))));
}

export function _decMakeWidgetInput(r: Reader): MakeWidgetInput {
    return {
        label: r.readString(),
        count: r.readI32Le(),
        ratio: r.readF32Le(),
        enabled: r.readBool(),
        color: r.readOption((r) => _decColor(r)),
        solo: _decSolo(r),
        tags: r.readList((r) => r.readString()),
        nullishTags: r.readList((r) => r.readOption((r) => r.readString())),
        maybeTags: r.readOption((r) => r.readList((r) => r.readString())),
        optionalNullishTags: r.readOption((r) => r.readList((r) => r.readOption((r) => r.readString()))),
        matrix: r.readList((r) => r.readList((r) => r.readI32Le())),
        optionalMatrix: r.readOption((r) => r.readList((r) => r.readOption((r) => r.readList((r) => r.readI32Le())))),
    };
}

// ─── enum Solo ───

export type Solo =
    | 'ONE';

export function _encSolo(w: Writer, v: Solo): void {
    switch (v) {
        case 'ONE': w.writeU32Le(0); return;
        default: throw new RuntimeCodecError('invalid Solo variant: ' + String(v));
    }
}

export function _decSolo(r: Reader): Solo {
    const d = r.readU32Le();
    switch (d) {
        case 0: return 'ONE';
        default: throw new RuntimeCodecError('invalid Solo discriminant: ' + String(d));
    }
}

export function encodeSolo(v: Solo): Uint8Array {
    const w = new RuntimeWriter();
    _encSolo(w, v);
    return w.finish();
}

export function decodeSolo(b: Uint8Array): Result<Solo> {
    return decodeWithBoundary(b, (r) => _decSolo(r));
}

// ─── type Widget ───

export interface Widget {
    id: string;
    label: string;
}

export function _encWidget(w: Writer, v: Widget): void {
    w.writeString(v.id);
    w.writeString(v.label);
}

export function _decWidget(r: Reader): Widget {
    return {
        id: r.readString(),
        label: r.readString(),
    };
}

// ─── query widget ───

export interface WidgetVars {
    id: string;
}

export function _encWidgetVars(w: Writer, v: WidgetVars): void {
    w.writeString(v.id);
}

export function _decWidgetVars(r: Reader): WidgetVars {
    return {
        id: r.readString(),
    };
}

export function encodeWidgetVars(v: WidgetVars): Uint8Array {
    const w = new RuntimeWriter();
    _encWidgetVars(w, v);
    return w.finish();
}

export function decodeWidgetVars(b: Uint8Array): Result<WidgetVars> {
    return decodeWithBoundary(b, (r) => _decWidgetVars(r));
}

// ─── mutation makeWidget ───

export interface MakeWidgetVars {
    input: MakeWidgetInput;
}

export function _encMakeWidgetVars(w: Writer, v: MakeWidgetVars): void {
    _encMakeWidgetInput(w, v.input);
}

export function _decMakeWidgetVars(r: Reader): MakeWidgetVars {
    return {
        input: _decMakeWidgetInput(r),
    };
}

export function encodeMakeWidgetVars(v: MakeWidgetVars): Uint8Array {
    const w = new RuntimeWriter();
    _encMakeWidgetVars(w, v);
    return w.finish();
}

export function decodeMakeWidgetVars(b: Uint8Array): Result<MakeWidgetVars> {
    return decodeWithBoundary(b, (r) => _decMakeWidgetVars(r));
}
