/* @generated by wesley-emit-typescript le-binary. Do not edit. */
// SPDX-License-Identifier: Apache-2.0
//
// Wire layout is Wesley little-endian variable codec v0. Field order is SDL
// declaration order. Enums encode their zero-based variant index as u32 LE.

import { Writer, Reader, CodecError } from '../../codec.js';

// ─── enum Color ───

export type Color =
    | 'RED'
    | 'GREEN'
    | 'BLUE';

export function _encColor(w: Writer, v: Color): void {
    switch (v) {
        case 'RED': w.writeU32Le(0); return;
        case 'GREEN': w.writeU32Le(1); return;
        case 'BLUE': w.writeU32Le(2); return;
        default: throw new CodecError('invalid Color variant: ' + String(v));
    }
}

export function _decColor(r: Reader): Color {
    const d = r.readU32Le();
    switch (d) {
        case 0: return 'RED';
        case 1: return 'GREEN';
        case 2: return 'BLUE';
        default: throw new CodecError('invalid Color discriminant: ' + String(d));
    }
}

export function encodeColor(v: Color): Uint8Array {
    const w = new Writer();
    _encColor(w, v);
    return w.finish();
}

export function decodeColor(b: Uint8Array): Color {
    return _decColor(new Reader(b));
}

// ─── input MakeWidgetInput ───

export interface MakeWidgetInput {
    label: string;
    count: number;
    ratio: number;
    enabled: boolean;
    color: Color | null;
    solo: Solo;
    tags: string[];
    nullishTags: (string | null)[];
    maybeTags: string[] | null;
    optionalNullishTags: (string | null)[] | null;
    matrix: number[][];
    optionalMatrix: (number[] | null)[] | null;
}

export function _encMakeWidgetInput(w: Writer, v: MakeWidgetInput): void {
    w.writeString(v.label);
    w.writeI32Le(v.count);
    w.writeF32Le(v.ratio);
    w.writeBool(v.enabled);
    w.writeOption(v.color, (w, x) => _encColor(w, x));
    _encSolo(w, v.solo);
    w.writeList(v.tags, (w, x) => w.writeString(x));
    w.writeList(v.nullishTags, (w, x) => w.writeOption(x, (w, x) => w.writeString(x)));
    w.writeOption(v.maybeTags, (w, x) => w.writeList(x, (w, x) => w.writeString(x)));
    w.writeOption(v.optionalNullishTags, (w, x) => w.writeList(x, (w, x) => w.writeOption(x, (w, x) => w.writeString(x))));
    w.writeList(v.matrix, (w, x) => w.writeList(x, (w, x) => w.writeI32Le(x)));
    w.writeOption(v.optionalMatrix, (w, x) => w.writeList(x, (w, x) => w.writeOption(x, (w, x) => w.writeList(x, (w, x) => w.writeI32Le(x)))));
}

export function _decMakeWidgetInput(r: Reader): MakeWidgetInput {
    return {
        label: r.readString(),
        count: r.readI32Le(),
        ratio: r.readF32Le(),
        enabled: r.readBool(),
        color: r.readOption((r) => _decColor(r)),
        solo: _decSolo(r),
        tags: r.readList((r) => r.readString()),
        nullishTags: r.readList((r) => r.readOption((r) => r.readString())),
        maybeTags: r.readOption((r) => r.readList((r) => r.readString())),
        optionalNullishTags: r.readOption((r) => r.readList((r) => r.readOption((r) => r.readString()))),
        matrix: r.readList((r) => r.readList((r) => r.readI32Le())),
        optionalMatrix: r.readOption((r) => r.readList((r) => r.readOption((r) => r.readList((r) => r.readI32Le())))),
    };
}

// ─── enum Solo ───

export type Solo =
    | 'ONE';

export function _encSolo(w: Writer, v: Solo): void {
    switch (v) {
        case 'ONE': w.writeU32Le(0); return;
        default: throw new CodecError('invalid Solo variant: ' + String(v));
    }
}

export function _decSolo(r: Reader): Solo {
    const d = r.readU32Le();
    switch (d) {
        case 0: return 'ONE';
        default: throw new CodecError('invalid Solo discriminant: ' + String(d));
    }
}

export function encodeSolo(v: Solo): Uint8Array {
    const w = new Writer();
    _encSolo(w, v);
    return w.finish();
}

export function decodeSolo(b: Uint8Array): Solo {
    return _decSolo(new Reader(b));
}

// ─── query widget ───

export interface WidgetVars {
    id: string;
}

export function encodeWidgetVars(v: WidgetVars): Uint8Array {
    const w = new Writer();
    w.writeString(v.id);
    return w.finish();
}

export function decodeWidgetVars(b: Uint8Array): WidgetVars {
    const r = new Reader(b);
    return {
        id: r.readString(),
    };
}

// ─── mutation makeWidget ───

export interface MakeWidgetVars {
    input: MakeWidgetInput;
}

export function encodeMakeWidgetVars(v: MakeWidgetVars): Uint8Array {
    const w = new Writer();
    _encMakeWidgetInput(w, v.input);
    return w.finish();
}

export function decodeMakeWidgetVars(b: Uint8Array): MakeWidgetVars {
    const r = new Reader(b);
    return {
        input: _decMakeWidgetInput(r),
    };
}
