/* @generated by Wesley. Do not edit. */

export type DateTime = unknown;

export interface Delivery extends Node {
  id: string;
  mode: DeliveryMode;
  requestedAt: DateTime | null;
  tags: string[];
}

export interface DeliveryEvent {
  delivery: Delivery;
  observedAt: DateTime;
}

export type DeliveryMode = "BATCH" | "SINGLE";

export interface Node {
  id: string;
}

export interface ScheduleInput {
  mode: DeliveryMode;
  requestedAt?: DateTime | null;
  tags?: string[] | null;
}

export interface ScheduleResult {
  accepted: boolean;
  delivery: Delivery | null;
}

export interface QueryDeliveryRequest {
  id: string;
  includeHistory?: boolean | null;
}

export type QueryDeliveryResponse = Delivery | null;

export const queryDeliveryOperation = {
  operationType: "QUERY",
  fieldName: "delivery",
  directives: {"route":{"path":"/delivery"}},
} as const;

export type QueryDeliveryOperation = {
  request: QueryDeliveryRequest;
  response: QueryDeliveryResponse;
  metadata: typeof queryDeliveryOperation;
};

export interface MutationScheduleRequest {
  input: ScheduleInput;
  traceId?: string | null;
}

export type MutationScheduleResponse = ScheduleResult;

export const mutationScheduleOperation = {
  operationType: "MUTATION",
  fieldName: "schedule",
  directives: {"route":{"path":"/schedule","retry":2}},
} as const;

export type MutationScheduleOperation = {
  request: MutationScheduleRequest;
  response: MutationScheduleResponse;
  metadata: typeof mutationScheduleOperation;
};

export interface SubscriptionDeliveryEventsRequest {
  after?: string | null;
  labels?: string[][] | null;
}

export type SubscriptionDeliveryEventsResponse = DeliveryEvent[];

export const subscriptionDeliveryEventsOperation = {
  operationType: "SUBSCRIPTION",
  fieldName: "deliveryEvents",
  directives: {"route":{"path":"/events"}},
} as const;

export type SubscriptionDeliveryEventsOperation = {
  request: SubscriptionDeliveryEventsRequest;
  response: SubscriptionDeliveryEventsResponse;
  metadata: typeof subscriptionDeliveryEventsOperation;
};
