[package]
name = "wesley-cli"
version = "0.1.1"
edition = "2021"
description = "Wesley native CLI"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/flyingrobots/wesley"
homepage = "https://github.com/flyingrobots/wesley#readme"
documentation = "https://docs.rs/wesley-cli"
keywords = ["graphql", "compiler", "cli", "schema"]
categories = ["command-line-utilities", "compilers"]

[[bin]]
name = "wesley"
path = "src/main.rs"

[dependencies]
serde = "1.0"
serde_json = "1.0"
wesley-core = { path = "../wesley-core", version = "0.1.1" }
wesley-emit-rust = { path = "../wesley-emit-rust", version = "0.1.1" }
wesley-emit-typescript = { path = "../wesley-emit-typescript", version = "0.1.1" }
