// @generated by Wesley. Do not edit.
use crate::codec::{CodecError, Reader, Writer};

/// Encode a `Color` into LE-binary bytes.
pub fn encode_color(value: &Color) -> Vec<u8> {
    let mut writer = Writer::new();
    enc_color(&mut writer, value);
    writer.finish()
}

/// Decode a `Color` from LE-binary bytes, rejecting trailing input.
pub fn decode_color(bytes: &[u8]) -> Result<Color, CodecError> {
    let mut reader = Reader::new(bytes);
    let value = dec_color(&mut reader)?;
    if reader.remaining() > 0 {
        return Err(CodecError::new("trailing bytes after decode".to_string()));
    }
    Ok(value)
}

fn enc_color(writer: &mut Writer, value: &Color) {
    match value {
        Color::Red => writer.write_u32_le(0),
        Color::Green => writer.write_u32_le(1),
        Color::Blue => writer.write_u32_le(2),
    }
}

fn dec_color(reader: &mut Reader) -> Result<Color, CodecError> {
    let discriminant = reader.read_u32_le()?;
    match discriminant {
        0 => Ok(Color::Red),
        1 => Ok(Color::Green),
        2 => Ok(Color::Blue),
        other => Err(CodecError::new(format!("invalid Color discriminant: {other}"))),
    }
}

/// Encode a `MakeWidgetInput` into LE-binary bytes.
pub fn encode_make_widget_input(value: &MakeWidgetInput) -> Vec<u8> {
    let mut writer = Writer::new();
    enc_make_widget_input(&mut writer, value);
    writer.finish()
}

/// Decode a `MakeWidgetInput` from LE-binary bytes, rejecting trailing input.
pub fn decode_make_widget_input(bytes: &[u8]) -> Result<MakeWidgetInput, CodecError> {
    let mut reader = Reader::new(bytes);
    let value = dec_make_widget_input(&mut reader)?;
    if reader.remaining() > 0 {
        return Err(CodecError::new("trailing bytes after decode".to_string()));
    }
    Ok(value)
}

fn enc_make_widget_input(writer: &mut Writer, value: &MakeWidgetInput) {
    writer.write_string(&value.label);
    writer.write_i32_le(value.count);
    writer.write_f32_le(value.ratio);
    writer.write_bool(value.enabled);
    writer.write_option(&value.color, |writer, x| enc_color(writer, x));
    enc_solo(writer, &value.solo);
    writer.write_list(&value.tags, |writer, x| writer.write_string(x));
    writer.write_list(&value.nullish_tags, |writer, x| writer.write_option(x, |writer, x| writer.write_string(x)));
    writer.write_option(&value.maybe_tags, |writer, x| writer.write_list(x, |writer, x| writer.write_string(x)));
    writer.write_option(&value.optional_nullish_tags, |writer, x| writer.write_list(x, |writer, x| writer.write_option(x, |writer, x| writer.write_string(x))));
    writer.write_list(&value.matrix, |writer, x| writer.write_list(x, |writer, x| writer.write_i32_le(*x)));
    writer.write_option(&value.optional_matrix, |writer, x| writer.write_list(x, |writer, x| writer.write_option(x, |writer, x| writer.write_list(x, |writer, x| writer.write_i32_le(*x)))));
}

fn dec_make_widget_input(reader: &mut Reader) -> Result<MakeWidgetInput, CodecError> {
    Ok(MakeWidgetInput {
        label: reader.read_string()?,
        count: reader.read_i32_le()?,
        ratio: reader.read_f32_le()?,
        enabled: reader.read_bool()?,
        color: reader.read_option(|reader| dec_color(reader))?,
        solo: dec_solo(reader)?,
        tags: reader.read_list(|reader| reader.read_string())?,
        nullish_tags: reader.read_list(|reader| reader.read_option(|reader| reader.read_string()))?,
        maybe_tags: reader.read_option(|reader| reader.read_list(|reader| reader.read_string()))?,
        optional_nullish_tags: reader.read_option(|reader| reader.read_list(|reader| reader.read_option(|reader| reader.read_string())))?,
        matrix: reader.read_list(|reader| reader.read_list(|reader| reader.read_i32_le()))?,
        optional_matrix: reader.read_option(|reader| reader.read_list(|reader| reader.read_option(|reader| reader.read_list(|reader| reader.read_i32_le()))))?,
    })
}

/// Encode a `Solo` into LE-binary bytes.
pub fn encode_solo(value: &Solo) -> Vec<u8> {
    let mut writer = Writer::new();
    enc_solo(&mut writer, value);
    writer.finish()
}

/// Decode a `Solo` from LE-binary bytes, rejecting trailing input.
pub fn decode_solo(bytes: &[u8]) -> Result<Solo, CodecError> {
    let mut reader = Reader::new(bytes);
    let value = dec_solo(&mut reader)?;
    if reader.remaining() > 0 {
        return Err(CodecError::new("trailing bytes after decode".to_string()));
    }
    Ok(value)
}

fn enc_solo(writer: &mut Writer, value: &Solo) {
    match value {
        Solo::One => writer.write_u32_le(0),
    }
}

fn dec_solo(reader: &mut Reader) -> Result<Solo, CodecError> {
    let discriminant = reader.read_u32_le()?;
    match discriminant {
        0 => Ok(Solo::One),
        other => Err(CodecError::new(format!("invalid Solo discriminant: {other}"))),
    }
}

/// Encode a `Widget` into LE-binary bytes.
pub fn encode_widget(value: &Widget) -> Vec<u8> {
    let mut writer = Writer::new();
    enc_widget(&mut writer, value);
    writer.finish()
}

/// Decode a `Widget` from LE-binary bytes, rejecting trailing input.
pub fn decode_widget(bytes: &[u8]) -> Result<Widget, CodecError> {
    let mut reader = Reader::new(bytes);
    let value = dec_widget(&mut reader)?;
    if reader.remaining() > 0 {
        return Err(CodecError::new("trailing bytes after decode".to_string()));
    }
    Ok(value)
}

fn enc_widget(writer: &mut Writer, value: &Widget) {
    writer.write_string(&value.id);
    writer.write_string(&value.label);
}

fn dec_widget(reader: &mut Reader) -> Result<Widget, CodecError> {
    Ok(Widget {
        id: reader.read_string()?,
        label: reader.read_string()?,
    })
}

/// Encode a `QueryWidgetRequest` into LE-binary bytes.
pub fn encode_query_widget_request(value: &QueryWidgetRequest) -> Vec<u8> {
    let mut writer = Writer::new();
    enc_query_widget_request(&mut writer, value);
    writer.finish()
}

/// Decode a `QueryWidgetRequest` from LE-binary bytes, rejecting trailing input.
pub fn decode_query_widget_request(bytes: &[u8]) -> Result<QueryWidgetRequest, CodecError> {
    let mut reader = Reader::new(bytes);
    let value = dec_query_widget_request(&mut reader)?;
    if reader.remaining() > 0 {
        return Err(CodecError::new("trailing bytes after decode".to_string()));
    }
    Ok(value)
}

fn enc_query_widget_request(writer: &mut Writer, value: &QueryWidgetRequest) {
    writer.write_string(&value.id);
}

fn dec_query_widget_request(reader: &mut Reader) -> Result<QueryWidgetRequest, CodecError> {
    Ok(QueryWidgetRequest {
        id: reader.read_string()?,
    })
}

/// Encode a `MutationMakeWidgetRequest` into LE-binary bytes.
pub fn encode_mutation_make_widget_request(value: &MutationMakeWidgetRequest) -> Vec<u8> {
    let mut writer = Writer::new();
    enc_mutation_make_widget_request(&mut writer, value);
    writer.finish()
}

/// Decode a `MutationMakeWidgetRequest` from LE-binary bytes, rejecting trailing input.
pub fn decode_mutation_make_widget_request(bytes: &[u8]) -> Result<MutationMakeWidgetRequest, CodecError> {
    let mut reader = Reader::new(bytes);
    let value = dec_mutation_make_widget_request(&mut reader)?;
    if reader.remaining() > 0 {
        return Err(CodecError::new("trailing bytes after decode".to_string()));
    }
    Ok(value)
}

fn enc_mutation_make_widget_request(writer: &mut Writer, value: &MutationMakeWidgetRequest) {
    enc_make_widget_input(writer, &value.input);
}

fn dec_mutation_make_widget_request(reader: &mut Reader) -> Result<MutationMakeWidgetRequest, CodecError> {
    Ok(MutationMakeWidgetRequest {
        input: dec_make_widget_input(reader)?,
    })
}
