//! LE-binary codec emitter for Wesley L1 IR (Rust).
//!
//! This is the Rust counterpart of `wesley-emit-typescript`'s
//! `emit_le_binary_typescript`: it emits `encode_*` / `decode_*` functions over
//! a consumer-provided runtime (`Writer`, `Reader`, `CodecError`) with a wire
//! format identical to the TypeScript codec, so the two interoperate byte for
//! byte:
//!
//! - enums encode as a `u32` little-endian discriminant (declaration ordinal);
//! - `Int` is `i32` LE, `Float` is `f32` LE, `Boolean` is a tagged byte;
//! - `String` / `ID` are length-prefixed UTF-8;
//! - nullable values are tagged (`writeOption`); lists are length-prefixed.
//!
//! The emitted code **references** the Wesley-generated Rust types (it does not
//! redefine them), so place it in a module where those types — and the runtime
//! `Writer` / `Reader` / `CodecError` — are in scope.

use std::collections::BTreeSet;
use std::fmt::Write as _;

use wesley_core::{SchemaOperation, TypeDefinition, TypeKind, TypeReference, WesleyIR};

use crate::{rust_field_name, rust_type_name, rust_variant_name, to_snake_case};

/// The default Rust module path the emitted codec imports its runtime from.
pub const DEFAULT_CODEC_IMPORT: &str = "crate::codec";

/// Stable generator identifier recorded in native emit metadata for this codec.
pub const LE_BINARY_GENERATOR_NAME: &str = "wesley-emit-rust:le-binary";

/// Emit a Rust LE-binary codec for the data types in `ir`.
///
/// Enums, input objects, and output objects each get an `encode_*` / `decode_*`
/// pair; operation root types (Query / Mutation / Subscription, identified from
/// `operations`) are skipped. The codec imports `Writer`, `Reader`, and
/// `CodecError` from `codec_import_path`.
#[must_use]
pub fn emit_le_binary_rust(
    ir: &WesleyIR,
    operations: &[SchemaOperation],
    codec_import_path: &str,
) -> String {
    let root_type_names: BTreeSet<&str> = operations
        .iter()
        .map(|operation| operation.root_type_name.as_str())
        .collect();

    let mut out = String::new();
    let _ = writeln!(out, "// @generated by Wesley. Do not edit.");
    let _ = writeln!(
        out,
        "use {codec_import_path}::{{CodecError, Reader, Writer}};"
    );

    for type_def in &ir.types {
        match type_def.kind {
            TypeKind::Enum => emit_enum(&mut out, type_def),
            TypeKind::InputObject | TypeKind::Object | TypeKind::Interface
                if !root_type_names.contains(type_def.name.as_str()) =>
            {
                emit_object(&mut out, type_def);
            }
            _ => {}
        }
    }

    out
}

/// Emit the public `encode_*` / `decode_*` wrappers shared by every type.
fn emit_wrappers(out: &mut String, ty: &str, snake: &str) {
    let _ = write!(
        out,
        "\n\
         /// Encode a `{ty}` into LE-binary bytes.\n\
         pub fn encode_{snake}(value: &{ty}) -> Vec<u8> {{\n\
         \x20   let mut writer = Writer::new();\n\
         \x20   enc_{snake}(&mut writer, value);\n\
         \x20   writer.finish()\n\
         }}\n\
         \n\
         /// Decode a `{ty}` from LE-binary bytes.\n\
         pub fn decode_{snake}(bytes: &[u8]) -> Result<{ty}, CodecError> {{\n\
         \x20   let mut reader = Reader::new(bytes);\n\
         \x20   dec_{snake}(&mut reader)\n\
         }}\n"
    );
}

fn emit_enum(out: &mut String, type_def: &TypeDefinition) {
    let ty = rust_type_name(&type_def.name);
    let snake = to_snake_case(&type_def.name);
    emit_wrappers(out, &ty, &snake);

    let _ = write!(
        out,
        "\nfn enc_{snake}(writer: &mut Writer, value: &{ty}) {{\n"
    );
    let _ = writeln!(out, "    match value {{");
    for (index, value) in type_def.enum_values.iter().enumerate() {
        let variant = rust_variant_name(value);
        let _ = writeln!(
            out,
            "        {ty}::{variant} => writer.write_u32_le({index}),"
        );
    }
    let _ = writeln!(out, "    }}");
    let _ = writeln!(out, "}}");

    let _ = write!(
        out,
        "\nfn dec_{snake}(reader: &mut Reader) -> Result<{ty}, CodecError> {{\n"
    );
    let _ = writeln!(out, "    let discriminant = reader.read_u32_le()?;");
    let _ = writeln!(out, "    match discriminant {{");
    for (index, value) in type_def.enum_values.iter().enumerate() {
        let variant = rust_variant_name(value);
        let _ = writeln!(out, "        {index} => Ok({ty}::{variant}),");
    }
    let _ = writeln!(
        out,
        "        other => Err(CodecError::new(format!(\"invalid {ty} discriminant: {{other}}\"))),"
    );
    let _ = writeln!(out, "    }}");
    let _ = writeln!(out, "}}");
}

fn emit_object(out: &mut String, type_def: &TypeDefinition) {
    let ty = rust_type_name(&type_def.name);
    let snake = to_snake_case(&type_def.name);
    emit_wrappers(out, &ty, &snake);

    let _ = write!(
        out,
        "\nfn enc_{snake}(writer: &mut Writer, value: &{ty}) {{\n"
    );
    if type_def.fields.is_empty() {
        let _ = writeln!(out, "    let _ = (writer, value);");
    }
    for field in &type_def.fields {
        let access = format!("&value.{}", rust_field_name(&field.name));
        let _ = writeln!(out, "    {};", encode_ref(&access, &field.r#type));
    }
    let _ = writeln!(out, "}}");

    let _ = write!(
        out,
        "\nfn dec_{snake}(reader: &mut Reader) -> Result<{ty}, CodecError> {{\n"
    );
    if type_def.fields.is_empty() {
        let _ = writeln!(out, "    let _ = reader;");
        let _ = writeln!(out, "    Ok({ty} {{}})");
    } else {
        let _ = writeln!(out, "    Ok({ty} {{");
        for field in &type_def.fields {
            let name = rust_field_name(&field.name);
            let _ = writeln!(out, "        {name}: {}?,", decode_ref(&field.r#type));
        }
        let _ = writeln!(out, "    }})");
    }
    let _ = writeln!(out, "}}");
}

/// Build the encode expression for a value reachable as the `&T` expression
/// `expr`. Mirrors the TypeScript emitter's `encode_expr_for_reference`.
fn encode_ref(expr: &str, ty: &TypeReference) -> String {
    if ty.nullable {
        let mut inner = ty.clone();
        inner.nullable = false;
        return format!(
            "writer.write_option({expr}, |writer, x| {})",
            encode_ref("x", &inner)
        );
    }
    if let Some(item) = list_item_type_reference(ty) {
        return format!(
            "writer.write_list({expr}, |writer, x| {})",
            encode_ref("x", &item)
        );
    }
    scalar_encode(&ty.base, expr)
}

/// Build the decode expression (of type `Result<_, CodecError>`) for `ty`.
fn decode_ref(ty: &TypeReference) -> String {
    if ty.nullable {
        let mut inner = ty.clone();
        inner.nullable = false;
        return format!("reader.read_option(|reader| {})", decode_ref(&inner));
    }
    if let Some(item) = list_item_type_reference(ty) {
        return format!("reader.read_list(|reader| {})", decode_ref(&item));
    }
    scalar_decode(&ty.base)
}

fn scalar_encode(base: &str, expr: &str) -> String {
    match base {
        "Boolean" => format!("writer.write_bool({})", deref_copy(expr)),
        "Int" => format!("writer.write_i32_le({})", deref_copy(expr)),
        "Float" => format!("writer.write_f32_le({})", deref_copy(expr)),
        "String" | "ID" => format!("writer.write_string({expr})"),
        other => format!("enc_{}(writer, {expr})", to_snake_case(other)),
    }
}

/// Turn a `&T` expression into an owned `T` expression for a `Copy` scalar: drop
/// a leading borrow (`&value.x` -> `value.x`) or dereference (`x` -> `*x`).
fn deref_copy(expr: &str) -> String {
    expr.strip_prefix('&')
        .map_or_else(|| format!("*{expr}"), str::to_string)
}

fn scalar_decode(base: &str) -> String {
    match base {
        "Boolean" => "reader.read_bool()".to_string(),
        "Int" => "reader.read_i32_le()".to_string(),
        "Float" => "reader.read_f32_le()".to_string(),
        "String" | "ID" => "reader.read_string()".to_string(),
        other => format!("dec_{}(reader)", to_snake_case(other)),
    }
}

/// Peel one list wrapper off `ty`, yielding the element's [`TypeReference`], or
/// `None` if `ty` is not a list. Ported from the TypeScript emitter so the two
/// agree on nested list / nullability handling.
fn list_item_type_reference(ty: &TypeReference) -> Option<TypeReference> {
    if !ty.is_list {
        return None;
    }

    if ty.list_wrappers.is_empty() {
        return Some(TypeReference {
            base: ty.base.clone(),
            nullable: ty.list_item_nullable.unwrap_or(true),
            is_list: false,
            list_item_nullable: None,
            list_wrappers: Vec::new(),
            leaf_nullable: None,
        });
    }

    let remaining = ty.list_wrappers[1..].to_vec();
    if remaining.is_empty() {
        return Some(TypeReference {
            base: ty.base.clone(),
            nullable: ty.leaf_nullable.unwrap_or(true),
            is_list: false,
            list_item_nullable: None,
            list_wrappers: Vec::new(),
            leaf_nullable: None,
        });
    }

    let next_nullable = remaining
        .get(1)
        .map(|wrapper| wrapper.nullable)
        .unwrap_or_else(|| ty.leaf_nullable.unwrap_or(true));
    Some(TypeReference {
        base: ty.base.clone(),
        nullable: remaining[0].nullable,
        is_list: true,
        list_item_nullable: Some(next_nullable),
        list_wrappers: remaining,
        leaf_nullable: ty.leaf_nullable,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use wesley_core::{Field, TypeListWrapper};

    fn scalar(base: &str, nullable: bool) -> TypeReference {
        TypeReference {
            base: base.to_string(),
            nullable,
            is_list: false,
            list_item_nullable: None,
            list_wrappers: Vec::new(),
            leaf_nullable: None,
        }
    }

    /// A non-null list of non-null `base` (`[base!]!`).
    fn list_of(base: &str) -> TypeReference {
        TypeReference {
            base: base.to_string(),
            nullable: false,
            is_list: true,
            list_item_nullable: Some(false),
            list_wrappers: vec![TypeListWrapper { nullable: false }],
            leaf_nullable: Some(false),
        }
    }

    fn field(name: &str, ty: TypeReference) -> Field {
        Field {
            name: name.to_string(),
            description: None,
            r#type: ty,
            arguments: Vec::new(),
            default_value: None,
            directives: Default::default(),
        }
    }

    fn type_def(
        name: &str,
        kind: TypeKind,
        fields: Vec<Field>,
        enum_values: Vec<String>,
    ) -> TypeDefinition {
        TypeDefinition {
            name: name.to_string(),
            kind,
            description: None,
            directives: Default::default(),
            implements: Vec::new(),
            fields,
            enum_values,
            union_members: Vec::new(),
        }
    }

    fn emit(types: Vec<TypeDefinition>) -> String {
        let ir = WesleyIR {
            version: "1.0.0".to_string(),
            metadata: None,
            types,
        };
        emit_le_binary_rust(&ir, &[], DEFAULT_CODEC_IMPORT)
    }

    #[test]
    fn emits_enum_codec_with_ordinal_discriminants() {
        let color = type_def(
            "Color",
            TypeKind::Enum,
            Vec::new(),
            vec!["RED".into(), "GREEN".into(), "BLUE".into()],
        );
        let rust = emit(vec![color]);

        assert!(rust.contains("use crate::codec::{CodecError, Reader, Writer};"));
        assert!(rust.contains("pub fn encode_color(value: &Color) -> Vec<u8> {"));
        assert!(rust.contains("pub fn decode_color(bytes: &[u8]) -> Result<Color, CodecError> {"));
        assert!(
            rust.contains("Color::Red => writer.write_u32_le(0),"),
            "{rust}"
        );
        assert!(
            rust.contains("Color::Blue => writer.write_u32_le(2),"),
            "{rust}"
        );
        assert!(rust.contains("let discriminant = reader.read_u32_le()?;"));
        assert!(rust.contains("0 => Ok(Color::Red),"), "{rust}");
        assert!(
            rust.contains(
                "other => Err(CodecError::new(format!(\"invalid Color discriminant: {other}\"))),"
            ),
            "{rust}"
        );
    }

    #[test]
    fn emits_object_codec_with_required_nullable_and_list_fields() {
        let widget = type_def(
            "Widget",
            TypeKind::Object,
            vec![
                field("label", scalar("String", false)),
                field("count", scalar("Int", false)),
                field("color", scalar("Color", true)),
                field("tags", list_of("String")),
            ],
            Vec::new(),
        );
        let rust = emit(vec![widget]);

        // required String -> direct write_string with a borrow
        assert!(
            rust.contains("writer.write_string(&value.label);"),
            "{rust}"
        );
        // required Int (Copy) -> no stray `*&`
        assert!(rust.contains("writer.write_i32_le(value.count);"), "{rust}");
        // nullable enum -> write_option wrapping the enum encoder
        assert!(
            rust.contains("writer.write_option(&value.color, |writer, x| enc_color(writer, x));"),
            "{rust}"
        );
        // required list of String! -> write_list, element borrowed
        assert!(
            rust.contains("writer.write_list(&value.tags, |writer, x| writer.write_string(x));"),
            "{rust}"
        );
        // decode builds the struct with `?` per field
        assert!(rust.contains("label: reader.read_string()?,"), "{rust}");
        assert!(rust.contains("count: reader.read_i32_le()?,"), "{rust}");
        assert!(
            rust.contains("color: reader.read_option(|reader| dec_color(reader))?,"),
            "{rust}"
        );
        assert!(
            rust.contains("tags: reader.read_list(|reader| reader.read_string())?,"),
            "{rust}"
        );
    }

    #[test]
    fn emits_le_binary_rust_from_golden_fixture() {
        use wesley_core::{list_schema_operations_sdl, lower_schema_sdl};
        let sdl = include_str!("../../../test/fixtures/typescript-emitter/le-binary-codec.graphql");
        let expected =
            include_str!("../../../test/fixtures/rust-emitter/le-binary-codec.generated.rs");
        let ir = lower_schema_sdl(sdl).expect("golden schema lowers");
        let ops = list_schema_operations_sdl(sdl).expect("golden operations enumerable");

        assert_eq!(
            emit_le_binary_rust(&ir, &ops, DEFAULT_CODEC_IMPORT),
            expected
        );
    }

    #[test]
    fn skips_operation_root_types() {
        let mutation = type_def("Mutation", TypeKind::Object, Vec::new(), Vec::new());
        let ir = WesleyIR {
            version: "1.0.0".to_string(),
            metadata: None,
            types: vec![mutation],
        };
        let operations = [make_operation("Mutation")];
        let rust = emit_le_binary_rust(&ir, &operations, DEFAULT_CODEC_IMPORT);
        assert!(!rust.contains("encode_mutation"), "{rust}");
    }

    /// A minimal `SchemaOperation` whose root type is `root`.
    fn make_operation(root: &str) -> SchemaOperation {
        use wesley_core::OperationType;
        SchemaOperation {
            operation_type: OperationType::Mutation,
            root_type_name: root.to_string(),
            field_name: "noop".to_string(),
            arguments: Vec::new(),
            result_type: scalar("Boolean", false),
            directives: Default::default(),
        }
    }
}
