name: Claude JSDoc Enhancement

on:
  push:
    # Triggers on ANY push to ANY branch with JS changes
    paths:
      - "**/*.js"
      - "**/*.mjs"
      - "starfleet/**/*.js"

jobs:
  analyze-jsdoc:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
      id-token: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      
      - name: Get changed files
        id: changed-files
        run: |
          echo "Changed JavaScript files in this push:"
          git diff --name-only HEAD^ HEAD | grep -E '\.(js|mjs)$' || echo "No JS files changed"
          echo "files=$(git diff --name-only HEAD^ HEAD | grep -E '\.(js|mjs)$' | head -5 | tr '\n' ' ')" >> $GITHUB_OUTPUT

      - name: Analyze JSDoc Coverage
        if: steps.changed-files.outputs.files != ''
        run: |
          echo "📚 JSDoc Coverage Analysis for Changed Files"
          echo "============================================"
          for file in ${{ steps.changed-files.outputs.files }}; do
            if [ -f "$file" ]; then
              echo ""
              echo "File: $file"
              echo "Classes: $(grep -c "^class " "$file" || echo 0)"
              echo "Functions: $(grep -c "^function \|^async function" "$file" || echo 0)"
              echo "Existing JSDoc: $(grep -c "/\*\*" "$file" || echo 0)"
            fi
          done
          echo ""
          echo "This workflow detected changed JavaScript files."
          echo "In production, Claude would analyze these and create a PR with JSDoc enhancements."

      - name: Run Claude JSDoc Enhancement
        if: steps.changed-files.outputs.files != ''
        uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          prompt: |
            You need to add comprehensive JSDoc to these JavaScript files:
            ${{ steps.changed-files.outputs.files }}
            
            Follow these steps:
            1. First, check if we're not already on a jsdoc branch: git branch --show-current
            2. If not on a jsdoc branch, create a new branch: git checkout -b auto/jsdoc-enhancement-${{ github.run_number }}
            3. Read each file and add JSDoc where missing (classes, functions, methods)
            4. Follow the patterns from docs/decisions/000-javascript-not-typescript.md
            5. After editing files, commit: git add -A && git commit -m "docs: Add comprehensive JSDoc documentation
            
            - Added @fileoverview headers
            - Added @param and @returns annotations  
            - Added @throws for error conditions
            - Added @example for complex functions
            
            Auto-generated by Claude"
            6. Push the branch: git push origin auto/jsdoc-enhancement-${{ github.run_number }}
            7. Create a PR: gh pr create --base ${{ github.ref_name }} --title "📚 AI JSDoc Enhancement" --body "This PR adds comprehensive JSDoc documentation to recently modified JavaScript files.
            
            Files enhanced:
            ${{ steps.changed-files.outputs.files }}
            
            Generated automatically by Claude following patterns from docs/decisions/000-javascript-not-typescript.md"
          claude_args: '--allowed-tools "Read,Edit,MultiEdit,Bash(git:*),Bash(gh pr create:*)"'