name: Docs Link Check

permissions:
  contents: read

on:
  pull_request:
    paths:
      - '**/*.md'
      - 'scripts/check-doc-links.mjs'
  push:
    branches:
      - main
    paths:
      - '**/*.md'
      - 'scripts/check-doc-links.mjs'

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Check markdown links (relative only)
        run: node scripts/check-doc-links.mjs
