name: install-bats

on:
  workflow_call:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Install bats and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y bats jq
