name: install-bats

on:
  workflow_call:

permissions:
  contents: read

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df
        with:
          egress-policy: audit
      - name: Install bats and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y bats jq
