name: pkg-generator-js

on:
  push:
    branches: ["**"]
    paths:
      - 'packages/wesley-generator-js/**'
      - 'pnpm-lock.yaml'
      - 'package.json'
  pull_request:
    branches: ["**"]
    paths:
      - 'packages/wesley-generator-js/**'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176
        with:
          egress-policy: audit
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: pnpm/action-setup@08c4be7e2e672a47d11bd04269e27e5f3e8529cb
        with:
          version: 9.15.9
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
        with:
          node-version: 22
      - name: Enable corepack (pnpm)
        run: corepack enable
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: "@wesley/generator-js tests"
        run: pnpm --filter @wesley/generator-js test
