name: Runtime Smokes

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  deno-smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x
      - name: Deno smoke
        run: deno run --config deno.json -A scripts/deno_smoke.ts | tee deno.out && grep -q "^DENO_SMOKE_OK:" deno.out

  bun-smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Bun smoke
        run: bun run scripts/bun_smoke.mjs | tee bun.out && grep -q "^BUN_SMOKE_OK:" bun.out

