name: wesley-website

on:
  push:
    branches: [ main ]
    paths:
      - 'wesley-website/**'
      - '.github/workflows/wesley-website.yml'
  pull_request:
    paths:
      - 'wesley-website/**'
      - '.github/workflows/wesley-website.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - name: Verify pnpm version
        run: |
          echo "pnpm: $(pnpm --version)"
          node -v
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Verify lockfile unchanged
        run: git diff --exit-code -- pnpm-lock.yaml

      - name: Build website
        run: pnpm --filter wesley-website run build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: wesley-website/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
